#!/usr/bin/env python3
"""Comprehensive IMM instruction debugging."""
import torch
from neural_vm.vm_step import AutoregressiveVM, set_vm_weights, Token, _SetDim
from neural_vm.embedding import Opcode
from neural_vm.run_vm import AutoregressiveVMRunner

BD = _SetDim

print("=" * 80)
print("COMPREHENSIVE IMM INSTRUCTION DEBUG")
print("=" * 80)

model = AutoregressiveVM()
set_vm_weights(model)
model = model.cuda()
model.eval()

runner = AutoregressiveVMRunner()
runner.model = model
bytecode = [Opcode.IMM | (42 << 8), Opcode.EXIT]

print(f"\nProgram: IMM 42 (0x2a), EXIT")
print(f"Bytecode[0]: 0x{bytecode[0]:08x}")
print(f"  Opcode: 0x{bytecode[0] & 0xFF:02x} (IMM)")
print(f"  Immediate: 0x{bytecode[0] >> 8:08x} (42)\n")

context = runner._build_context(bytecode, b'', [])

# Show code section layout
print("Code section layout:")
code_start = 0  # CODE_START token at position 0
for i in range(17):  # Up to CODE_END
    byte = context[code_start + 1 + i]
    if byte < 256:
        print(f"  Address {i:2d}: 0x{byte:02x}", end="")
        if i == 0:
            print(" (IMM opcode)")
        elif i == 1:
            print(" (immediate byte 0 = 42)")
        elif i in [2, 3, 4]:
            print(f" (immediate byte {i-1})")
        elif i in [5, 6, 7]:
            print(f" (padding byte {i-5})")
        elif i == 8:
            print(" (EXIT opcode)")
        else:
            print()
    else:
        print(f"  Address {i:2d}: TOKEN {byte}")

print("\n" + "=" * 80)
print("STEP 0: IMM EXECUTION")
print("=" * 80)

# Generate step 0
for i in range(100):
    tok = model.generate_next(context)
    context.append(tok)
    if tok == Token.STEP_END:
        print(f"Step 0 complete at token {i}")
        break

# Find REG_AX in step 0
reg_ax_pos = None
for pos in range(20, len(context)):
    if context[pos] == 260:  # REG_AX
        reg_ax_pos = pos
        break

if reg_ax_pos:
    print(f"\nREG_AX marker at position {reg_ax_pos}")

    # Check what model PREDICTS at REG_AX marker
    token_ids = torch.tensor([context[:reg_ax_pos+1]], dtype=torch.long, device='cuda')
    with torch.no_grad():
        logits = model.forward(token_ids)

    print("\n--- MODEL PREDICTIONS at REG_AX marker ---")
    for i in range(4):
        pred = logits[0, reg_ax_pos, :256].argmax(-1).item()
        top5 = torch.topk(logits[0, reg_ax_pos, :256], 5)

        print(f"\nByte {i} prediction:")
        print(f"  Top choice: 0x{pred:02x}")
        print(f"  Top 5: {', '.join(f'0x{idx.item():02x}({val.item():.1f})' for val, idx in zip(top5.values, top5.indices))}")

    # Check what was GENERATED
    print("\n--- GENERATED BYTES after REG_AX ---")
    generated_bytes = []
    for i in range(4):
        if reg_ax_pos + 1 + i < len(context):
            byte_val = context[reg_ax_pos + 1 + i]
            generated_bytes.append(byte_val)
            print(f"  Byte {i}: 0x{byte_val:02x}")
        else:
            print(f"  Byte {i}: NOT YET GENERATED")

    if len(generated_bytes) == 4:
        ax_value = sum(b << (i*8) for i, b in enumerate(generated_bytes))
        print(f"\n  Generated AX value: 0x{ax_value:08x} ({ax_value})")
        print(f"  Expected AX value:  0x0000002a (42)")

        if ax_value == 42:
            print("  ✓ CORRECT!")
        else:
            print(f"  ✗ WRONG!")

            # Analyze the wrong value
            print(f"\n  Wrong value analysis:")
            print(f"    Binary: {bin(ax_value)}")
            print(f"    Set bytes: {[i for i, b in enumerate(generated_bytes) if b != 0]}")
            print(f"    Non-zero bytes: {[(i, hex(b)) for i, b in enumerate(generated_bytes) if b != 0]}")

print("\n" + "=" * 80)
print("LAYER-BY-LAYER ANALYSIS AT REG_AX")
print("=" * 80)

if reg_ax_pos:
    token_ids = torch.tensor([context[:reg_ax_pos+1]], dtype=torch.long, device='cuda')

    with torch.no_grad():
        x = model.embed(token_ids)

        # Check key layers
        for layer_idx in [0, 1, 2, 3, 4, 5, 6]:
            if layer_idx > 0:
                x = model.blocks[layer_idx - 1](x, kv_cache=None)

            layer_name = f"After Layer {layer_idx-1}" if layer_idx > 0 else "After Embedding"

            # Check AX-related dimensions
            print(f"\n{layer_name}:")

            # Check opcode detection
            if layer_idx >= 2:
                print(f"  OP_IMM: {x[0, reg_ax_pos, BD.OP_IMM].item():.3f}")

            # Check immediate fetch
            if layer_idx >= 5:
                fetch_vals = []
                for i in range(16):
                    val = x[0, reg_ax_pos, BD.FETCH_LO + i].item()
                    if abs(val) > 0.1:
                        fetch_vals.append((i, val))

                if fetch_vals:
                    print(f"  FETCH_LO non-zero: {fetch_vals[:5]}")
                    max_idx, max_val = max(fetch_vals, key=lambda x: x[1])
                    print(f"  FETCH_LO max: index={max_idx} (0x{max_idx:02x}), value={max_val:.3f}")

            # Check OUTPUT
            if layer_idx >= 6:
                output_vals = []
                for i in range(16):
                    val = x[0, reg_ax_pos, BD.OUTPUT_LO + i].item()
                    if abs(val) > 0.1:
                        output_vals.append((i, val))

                if output_vals:
                    print(f"  OUTPUT_LO non-zero: {output_vals[:5]}")
                    max_idx, max_val = max(output_vals, key=lambda x: abs(x[1]))
                    print(f"  OUTPUT_LO max: index={max_idx} (0x{max_idx:02x}), value={max_val:.3f}")

print("\n" + "=" * 80)
print("SUMMARY")
print("=" * 80)
print(f"Expected: AX = 0x2a (42)")
if len(generated_bytes) == 4:
    ax_value = sum(b << (i*8) for i, b in enumerate(generated_bytes))
    print(f"Actual:   AX = 0x{ax_value:08x} ({ax_value})")
    print(f"Status:   {'PASS ✓' if ax_value == 42 else 'FAIL ✗'}")
