/*
 * Neural VM Bundler - C4 Compatible Version
 *
 * Reads a compiled bytecode file and sparse weights,
 * outputs a standalone C file that can be compiled without libc.
 *
 * c4 limitations:
 *   - No float/double (use int fixed-point)
 *   - No for loops (use while)
 *   - No switch (use if/else)
 *   - Only: printf, malloc, free, memset, memcpy, open, read, close, exit
 *
 * Usage:
 *   ./bundle_c4 bytecode.bin weights.bin > output.c
 *
 * Build with c4:
 *   ./c4 bundle_c4.c bytecode.bin weights.bin > output.c
 *
 * Build with gcc:
 *   gcc -o bundle_c4 bundle_c4.c
 */

/* File I/O */
int open(char *path, int mode);
int read(int fd, char *buf, int n);
int close(int fd);

/* Memory */
char *malloc(int size);
int free(char *ptr);
char *memset(char *s, int c, int n);
char *memcpy(char *dst, char *src, int n);

/* Output */
int printf(char *fmt, ...);
int putchar(int c);

/* Exit */
int exit(int code);

/* Globals */
int bytecode_fd;
int weights_fd;
char *bytecode;
int bytecode_len;
char *weights;
int weights_len;

/* Read entire file into buffer */
char *read_file(char *path, int *out_len) {
    int fd;
    int n;
    int total;
    int capacity;
    char *buf;
    char *newbuf;
    char tmp[1024];

    fd = open(path, 0);
    if (fd < 0) {
        printf("/* Error: cannot open %s */\n", path);
        return 0;
    }

    capacity = 4096;
    buf = malloc(capacity);
    total = 0;

    n = read(fd, tmp, 1024);
    while (n > 0) {
        /* Grow buffer if needed */
        if (total + n > capacity) {
            capacity = capacity * 2;
            newbuf = malloc(capacity);
            memcpy(newbuf, buf, total);
            free(buf);
            buf = newbuf;
        }

        memcpy(buf + total, tmp, n);
        total = total + n;
        n = read(fd, tmp, 1024);
    }

    close(fd);
    *out_len = total;
    return buf;
}

/* Print byte as hex */
int print_hex(int b) {
    int hi;
    int lo;
    char hex[17];

    hex[0] = '0'; hex[1] = '1'; hex[2] = '2'; hex[3] = '3';
    hex[4] = '4'; hex[5] = '5'; hex[6] = '6'; hex[7] = '7';
    hex[8] = '8'; hex[9] = '9'; hex[10] = 'a'; hex[11] = 'b';
    hex[12] = 'c'; hex[13] = 'd'; hex[14] = 'e'; hex[15] = 'f';

    b = b & 255;
    hi = (b >> 4) & 15;
    lo = b & 15;

    putchar('0');
    putchar('x');
    putchar(hex[hi]);
    putchar(hex[lo]);

    return 0;
}

/* Print C array of bytes */
int print_byte_array(char *name, char *data, int len) {
    int i;
    int per_line;

    per_line = 16;

    printf("static const unsigned char %s[] = {\n", name);

    i = 0;
    while (i < len) {
        if ((i % per_line) == 0) {
            printf("    ");
        }

        print_hex(data[i]);

        if (i + 1 < len) {
            putchar(',');
        }

        if ((i % per_line) == per_line - 1 || i + 1 == len) {
            putchar('\n');
        }

        i = i + 1;
    }

    printf("};\n");
    printf("static const int %s_len = %d;\n\n", name, len);

    return 0;
}

/* Print freestanding runtime header */
int print_runtime_header() {
    printf("/*\n");
    printf(" * Neural VM Bundle - Generated by bundle_c4\n");
    printf(" * Freestanding - no libc required\n");
    printf(" */\n\n");

    printf("typedef long long int64;\n");
    printf("typedef unsigned long long uint64;\n");
    printf("typedef unsigned char byte;\n\n");

    return 0;
}

/* Print syscall wrappers */
int print_syscalls() {
    printf("/* System calls */\n");
    printf("#ifdef __APPLE__\n");
    printf("#define SYS_exit 0x2000001\n");
    printf("#define SYS_read 0x2000003\n");
    printf("#define SYS_write 0x2000004\n");
    printf("#else\n");
    printf("#define SYS_exit 60\n");
    printf("#define SYS_read 0\n");
    printf("#define SYS_write 1\n");
    printf("#endif\n\n");

    printf("#ifdef __aarch64__\n");
    printf("static inline int64 syscall3(int64 n, int64 a, int64 b, int64 c) {\n");
    printf("    register int64 x16 __asm__(\"x16\") = n;\n");
    printf("    register int64 x0 __asm__(\"x0\") = a;\n");
    printf("    register int64 x1 __asm__(\"x1\") = b;\n");
    printf("    register int64 x2 __asm__(\"x2\") = c;\n");
    printf("    __asm__ volatile(\"svc #0x80\" : \"+r\"(x0) : \"r\"(x16), \"r\"(x1), \"r\"(x2) : \"memory\");\n");
    printf("    return x0;\n");
    printf("}\n");
    printf("static inline void syscall1(int64 n, int64 a) {\n");
    printf("    register int64 x16 __asm__(\"x16\") = n;\n");
    printf("    register int64 x0 __asm__(\"x0\") = a;\n");
    printf("    __asm__ volatile(\"svc #0x80\" : : \"r\"(x16), \"r\"(x0));\n");
    printf("}\n");
    printf("#else\n");
    printf("static inline int64 syscall3(int64 n, int64 a, int64 b, int64 c) {\n");
    printf("    int64 r;\n");
    printf("    __asm__ volatile(\"syscall\" : \"=a\"(r) : \"a\"(n), \"D\"(a), \"S\"(b), \"d\"(c) : \"rcx\", \"r11\", \"memory\");\n");
    printf("    return r;\n");
    printf("}\n");
    printf("static inline void syscall1(int64 n, int64 a) {\n");
    printf("    __asm__ volatile(\"syscall\" : : \"a\"(n), \"D\"(a) : \"rcx\", \"r11\", \"memory\");\n");
    printf("}\n");
    printf("#endif\n\n");

    printf("static void sys_exit(int code) { syscall1(SYS_exit, code); }\n");
    printf("static int sys_write(int fd, void *buf, int len) { return (int)syscall3(SYS_write, fd, (int64)buf, len); }\n");
    printf("static int sys_read(int fd, void *buf, int len) { return (int)syscall3(SYS_read, fd, (int64)buf, len); }\n");
    printf("static void putchar_raw(int c) { byte ch = c; sys_write(1, &ch, 1); }\n");
    printf("static int getchar_raw(void) { byte ch; int n = sys_read(0, &ch, 1); return n <= 0 ? 0 : ch; }\n\n");

    return 0;
}

/* Print VM code */
int print_vm() {
    printf("/* Memory */\n");
    printf("#define MEM_SIZE (1024*1024)\n");
    printf("static byte memory[MEM_SIZE];\n");
    printf("#define DATA_BASE 0x10000\n");
    printf("#define STACK_BASE 0x90000\n\n");

    printf("static void mcopy(void *d, void *s, int n) { byte *a=d; byte *b=s; while(n-->0) *a++=*b++; }\n\n");

    printf("/* VM state */\n");
    printf("static int64 *code;\n");
    printf("static int code_len;\n");
    printf("static int64 pc, sp, bp, ax;\n");
    printf("static int halted;\n\n");

    printf("static int64 mem_ri(int64 a) { return *(int64*)(memory+a); }\n");
    printf("static void mem_wi(int64 a, int64 v) { *(int64*)(memory+a) = v; }\n");
    printf("static byte mem_rb(int64 a) { return memory[a]; }\n");
    printf("static void mem_wb(int64 a, byte v) { memory[a] = v; }\n\n");

    printf("/* Opcodes */\n");
    printf("enum { LEA,IMM,JMP,JSR,BZ,BNZ,ENT,ADJ,LEV,LI,LC,SI,SC,PSH,\n");
    printf("       OR,XOR,AND,EQ,NE,LT,GT,LE,GE,SHL,SHR,ADD,SUB,MUL,DIV,MOD,\n");
    printf("       OPEN,READ,CLOS,PRTF,MALC,FREE,MSET,MCMP,EXIT_OP };\n");
    printf("#define GETC_OP 64\n");
    printf("#define PUTC_OP 65\n\n");

    printf("static int step(void) {\n");
    printf("    int64 op,imm,a;\n");
    printf("    if (halted) return 1;\n");
    printf("    if (pc<0 || pc>=code_len*8) { halted=1; return 1; }\n");
    printf("    op = code[pc/8] & 0xFF;\n");
    printf("    imm = code[pc/8] >> 8;\n");
    printf("    if (imm >= (1LL<<55)) imm -= (1LL<<56);\n");
    printf("    pc += 8;\n");
    printf("    if (op==LEA) ax=bp+imm;\n");
    printf("    else if (op==IMM) ax=imm;\n");
    printf("    else if (op==JMP) pc=imm;\n");
    printf("    else if (op==JSR) { sp-=8; mem_wi(sp,pc); pc=imm; }\n");
    printf("    else if (op==BZ) { if (ax==0) pc=imm; }\n");
    printf("    else if (op==BNZ) { if (ax!=0) pc=imm; }\n");
    printf("    else if (op==ENT) { sp-=8; mem_wi(sp,bp); bp=sp; sp-=imm; }\n");
    printf("    else if (op==ADJ) sp+=imm;\n");
    printf("    else if (op==LEV) { sp=bp; bp=mem_ri(sp); sp+=8; pc=mem_ri(sp); sp+=8; }\n");
    printf("    else if (op==LI) ax=mem_ri(ax);\n");
    printf("    else if (op==LC) ax=mem_rb(ax);\n");
    printf("    else if (op==SI) { a=mem_ri(sp); sp+=8; mem_wi(a,ax); }\n");
    printf("    else if (op==SC) { a=mem_ri(sp); sp+=8; mem_wb(a,(byte)ax); }\n");
    printf("    else if (op==PSH) { sp-=8; mem_wi(sp,ax); }\n");
    printf("    else if (op==ADD) { a=mem_ri(sp); sp+=8; ax=a+ax; }\n");
    printf("    else if (op==SUB) { a=mem_ri(sp); sp+=8; ax=a-ax; }\n");
    printf("    else if (op==MUL) { a=mem_ri(sp); sp+=8; ax=a*ax; }\n");
    printf("    else if (op==DIV) { a=mem_ri(sp); sp+=8; ax=ax?a/ax:0; }\n");
    printf("    else if (op==MOD) { a=mem_ri(sp); sp+=8; ax=ax?a%%ax:0; }\n");
    printf("    else if (op==AND) { a=mem_ri(sp); sp+=8; ax=a&ax; }\n");
    printf("    else if (op==OR) { a=mem_ri(sp); sp+=8; ax=a|ax; }\n");
    printf("    else if (op==XOR) { a=mem_ri(sp); sp+=8; ax=a^ax; }\n");
    printf("    else if (op==SHL) { a=mem_ri(sp); sp+=8; ax=a<<ax; }\n");
    printf("    else if (op==SHR) { a=mem_ri(sp); sp+=8; ax=(int64)((uint64)a>>ax); }\n");
    printf("    else if (op==EQ) { a=mem_ri(sp); sp+=8; ax=(a==ax); }\n");
    printf("    else if (op==NE) { a=mem_ri(sp); sp+=8; ax=(a!=ax); }\n");
    printf("    else if (op==LT) { a=mem_ri(sp); sp+=8; ax=(a<ax); }\n");
    printf("    else if (op==GT) { a=mem_ri(sp); sp+=8; ax=(a>ax); }\n");
    printf("    else if (op==LE) { a=mem_ri(sp); sp+=8; ax=(a<=ax); }\n");
    printf("    else if (op==GE) { a=mem_ri(sp); sp+=8; ax=(a>=ax); }\n");
    printf("    else if (op==GETC_OP) ax=getchar_raw();\n");
    printf("    else if (op==PUTC_OP) putchar_raw((int)mem_ri(sp));\n");
    printf("    else if (op==EXIT_OP) { halted=1; return (int)mem_ri(sp); }\n");
    printf("    return 0;\n");
    printf("}\n\n");

    printf("static int run(void) {\n");
    printf("    int cycles = 0;\n");
    printf("    sp = STACK_BASE + 0x40000 - 8;\n");
    printf("    bp = sp; pc = 0; ax = 0; halted = 0;\n");
    printf("    code = (int64*)bundled_bytecode;\n");
    printf("    code_len = bundled_bytecode_len / 8;\n");
    printf("    if (bundled_data_len > 0) mcopy(memory+DATA_BASE, (void*)bundled_data, bundled_data_len);\n");
    printf("    while (!halted && cycles < 100000000) { step(); cycles++; }\n");
    printf("    return (int)ax;\n");
    printf("}\n\n");

    return 0;
}

/* Print entry point */
int print_entry() {
    printf("__attribute__((visibility(\"default\")))\n");
    printf("__attribute__((used))\n");
    printf("void _start(void) { sys_exit(run()); }\n\n");

    printf("int main(void) { return run(); }\n");

    return 0;
}

/* Main */
int main(int argc, char **argv) {
    char *bytecode_path;
    char *weights_path;

    if (argc < 2) {
        printf("/* Usage: bundle_c4 bytecode.bin [weights.bin] */\n");
        exit(1);
    }

    bytecode_path = argv[1];
    weights_path = 0;
    if (argc > 2) {
        weights_path = argv[2];
    }

    /* Read bytecode */
    bytecode = read_file(bytecode_path, &bytecode_len);
    if (!bytecode) {
        exit(1);
    }

    /* Read weights if provided */
    if (weights_path) {
        weights = read_file(weights_path, &weights_len);
    }

    /* Generate output */
    print_runtime_header();
    print_syscalls();

    /* Bytecode array */
    print_byte_array("bundled_bytecode", bytecode, bytecode_len);

    /* Data section (empty for now) */
    printf("static const unsigned char bundled_data[] = {};\n");
    printf("static const int bundled_data_len = 0;\n\n");

    /* Weights if provided */
    if (weights && weights_len > 0) {
        print_byte_array("bundled_weights", weights, weights_len);
    }

    /* VM code */
    print_vm();

    /* Entry point */
    print_entry();

    return 0;
}
