/*
 * C4 Neural - A C compiler and VM with ONNX-based arithmetic
 *
 * This is a c4-compatible implementation that:
 * 1. Compiles C source code to bytecode
 * 2. Executes bytecode with neural arithmetic operations
 * 3. Supports stdin/stdout for I/O
 *
 * Usage:
 *   ./c4_neural -e '6 * 7'                    # Evaluate expression
 *   ./c4_neural -c 'int main() { return 42; }'  # Run C code
 *   ./c4_neural program.c                     # Run from file
 *   echo "input" | ./c4_neural program.c      # With stdin
 *
 * Build with gcc:
 *   gcc -include stdio.h -include stdlib.h -include fcntl.h -include unistd.h \
 *       -include string.h -w -o c4_neural c4_neural.c
 */

/* ============ Constants ============ */

int POOL_SIZE;
int DATA_BASE;

/* Token types */
int TK_NUM;   int TK_ID;    int TK_STR;
int TK_INT;   int TK_CHAR;  int TK_ENUM;
int TK_IF;    int TK_ELSE;  int TK_WHILE;
int TK_RET;   int TK_SIZEOF;
int TK_ASSIGN; int TK_OR;   int TK_AND;
int TK_EQ;    int TK_NE;    int TK_LT;
int TK_GT;    int TK_LE;    int TK_GE;
int TK_SHL;   int TK_SHR;   int TK_ADD;
int TK_SUB;   int TK_MUL;   int TK_DIV;
int TK_MOD;   int TK_INC;   int TK_DEC;
int TK_BRAK;  int TK_EOF;

/* Opcodes */
int OP_LEA;  int OP_IMM;  int OP_JMP;  int OP_JSR;
int OP_BZ;   int OP_BNZ;  int OP_ENT;  int OP_ADJ;
int OP_LEV;  int OP_LI;   int OP_LC;   int OP_SI;
int OP_SC;   int OP_PSH;
int OP_OR;   int OP_XOR;  int OP_AND;
int OP_EQ;   int OP_NE;   int OP_LT;   int OP_GT;
int OP_LE;   int OP_GE;   int OP_SHL;  int OP_SHR;
int OP_ADD;  int OP_SUB;  int OP_MUL;  int OP_DIV;
int OP_MOD;  int OP_EXIT;
int OP_GETCHAR; int OP_PUTCHAR;

/* Type constants */
int TY_CHAR; int TY_INT; int TY_PTR;

/* ============ Global State ============ */

/* Lexer */
char *src;
int src_pos;
int line;
int tk;        /* current token */
int tk_val;    /* token value (for numbers) */
char *tk_str;  /* token string (for identifiers) */
int tk_len;    /* token string length */

/* Parser */
int *code;     /* generated bytecode */
int code_pos;
char *data;    /* data segment */
int data_pos;
int expr_type; /* type of current expression */

/* Symbol table - simple linear array */
char **sym_names;
int *sym_class;   /* 0=none, 1=Num, 2=Fun, 3=Sys, 4=Glo, 5=Loc */
int *sym_type;
int *sym_val;
int *sym_hclass;  /* hidden class (for locals) */
int *sym_htype;
int *sym_hval;
int sym_count;
int MAX_SYMS;

/* Local variable tracking */
int local_offset;

/* VM state */
int *vm_mem;
int vm_sp;
int vm_bp;
int vm_ax;
int vm_pc;
int vm_halted;

/* I/O */
char *stdin_buf;
int stdin_pos;
int stdin_len;
char *stdout_buf;
int stdout_pos;

/* Neural arithmetic - fixed point */
int SCALE;
int *exp_tbl;

/* ============ Initialize Constants ============ */

int init_constants() {
    POOL_SIZE = 65536;
    DATA_BASE = 0x10000;

    /* Token types */
    TK_NUM = 1;   TK_ID = 2;    TK_STR = 3;
    TK_INT = 10;  TK_CHAR = 11; TK_ENUM = 12;
    TK_IF = 13;   TK_ELSE = 14; TK_WHILE = 15;
    TK_RET = 16;  TK_SIZEOF = 17;
    TK_ASSIGN = 20;
    TK_OR = 22;   TK_AND = 23;
    TK_EQ = 27;   TK_NE = 28;
    TK_LT = 29;   TK_GT = 30;   TK_LE = 31;   TK_GE = 32;
    TK_SHL = 33;  TK_SHR = 34;
    TK_ADD = 35;  TK_SUB = 36;
    TK_MUL = 37;  TK_DIV = 38;  TK_MOD = 39;
    TK_INC = 40;  TK_DEC = 41;
    TK_BRAK = 42;
    TK_EOF = 99;

    /* Opcodes */
    OP_LEA = 0;  OP_IMM = 1;  OP_JMP = 2;  OP_JSR = 3;
    OP_BZ = 4;   OP_BNZ = 5;  OP_ENT = 6;  OP_ADJ = 7;
    OP_LEV = 8;  OP_LI = 9;   OP_LC = 10;  OP_SI = 11;
    OP_SC = 12;  OP_PSH = 13;
    OP_OR = 14;  OP_XOR = 15; OP_AND = 16;
    OP_EQ = 17;  OP_NE = 18;  OP_LT = 19;  OP_GT = 20;
    OP_LE = 21;  OP_GE = 22;  OP_SHL = 23; OP_SHR = 24;
    OP_ADD = 25; OP_SUB = 26; OP_MUL = 27; OP_DIV = 28;
    OP_MOD = 29;
    OP_EXIT = 38;
    OP_GETCHAR = 64;
    OP_PUTCHAR = 65;

    /* Types */
    TY_CHAR = 0; TY_INT = 1; TY_PTR = 2;

    MAX_SYMS = 256;

    return 0;
}

/* ============ Fixed-Point Neural Arithmetic ============ */

int init_neural() {
    SCALE = 256;
    exp_tbl = malloc(64);
    exp_tbl[0] = 256;
    exp_tbl[1] = 94;
    exp_tbl[2] = 35;
    exp_tbl[3] = 13;
    exp_tbl[4] = 5;
    exp_tbl[5] = 2;
    exp_tbl[6] = 1;
    exp_tbl[7] = 0;
    return 0;
}

int fp_exp_neg(int x) {
    int idx; int frac; int e1; int e2;
    if (x <= 0) return SCALE;
    if (x >= SCALE * 7) return 0;
    idx = x / SCALE;
    if (idx >= 6) return 0;
    frac = x - idx * SCALE;
    e1 = exp_tbl[idx];
    e2 = exp_tbl[idx + 1];
    return e1 + ((e2 - e1) * frac) / SCALE;
}

int fp_sigmoid(int x) {
    int exp_neg_x; int denom;
    if (x >= SCALE * 6) return SCALE;
    if (x <= 0 - SCALE * 6) return 0;
    if (x >= 0) {
        exp_neg_x = fp_exp_neg(x);
        denom = SCALE + exp_neg_x;
        return (SCALE * SCALE) / denom;
    } else {
        exp_neg_x = fp_exp_neg(0 - x);
        if (exp_neg_x == 0) return 0;
        denom = exp_neg_x + SCALE;
        return (exp_neg_x * SCALE) / denom;
    }
}

int fp_silu(int x) {
    int sig;
    sig = fp_sigmoid(x);
    return (x * sig) / SCALE;
}

/* SwiGLU multiply: silu(a)*b + silu(-a)*(-b) = a*b */
int neural_mul(int a, int b) {
    int a_fp; int silu_a; int silu_neg_a;
    int term1; int term2; int result_fp;

    a_fp = a * SCALE;
    silu_a = fp_silu(a_fp);
    silu_neg_a = fp_silu(0 - a_fp);
    term1 = (silu_a / SCALE) * b + ((silu_a % SCALE) * b) / SCALE;
    term2 = (silu_neg_a / SCALE) * (0 - b) + ((silu_neg_a % SCALE) * (0 - b)) / SCALE;
    result_fp = term1 + term2;
    return result_fp / SCALE;
}

/* Simple division via repeated subtraction */
int neural_div(int a, int b) {
    int result; int neg;
    if (b == 0) return 0;
    neg = 0;
    if (a < 0) { a = 0 - a; neg = neg + 1; }
    if (b < 0) { b = 0 - b; neg = neg + 1; }
    result = 0;
    while (a >= b) { a = a - b; result = result + 1; }
    if (neg == 1) return 0 - result;
    return result;
}

/* Nibble-based addition */
int neural_add(int a, int b) {
    int result; int carry; int i; int shift;
    int nibble_a; int nibble_b; int sum; int total;
    result = 0;
    carry = 0;
    i = 0;
    while (i < 8) {
        shift = i * 4;
        nibble_a = (a / (1 << shift)) & 15;
        nibble_b = (b / (1 << shift)) & 15;
        total = nibble_a + nibble_b + carry;
        sum = total & 15;
        carry = (total / 16) & 1;
        result = result | (sum << shift);
        i = i + 1;
    }
    return result;
}

/* ============ String Utilities ============ */

int str_eq(char *a, int alen, char *b, int blen) {
    int i;
    if (alen != blen) return 0;
    i = 0;
    while (i < alen) {
        if (a[i] != b[i]) return 0;
        i = i + 1;
    }
    return 1;
}

int is_digit(int c) { return c >= '0' && c <= '9'; }
int is_alpha(int c) { return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_'; }
int is_alnum(int c) { return is_digit(c) || is_alpha(c); }

/* ============ Lexer ============ */

int next_token() {
    int c; int num; int str_start;

    /* Skip whitespace and comments */
    while (1) {
        while (src[src_pos] == ' ' || src[src_pos] == '\t' || src[src_pos] == '\n' || src[src_pos] == '\r') {
            if (src[src_pos] == '\n') line = line + 1;
            src_pos = src_pos + 1;
        }
        if (src[src_pos] == '/' && src[src_pos + 1] == '/') {
            while (src[src_pos] && src[src_pos] != '\n') src_pos = src_pos + 1;
        } else if (src[src_pos] == '/' && src[src_pos + 1] == '*') {
            src_pos = src_pos + 2;
            while (src[src_pos] && !(src[src_pos] == '*' && src[src_pos + 1] == '/')) {
                if (src[src_pos] == '\n') line = line + 1;
                src_pos = src_pos + 1;
            }
            if (src[src_pos]) src_pos = src_pos + 2;
        } else if (src[src_pos] == '#') {
            while (src[src_pos] && src[src_pos] != '\n') src_pos = src_pos + 1;
        } else {
            break;
        }
    }

    if (!src[src_pos]) { tk = TK_EOF; return 0; }

    c = src[src_pos];

    /* Number */
    if (is_digit(c)) {
        num = 0;
        if (c == '0' && (src[src_pos + 1] == 'x' || src[src_pos + 1] == 'X')) {
            src_pos = src_pos + 2;
            while (is_digit(src[src_pos]) || (src[src_pos] >= 'a' && src[src_pos] <= 'f') || (src[src_pos] >= 'A' && src[src_pos] <= 'F')) {
                c = src[src_pos];
                if (is_digit(c)) num = num * 16 + c - '0';
                else if (c >= 'a') num = num * 16 + c - 'a' + 10;
                else num = num * 16 + c - 'A' + 10;
                src_pos = src_pos + 1;
            }
        } else {
            while (is_digit(src[src_pos])) {
                num = num * 10 + src[src_pos] - '0';
                src_pos = src_pos + 1;
            }
        }
        tk = TK_NUM;
        tk_val = num;
        return 0;
    }

    /* Identifier or keyword */
    if (is_alpha(c)) {
        tk_str = src + src_pos;
        tk_len = 0;
        while (is_alnum(src[src_pos])) {
            src_pos = src_pos + 1;
            tk_len = tk_len + 1;
        }

        /* Check keywords */
        if (str_eq(tk_str, tk_len, "int", 3)) { tk = TK_INT; return 0; }
        if (str_eq(tk_str, tk_len, "char", 4)) { tk = TK_CHAR; return 0; }
        if (str_eq(tk_str, tk_len, "enum", 4)) { tk = TK_ENUM; return 0; }
        if (str_eq(tk_str, tk_len, "if", 2)) { tk = TK_IF; return 0; }
        if (str_eq(tk_str, tk_len, "else", 4)) { tk = TK_ELSE; return 0; }
        if (str_eq(tk_str, tk_len, "while", 5)) { tk = TK_WHILE; return 0; }
        if (str_eq(tk_str, tk_len, "return", 6)) { tk = TK_RET; return 0; }
        if (str_eq(tk_str, tk_len, "sizeof", 6)) { tk = TK_SIZEOF; return 0; }

        tk = TK_ID;
        return 0;
    }

    /* Character literal */
    if (c == '\'') {
        src_pos = src_pos + 1;
        tk_val = src[src_pos];
        if (src[src_pos] == '\\') {
            src_pos = src_pos + 1;
            c = src[src_pos];
            if (c == 'n') tk_val = 10;
            else if (c == 't') tk_val = 9;
            else if (c == '0') tk_val = 0;
            else tk_val = c;
        }
        src_pos = src_pos + 1;
        src_pos = src_pos + 1; /* skip closing quote */
        tk = TK_NUM;
        return 0;
    }

    /* String literal */
    if (c == '"') {
        src_pos = src_pos + 1;
        str_start = data_pos;
        while (src[src_pos] && src[src_pos] != '"') {
            c = src[src_pos];
            if (c == '\\') {
                src_pos = src_pos + 1;
                c = src[src_pos];
                if (c == 'n') c = 10;
                else if (c == 't') c = 9;
                else if (c == '0') c = 0;
            }
            data[data_pos] = c;
            data_pos = data_pos + 1;
            src_pos = src_pos + 1;
        }
        data[data_pos] = 0;
        data_pos = data_pos + 1;
        while (data_pos % 8 != 0) { data[data_pos] = 0; data_pos = data_pos + 1; }
        src_pos = src_pos + 1; /* skip closing quote */
        tk = TK_STR;
        tk_val = str_start;
        return 0;
    }

    src_pos = src_pos + 1;

    /* Operators */
    if (c == '+') {
        if (src[src_pos] == '+') { src_pos = src_pos + 1; tk = TK_INC; return 0; }
        tk = TK_ADD; return 0;
    }
    if (c == '-') {
        if (src[src_pos] == '-') { src_pos = src_pos + 1; tk = TK_DEC; return 0; }
        tk = TK_SUB; return 0;
    }
    if (c == '*') { tk = TK_MUL; return 0; }
    if (c == '/') { tk = TK_DIV; return 0; }
    if (c == '%') { tk = TK_MOD; return 0; }

    if (c == '=') {
        if (src[src_pos] == '=') { src_pos = src_pos + 1; tk = TK_EQ; return 0; }
        tk = TK_ASSIGN; return 0;
    }
    if (c == '!') {
        if (src[src_pos] == '=') { src_pos = src_pos + 1; tk = TK_NE; return 0; }
        tk = TK_NUM; tk_val = 0; return 0;
    }
    if (c == '<') {
        if (src[src_pos] == '=') { src_pos = src_pos + 1; tk = TK_LE; return 0; }
        if (src[src_pos] == '<') { src_pos = src_pos + 1; tk = TK_SHL; return 0; }
        tk = TK_LT; return 0;
    }
    if (c == '>') {
        if (src[src_pos] == '=') { src_pos = src_pos + 1; tk = TK_GE; return 0; }
        if (src[src_pos] == '>') { src_pos = src_pos + 1; tk = TK_SHR; return 0; }
        tk = TK_GT; return 0;
    }

    if (c == '&') {
        if (src[src_pos] == '&') { src_pos = src_pos + 1; tk = TK_AND; return 0; }
        tk = TK_AND + 100; return 0;  /* bitwise AND */
    }
    if (c == '|') {
        if (src[src_pos] == '|') { src_pos = src_pos + 1; tk = TK_OR; return 0; }
        tk = TK_OR + 100; return 0;   /* bitwise OR */
    }
    if (c == '^') { tk = TK_OR + 101; return 0; }  /* XOR */

    if (c == '(') { tk = '('; return 0; }
    if (c == ')') { tk = ')'; return 0; }
    if (c == '{') { tk = '{'; return 0; }
    if (c == '}') { tk = '}'; return 0; }
    if (c == '[') { tk = TK_BRAK; return 0; }
    if (c == ']') { tk = ']'; return 0; }
    if (c == ';') { tk = ';'; return 0; }
    if (c == ',') { tk = ','; return 0; }
    if (c == ':') { tk = ':'; return 0; }
    if (c == '?') { tk = '?'; return 0; }

    tk = c;
    return 0;
}

/* ============ Symbol Table ============ */

int find_sym(char *name, int len) {
    int i;
    i = 0;
    while (i < sym_count) {
        if (str_eq(sym_names[i], strlen(sym_names[i]), name, len)) return i;
        i = i + 1;
    }
    return -1;
}

int add_sym(char *name, int len, int sclass, int stype, int sval) {
    int i; char *n;
    i = sym_count;
    n = malloc(len + 1);
    memcpy(n, name, len);
    n[len] = 0;
    sym_names[i] = n;
    sym_class[i] = sclass;
    sym_type[i] = stype;
    sym_val[i] = sval;
    sym_hclass[i] = 0;
    sym_count = sym_count + 1;
    return i;
}

/* ============ Code Generation ============ */

int emit(int op, int imm) {
    code[code_pos] = op | (imm << 8);
    code_pos = code_pos + 1;
    return 0;
}

int current_addr() {
    return code_pos * 8;
}

int patch(int addr, int target) {
    int idx; int op;
    idx = addr / 8;
    op = code[idx] & 0xFF;
    code[idx] = op | (target << 8);
    return 0;
}

/* ============ Parser Forward Declarations ============ */
int parse_expr(int level);
int parse_stmt();

/* ============ Expression Parser ============ */

int parse_expr(int level) {
    int id; int sym_idx; int argc; int addr;
    int t; int saved_type; int bz_addr; int jmp_addr;

    if (tk == TK_NUM) {
        emit(OP_IMM, tk_val);
        next_token();
        expr_type = TY_INT;
    }
    else if (tk == TK_STR) {
        emit(OP_IMM, DATA_BASE + tk_val);
        next_token();
        expr_type = TY_PTR + TY_CHAR;
    }
    else if (tk == TK_SIZEOF) {
        next_token();
        next_token(); /* ( */
        t = TY_INT;
        if (tk == TK_INT) { next_token(); t = TY_INT; }
        else if (tk == TK_CHAR) { next_token(); t = TY_CHAR; }
        while (tk == TK_MUL) { next_token(); t = t + TY_PTR; }
        next_token(); /* ) */
        emit(OP_IMM, (t >= TY_PTR || t == TY_INT) ? 8 : 1);
        expr_type = TY_INT;
    }
    else if (tk == TK_ID) {
        sym_idx = find_sym(tk_str, tk_len);
        if (sym_idx < 0) {
            /* Add as forward reference */
            sym_idx = add_sym(tk_str, tk_len, 0, TY_INT, 0);
        }
        next_token();

        if (tk == '(') {
            /* Function call */
            next_token();
            argc = 0;
            while (tk != ')') {
                parse_expr(TK_ASSIGN);
                emit(OP_PSH, 0);
                argc = argc + 1;
                if (tk == ',') next_token();
            }
            next_token(); /* ) */

            if (sym_class[sym_idx] == 3) {
                /* System call */
                emit(sym_val[sym_idx], 0);
            } else {
                /* Function call */
                emit(OP_JSR, sym_val[sym_idx]);
            }
            if (argc) emit(OP_ADJ, argc * 8);
            expr_type = sym_type[sym_idx];
        }
        else if (sym_class[sym_idx] == 1) {
            /* Enum constant */
            emit(OP_IMM, sym_val[sym_idx]);
            expr_type = TY_INT;
        }
        else if (sym_class[sym_idx] == 5) {
            /* Local variable */
            emit(OP_LEA, sym_val[sym_idx]);
            expr_type = sym_type[sym_idx];
            if (expr_type == TY_CHAR) emit(OP_LC, 0);
            else emit(OP_LI, 0);
        }
        else if (sym_class[sym_idx] == 4) {
            /* Global variable */
            emit(OP_IMM, sym_val[sym_idx]);
            expr_type = sym_type[sym_idx];
            if (expr_type == TY_CHAR) emit(OP_LC, 0);
            else emit(OP_LI, 0);
        }
    }
    else if (tk == '(') {
        next_token();
        if (tk == TK_INT || tk == TK_CHAR) {
            /* Cast */
            t = (tk == TK_INT) ? TY_INT : TY_CHAR;
            next_token();
            while (tk == TK_MUL) { next_token(); t = t + TY_PTR; }
            next_token(); /* ) */
            parse_expr(TK_INC);
            expr_type = t;
        } else {
            parse_expr(TK_ASSIGN);
            next_token(); /* ) */
        }
    }
    else if (tk == TK_MUL) {
        /* Dereference */
        next_token();
        parse_expr(TK_INC);
        if (expr_type >= TY_PTR) expr_type = expr_type - TY_PTR;
        if (expr_type == TY_CHAR) emit(OP_LC, 0);
        else emit(OP_LI, 0);
    }
    else if (tk == TK_AND + 100) {
        /* Address-of */
        next_token();
        parse_expr(TK_INC);
        if ((code[code_pos - 1] & 0xFF) == OP_LI || (code[code_pos - 1] & 0xFF) == OP_LC) {
            code_pos = code_pos - 1;
        }
        expr_type = expr_type + TY_PTR;
    }
    else if (tk == TK_SUB) {
        /* Unary minus */
        next_token();
        emit(OP_IMM, -1);
        emit(OP_PSH, 0);
        parse_expr(TK_INC);
        emit(OP_MUL, 0);
        expr_type = TY_INT;
    }
    else if (tk == TK_INC || tk == TK_DEC) {
        /* Pre-increment/decrement */
        t = tk;
        next_token();
        parse_expr(TK_INC);
        if ((code[code_pos - 1] & 0xFF) == OP_LI || (code[code_pos - 1] & 0xFF) == OP_LC) {
            code[code_pos - 1] = OP_PSH;
            if (expr_type == TY_CHAR) emit(OP_LC, 0);
            else emit(OP_LI, 0);
        }
        emit(OP_PSH, 0);
        emit(OP_IMM, (expr_type >= TY_PTR) ? 8 : 1);
        if (t == TK_INC) emit(OP_ADD, 0);
        else emit(OP_SUB, 0);
        if (expr_type == TY_CHAR) emit(OP_SC, 0);
        else emit(OP_SI, 0);
    }

    /* Binary operators */
    while (tk >= level) {
        saved_type = expr_type;

        if (tk == TK_ASSIGN) {
            next_token();
            if ((code[code_pos - 1] & 0xFF) == OP_LI || (code[code_pos - 1] & 0xFF) == OP_LC) {
                code[code_pos - 1] = OP_PSH;
            }
            parse_expr(TK_ASSIGN);
            if (saved_type == TY_CHAR) emit(OP_SC, 0);
            else emit(OP_SI, 0);
        }
        else if (tk == '?') {
            next_token();
            bz_addr = current_addr();
            emit(OP_BZ, 0);
            parse_expr(TK_ASSIGN);
            next_token(); /* : */
            jmp_addr = current_addr();
            emit(OP_JMP, 0);
            patch(bz_addr, current_addr());
            parse_expr(TK_ASSIGN);
            patch(jmp_addr, current_addr());
        }
        else if (tk == TK_OR) {
            next_token();
            bz_addr = current_addr();
            emit(OP_BNZ, 0);
            parse_expr(TK_AND);
            patch(bz_addr, current_addr());
            expr_type = TY_INT;
        }
        else if (tk == TK_AND) {
            next_token();
            bz_addr = current_addr();
            emit(OP_BZ, 0);
            parse_expr(TK_OR + 100);
            patch(bz_addr, current_addr());
            expr_type = TY_INT;
        }
        else if (tk == TK_OR + 100) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_OR + 101);
            emit(OP_OR, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_OR + 101) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_AND + 100);
            emit(OP_XOR, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_AND + 100) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_EQ);
            emit(OP_AND, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_EQ) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_LT);
            emit(OP_EQ, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_NE) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_LT);
            emit(OP_NE, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_LT) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_SHL);
            emit(OP_LT, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_GT) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_SHL);
            emit(OP_GT, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_LE) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_SHL);
            emit(OP_LE, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_GE) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_SHL);
            emit(OP_GE, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_SHL) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_ADD);
            emit(OP_SHL, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_SHR) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_ADD);
            emit(OP_SHR, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_ADD) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_MUL);
            if (saved_type >= TY_PTR) {
                emit(OP_PSH, 0);
                emit(OP_IMM, 8);
                emit(OP_MUL, 0);
            }
            emit(OP_ADD, 0);
            expr_type = saved_type;
        }
        else if (tk == TK_SUB) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_MUL);
            if (saved_type >= TY_PTR) {
                emit(OP_PSH, 0);
                emit(OP_IMM, 8);
                emit(OP_MUL, 0);
            }
            emit(OP_SUB, 0);
            expr_type = saved_type;
        }
        else if (tk == TK_MUL) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_INC);
            emit(OP_MUL, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_DIV) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_INC);
            emit(OP_DIV, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_MOD) {
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_INC);
            emit(OP_MOD, 0);
            expr_type = TY_INT;
        }
        else if (tk == TK_INC || tk == TK_DEC) {
            /* Post-increment/decrement */
            if ((code[code_pos - 1] & 0xFF) == OP_LI || (code[code_pos - 1] & 0xFF) == OP_LC) {
                code[code_pos - 1] = OP_PSH;
                if (saved_type == TY_CHAR) emit(OP_LC, 0);
                else emit(OP_LI, 0);
            }
            emit(OP_PSH, 0);
            emit(OP_IMM, (saved_type >= TY_PTR) ? 8 : 1);
            if (tk == TK_INC) emit(OP_ADD, 0);
            else emit(OP_SUB, 0);
            if (saved_type == TY_CHAR) emit(OP_SC, 0);
            else emit(OP_SI, 0);
            emit(OP_PSH, 0);
            emit(OP_IMM, (saved_type >= TY_PTR) ? 8 : 1);
            if (tk == TK_INC) emit(OP_SUB, 0);
            else emit(OP_ADD, 0);
            next_token();
        }
        else if (tk == TK_BRAK) {
            /* Array subscript */
            next_token();
            emit(OP_PSH, 0);
            parse_expr(TK_ASSIGN);
            next_token(); /* ] */
            if (saved_type >= TY_PTR) {
                emit(OP_PSH, 0);
                emit(OP_IMM, 8);
                emit(OP_MUL, 0);
            }
            emit(OP_ADD, 0);
            if (saved_type >= TY_PTR) expr_type = saved_type - TY_PTR;
            else expr_type = saved_type;
            if (expr_type == TY_CHAR) emit(OP_LC, 0);
            else emit(OP_LI, 0);
        }
        else {
            break;
        }
    }

    return 0;
}

/* ============ Statement Parser ============ */

int parse_stmt() {
    int bz_addr; int jmp_addr; int loop_addr;

    if (tk == TK_IF) {
        next_token();
        next_token(); /* ( */
        parse_expr(TK_ASSIGN);
        next_token(); /* ) */
        bz_addr = current_addr();
        emit(OP_BZ, 0);
        parse_stmt();
        if (tk == TK_ELSE) {
            next_token();
            jmp_addr = current_addr();
            emit(OP_JMP, 0);
            patch(bz_addr, current_addr());
            parse_stmt();
            patch(jmp_addr, current_addr());
        } else {
            patch(bz_addr, current_addr());
        }
    }
    else if (tk == TK_WHILE) {
        next_token();
        loop_addr = current_addr();
        next_token(); /* ( */
        parse_expr(TK_ASSIGN);
        next_token(); /* ) */
        bz_addr = current_addr();
        emit(OP_BZ, 0);
        parse_stmt();
        emit(OP_JMP, loop_addr);
        patch(bz_addr, current_addr());
    }
    else if (tk == TK_RET) {
        next_token();
        if (tk != ';') parse_expr(TK_ASSIGN);
        next_token(); /* ; */
        emit(OP_LEV, 0);
    }
    else if (tk == '{') {
        next_token();
        while (tk != '}') parse_stmt();
        next_token();
    }
    else if (tk == ';') {
        next_token();
    }
    else {
        parse_expr(TK_ASSIGN);
        next_token(); /* ; */
    }

    return 0;
}

/* ============ Function Parser ============ */

int parse_function(int sym_idx, int ret_type) {
    int ent_addr; int param_count; int ptype; int pname_idx;
    char *pname; int plen;

    sym_class[sym_idx] = 2;  /* Fun */
    sym_type[sym_idx] = ret_type;
    sym_val[sym_idx] = current_addr();

    next_token(); /* ( */
    param_count = 0;

    while (tk != ')') {
        ptype = TY_INT;
        if (tk == TK_INT) { next_token(); ptype = TY_INT; }
        else if (tk == TK_CHAR) { next_token(); ptype = TY_CHAR; }
        while (tk == TK_MUL) { next_token(); ptype = ptype + TY_PTR; }

        pname = tk_str;
        plen = tk_len;
        next_token();

        pname_idx = find_sym(pname, plen);
        if (pname_idx >= 0) {
            sym_hclass[pname_idx] = sym_class[pname_idx];
            sym_htype[pname_idx] = sym_type[pname_idx];
            sym_hval[pname_idx] = sym_val[pname_idx];
        } else {
            pname_idx = add_sym(pname, plen, 5, ptype, param_count);
        }
        sym_class[pname_idx] = 5;  /* Loc */
        sym_type[pname_idx] = ptype;
        sym_val[pname_idx] = param_count;
        param_count = param_count + 1;

        if (tk == ',') next_token();
    }
    next_token(); /* ) */
    next_token(); /* { */

    ent_addr = current_addr();
    emit(OP_ENT, 0);

    /* Fix param offsets */
    {
        int i;
        i = 0;
        while (i < sym_count) {
            if (sym_class[i] == 5 && sym_val[i] >= 0 && sym_val[i] < param_count) {
                sym_val[i] = 16 + (param_count - 1 - sym_val[i]) * 8;
            }
            i = i + 1;
        }
    }

    /* Parse local variables */
    local_offset = 0;
    while (tk == TK_INT || tk == TK_CHAR) {
        int ltype; char *lname; int llen; int lidx;
        ltype = (tk == TK_INT) ? TY_INT : TY_CHAR;
        next_token();
        while (tk == TK_MUL) { next_token(); ltype = ltype + TY_PTR; }

        while (1) {
            lname = tk_str;
            llen = tk_len;
            next_token();

            lidx = find_sym(lname, llen);
            if (lidx >= 0) {
                if (sym_hclass[lidx] == 0) {
                    sym_hclass[lidx] = sym_class[lidx];
                    sym_htype[lidx] = sym_type[lidx];
                    sym_hval[lidx] = sym_val[lidx];
                }
            } else {
                lidx = add_sym(lname, llen, 5, ltype, 0);
            }

            local_offset = local_offset + 8;
            sym_class[lidx] = 5;
            sym_type[lidx] = ltype;
            sym_val[lidx] = 0 - local_offset;

            if (tk == ',') next_token();
            else break;
        }
        next_token(); /* ; */
    }

    patch(ent_addr, local_offset);

    /* Parse body */
    while (tk != '}') parse_stmt();
    next_token();

    emit(OP_LEV, 0);

    /* Restore hidden symbols */
    {
        int i;
        i = 0;
        while (i < sym_count) {
            if (sym_hclass[i] != 0) {
                sym_class[i] = sym_hclass[i];
                sym_type[i] = sym_htype[i];
                sym_val[i] = sym_hval[i];
                sym_hclass[i] = 0;
            }
            i = i + 1;
        }
    }

    return 0;
}

/* ============ Global Declaration Parser ============ */

int parse_global() {
    int base_type; char *name; int len; int sym_idx;

    base_type = TY_INT;
    if (tk == TK_INT) { next_token(); base_type = TY_INT; }
    else if (tk == TK_CHAR) { next_token(); base_type = TY_CHAR; }
    else if (tk == TK_ENUM) {
        next_token();
        if (tk == TK_ID) next_token();
        next_token(); /* { */
        {
            int val; char *ename; int elen;
            val = 0;
            while (tk != '}') {
                ename = tk_str;
                elen = tk_len;
                next_token();
                if (tk == TK_ASSIGN) {
                    next_token();
                    val = tk_val;
                    next_token();
                }
                add_sym(ename, elen, 1, TY_INT, val);
                val = val + 1;
                if (tk == ',') next_token();
            }
        }
        next_token(); /* } */
        if (tk == ';') next_token();
        return 0;
    }

    while (tk == TK_MUL) { next_token(); base_type = base_type + TY_PTR; }

    name = tk_str;
    len = tk_len;
    next_token();

    sym_idx = find_sym(name, len);
    if (sym_idx < 0) {
        sym_idx = add_sym(name, len, 0, base_type, 0);
    }

    if (tk == '(') {
        parse_function(sym_idx, base_type);
    } else {
        sym_class[sym_idx] = 4;  /* Glo */
        sym_type[sym_idx] = base_type;
        sym_val[sym_idx] = DATA_BASE + data_pos;
        {
            int i;
            i = 0;
            while (i < 8) { data[data_pos] = 0; data_pos = data_pos + 1; i = i + 1; }
        }
        next_token(); /* ; */
    }

    return 0;
}

/* ============ Compiler Entry Point ============ */

int compile(char *source) {
    int main_idx;

    /* Initialize */
    src = source;
    src_pos = 0;
    line = 1;
    code_pos = 0;
    data_pos = 0;
    sym_count = 0;
    local_offset = 0;

    /* Add built-in functions */
    add_sym("exit", 4, 3, TY_INT, OP_EXIT);
    add_sym("getchar", 7, 3, TY_INT, OP_GETCHAR);
    add_sym("putchar", 7, 3, TY_INT, OP_PUTCHAR);

    /* Initial jump to main */
    emit(OP_JSR, 0);
    emit(OP_EXIT, 0);

    /* Parse program */
    next_token();
    while (tk != TK_EOF) {
        parse_global();
    }

    /* Patch jump to main */
    main_idx = find_sym("main", 4);
    if (main_idx >= 0) {
        code[0] = OP_JSR | (sym_val[main_idx] << 8);
    }

    return 0;
}

/* ============ VM Execution ============ */

int vm_run(int max_steps) {
    int steps; int instr_idx; int op; int imm;
    int a; int c;

    steps = 0;
    while (steps < max_steps) {
        instr_idx = vm_pc / 8;
        if (instr_idx >= code_pos || vm_halted) break;

        op = code[instr_idx] & 0xFF;
        imm = code[instr_idx] >> 8;
        vm_pc = vm_pc + 8;

        if (op == OP_GETCHAR) {
            if (stdin_pos >= stdin_len) {
                vm_ax = -1;
            } else {
                vm_ax = stdin_buf[stdin_pos] & 255;
                stdin_pos = stdin_pos + 1;
            }
        }
        else if (op == OP_PUTCHAR) {
            c = vm_mem[vm_sp / 8];
            stdout_buf[stdout_pos] = c & 255;
            stdout_pos = stdout_pos + 1;
            vm_ax = c;
        }
        else if (op == OP_LEA) { vm_ax = vm_bp + imm; }
        else if (op == OP_IMM) { vm_ax = imm; }
        else if (op == OP_JMP) { vm_pc = imm; }
        else if (op == OP_JSR) {
            vm_sp = vm_sp - 8;
            vm_mem[vm_sp / 8] = vm_pc;
            vm_pc = imm;
        }
        else if (op == OP_BZ) { if (vm_ax == 0) vm_pc = imm; }
        else if (op == OP_BNZ) { if (vm_ax != 0) vm_pc = imm; }
        else if (op == OP_ENT) {
            vm_sp = vm_sp - 8;
            vm_mem[vm_sp / 8] = vm_bp;
            vm_bp = vm_sp;
            vm_sp = vm_sp - imm;
        }
        else if (op == OP_ADJ) { vm_sp = vm_sp + imm; }
        else if (op == OP_LEV) {
            vm_sp = vm_bp;
            vm_bp = vm_mem[vm_sp / 8];
            vm_sp = vm_sp + 8;
            vm_pc = vm_mem[vm_sp / 8];
            vm_sp = vm_sp + 8;
        }
        else if (op == OP_LI) { vm_ax = vm_mem[vm_ax / 8]; }
        else if (op == OP_LC) { vm_ax = data[vm_ax - DATA_BASE] & 255; }
        else if (op == OP_SI) {
            a = vm_mem[vm_sp / 8];
            vm_sp = vm_sp + 8;
            vm_mem[a / 8] = vm_ax;
        }
        else if (op == OP_SC) {
            a = vm_mem[vm_sp / 8];
            vm_sp = vm_sp + 8;
            data[a - DATA_BASE] = vm_ax & 255;
        }
        else if (op == OP_PSH) {
            vm_sp = vm_sp - 8;
            vm_mem[vm_sp / 8] = vm_ax;
        }
        else if (op == OP_OR) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = a | vm_ax;
        }
        else if (op == OP_XOR) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = a ^ vm_ax;
        }
        else if (op == OP_AND) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = a & vm_ax;
        }
        else if (op == OP_EQ) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = (a == vm_ax) ? 1 : 0;
        }
        else if (op == OP_NE) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = (a != vm_ax) ? 1 : 0;
        }
        else if (op == OP_LT) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = (a < vm_ax) ? 1 : 0;
        }
        else if (op == OP_GT) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = (a > vm_ax) ? 1 : 0;
        }
        else if (op == OP_LE) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = (a <= vm_ax) ? 1 : 0;
        }
        else if (op == OP_GE) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = (a >= vm_ax) ? 1 : 0;
        }
        else if (op == OP_SHL) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = a << vm_ax;
        }
        else if (op == OP_SHR) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = a >> vm_ax;
        }
        else if (op == OP_ADD) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = neural_add(a, vm_ax);
        }
        else if (op == OP_SUB) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = a - vm_ax;
        }
        else if (op == OP_MUL) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = neural_mul(a, vm_ax);
        }
        else if (op == OP_DIV) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = neural_div(a, vm_ax);
        }
        else if (op == OP_MOD) {
            a = vm_mem[vm_sp / 8]; vm_sp = vm_sp + 8;
            vm_ax = a - neural_mul(neural_div(a, vm_ax), vm_ax);
        }
        else if (op == OP_EXIT) {
            vm_halted = 1;
            break;
        }

        steps = steps + 1;
    }

    return vm_ax;
}

/* ============ Main ============ */

int main(int argc, char **argv) {
    int fd; int src_len; int exit_code;
    char *source; int i;
    int expr_mode; int code_mode;

    init_constants();
    init_neural();

    /* Allocate memory */
    code = malloc(POOL_SIZE * 4);
    data = malloc(POOL_SIZE);
    sym_names = malloc(MAX_SYMS * 8);
    sym_class = malloc(MAX_SYMS * 4);
    sym_type = malloc(MAX_SYMS * 4);
    sym_val = malloc(MAX_SYMS * 4);
    sym_hclass = malloc(MAX_SYMS * 4);
    sym_htype = malloc(MAX_SYMS * 4);
    sym_hval = malloc(MAX_SYMS * 4);
    vm_mem = malloc(POOL_SIZE * 4);
    stdin_buf = malloc(POOL_SIZE);
    stdout_buf = malloc(POOL_SIZE);

    /* Initialize symbol table hidden values */
    i = 0;
    while (i < MAX_SYMS) { sym_hclass[i] = 0; i = i + 1; }

    /* Parse arguments */
    expr_mode = 0;
    code_mode = 0;
    source = 0;

    i = 1;
    while (i < argc) {
        if (argv[i][0] == '-' && argv[i][1] == 'e') {
            expr_mode = 1;
            i = i + 1;
            if (i < argc) {
                /* Build: int main() { return <expr>; } */
                source = malloc(strlen(argv[i]) + 32);
                strcpy(source, "int main(){return ");
                strcat(source, argv[i]);
                strcat(source, ";}");
            }
        }
        else if (argv[i][0] == '-' && argv[i][1] == 'c') {
            code_mode = 1;
            i = i + 1;
            if (i < argc) {
                source = argv[i];
            }
        }
        else {
            /* File argument */
            fd = open(argv[i], 0);
            if (fd >= 0) {
                source = malloc(POOL_SIZE);
                src_len = read(fd, source, POOL_SIZE - 1);
                source[src_len] = 0;
                close(fd);
            }
        }
        i = i + 1;
    }

    if (!source) {
        printf("Usage: %s [-e expr | -c code | file.c]\n", argv[0]);
        return 1;
    }

    /* Read stdin */
    stdin_pos = 0;
    stdin_len = 0;
    /* Note: In a real implementation, would read from actual stdin */

    /* Compile */
    compile(source);

    /* Initialize VM */
    vm_sp = POOL_SIZE * 4;
    vm_bp = vm_sp;
    vm_ax = 0;
    vm_pc = 0;
    vm_halted = 0;
    stdout_pos = 0;

    /* Run */
    exit_code = vm_run(1000000);

    /* Output stdout */
    stdout_buf[stdout_pos] = 0;
    if (stdout_pos > 0) {
        printf("%s", stdout_buf);
    }

    /* Cleanup */
    free(code);
    free(data);
    free(vm_mem);
    free(stdin_buf);
    free(stdout_buf);
    free(exp_tbl);

    return exit_code & 255;
}
