#!/usr/bin/env python3
"""
Bundle Executable Generator

Creates a standalone executable by combining:
1. ONNX C runtime (the inference engine)
2. Neural network weights (baked/hardcoded, NOT trained)
3. Target C program (compiled to bytecode)

The output is a single C file that can be compiled with gcc
to produce a standalone executable that runs the target program
using the neural VM.

Usage:
    python bundle_executable.py \
        --runtime onnx_runner_c4.c \
        --weights model_weights.bin \
        --program hello.c \
        --output bundled.c

    # Then compile:
    gcc -O2 -o bundled bundled.c
"""

import argparse
import struct
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def load_weights(weights_path):
    """Load neural network weights from binary file."""
    with open(weights_path, 'rb') as f:
        data = f.read()
    return data


def compile_program(source_path):
    """Compile C source to bytecode."""
    from src.compiler import compile_c

    with open(source_path, 'r') as f:
        source = f.read()

    bytecode, data = compile_c(source)

    # Convert bytecode to bytes (handle negative immediates)
    bytecode_bytes = b''
    for instr in bytecode:
        # Convert to unsigned 64-bit (handle negative values)
        if instr < 0:
            instr = instr & 0xFFFFFFFFFFFFFFFF
        bytecode_bytes += struct.pack('<Q', instr)  # 64-bit little-endian

    return bytecode_bytes, data or b''


def generate_c_array(name, data, items_per_line=16):
    """Generate C array declaration from binary data."""
    lines = [f"static const unsigned char {name}[] = {{"]

    for i in range(0, len(data), items_per_line):
        chunk = data[i:i+items_per_line]
        hex_vals = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f"    {hex_vals},")

    lines.append("};")
    lines.append(f"static const int {name}_size = {len(data)};")

    return '\n'.join(lines)


def generate_bundled_c(runtime_path, weights_data, bytecode_data, data_section,
                       program_name="program"):
    """Generate the bundled C source file."""

    # Read the runtime template
    with open(runtime_path, 'r') as f:
        runtime_source = f.read()

    # Generate embedded data arrays
    bytecode_array = generate_c_array("bundled_bytecode", bytecode_data)
    data_array = generate_c_array("bundled_data", data_section) if data_section else \
                 "static const unsigned char bundled_data[] = {};\nstatic const int bundled_data_size = 0;"
    weights_array = generate_c_array("bundled_weights", weights_data) if weights_data else \
                    "static const unsigned char bundled_weights[] = {};\nstatic const int bundled_weights_size = 0;"

    # Create the bundled source
    bundled_source = f'''/*
 * Bundled Executable: {program_name}
 *
 * Generated by bundle_executable.py
 *
 * This file contains:
 *   - Neural VM runtime
 *   - Baked weights (hardcoded, not trained)
 *   - Compiled bytecode
 *
 * Compile with: gcc -O2 -o {program_name} {program_name}.c
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ============ Embedded Data ============ */

{bytecode_array}

{data_array}

{weights_array}

/* ============ Neural VM Runtime ============ */

{runtime_source}

/* ============ Bundled Program Loader ============ */

int load_bundled_program() {{
    /* Load bytecode */
    int num_instrs;
    int i;
    unsigned long long *code;

    num_instrs = bundled_bytecode_size / 8;
    code = (unsigned long long *)bundled_bytecode;

    /* Copy to VM's code array */
    for (i = 0; i < num_instrs; i++) {{
        /* Assuming vm_code is the global code array */
        /* This depends on the runtime implementation */
    }}

    /* Load data section */
    if (bundled_data_size > 0) {{
        /* Copy to VM's data segment */
    }}

    /* Load weights */
    if (bundled_weights_size > 0) {{
        /* Initialize neural network weights */
    }}

    return num_instrs;
}}

/* ============ Main Entry Point ============ */

int bundled_main(int argc, char **argv) {{
    /* Initialize VM */
    /* load_bundled_program(); */

    /* Run the program */
    /* return vm_run(); */

    printf("Bundled executable ready.\\n");
    printf("Bytecode size: %d bytes (%d instructions)\\n",
           bundled_bytecode_size, bundled_bytecode_size / 8);
    printf("Data section: %d bytes\\n", bundled_data_size);
    printf("Weights: %d bytes\\n", bundled_weights_size);

    return 0;
}}

#ifndef BUNDLED_AS_LIBRARY
int main(int argc, char **argv) {{
    return bundled_main(argc, argv);
}}
#endif
'''

    return bundled_source


def create_minimal_bundled(bytecode_data, data_section, program_name="program"):
    """Create a minimal bundled C file without neural runtime."""

    bytecode_array = generate_c_array("bundled_bytecode", bytecode_data)
    data_array = generate_c_array("bundled_data", data_section) if data_section else \
                 "static const unsigned char bundled_data[] = {};\nstatic const int bundled_data_size = 0;"

    bundled_source = f'''/*
 * Bundled C4 VM Executable: {program_name}
 *
 * Generated by bundle_executable.py
 * This contains the compiled bytecode embedded in a minimal VM.
 *
 * Compile with: gcc -O2 -o {program_name} {program_name}.c
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ============ Embedded Bytecode ============ */

{bytecode_array}

{data_array}

/* ============ Minimal C4 VM ============ */

typedef long long int64;
typedef unsigned char byte;

/* Memory layout:
 *   0x00000 - 0x0FFFF: Code segment (not directly accessed)
 *   0x10000 - 0x4FFFF: Data segment (strings, globals)
 *   0x50000 - 0x9FFFF: Stack (grows down)
 */
#define DATA_BASE   0x10000
#define STACK_BASE  0x90000
#define STACK_SIZE  0x40000

/* VM State */
static int64 *code;      /* Code segment */
static byte *memory;     /* Unified memory */
static int64 pc;         /* Program counter */
static int64 sp;         /* Stack pointer */
static int64 bp;         /* Base pointer */
static int64 ax;         /* Accumulator */
static int code_size;

/* Opcodes (matching compiler output) */
enum {{
    LEA, IMM, JMP, JSR, BZ, BNZ, ENT, ADJ, LEV, LI, LC, SI, SC, PSH,
    OR, XOR, AND, EQ, NE, LT, GT, LE, GE, SHL, SHR, ADD, SUB, MUL, DIV, MOD,
    OPEN, READ, CLOS, PRTF, MALC, FREE, MSET, MCMP, EXIT
}};

/* Extended opcodes from compiler */
#define GETC_EXT 64
#define PUTC_EXT 65

/* Memory access helpers */
static inline byte mem_read_byte(int64 addr) {{
    return memory[addr];
}}

static inline int64 mem_read_int(int64 addr) {{
    return *(int64 *)(memory + addr);
}}

static inline void mem_write_byte(int64 addr, byte val) {{
    memory[addr] = val;
}}

static inline void mem_write_int(int64 addr, int64 val) {{
    *(int64 *)(memory + addr) = val;
}}

/* Initialize VM */
void vm_init() {{
    int num_instrs;

    num_instrs = bundled_bytecode_size / 8;
    code_size = num_instrs;

    code = (int64 *)malloc(num_instrs * sizeof(int64));
    memcpy(code, bundled_bytecode, bundled_bytecode_size);

    /* Allocate unified memory */
    memory = (byte *)calloc(1, STACK_BASE + STACK_SIZE);

    /* Copy data to DATA_BASE */
    if (bundled_data_size > 0) {{
        memcpy(memory + DATA_BASE, bundled_data, bundled_data_size);
    }}

    /* Initialize stack pointer */
    sp = STACK_BASE + STACK_SIZE - 8;
    bp = sp;

    pc = 0;
    ax = 0;
}}

/* Run VM */
int vm_run() {{
    int64 op, imm;
    int64 a;
    int cycle;

    cycle = 0;

    while (1) {{
        if (pc < 0 || pc >= code_size * 8) break;

        op = code[pc / 8] & 0xFF;
        imm = code[pc / 8] >> 8;
        /* Sign extend immediate */
        if (imm >= (1LL << 55)) imm -= (1LL << 56);
        pc = pc + 8;

        if (op == LEA) {{ ax = bp + imm; }}
        else if (op == IMM) {{ ax = imm; }}
        else if (op == JMP) {{ pc = imm; }}
        else if (op == JSR) {{ sp = sp - 8; mem_write_int(sp, pc); pc = imm; }}
        else if (op == BZ)  {{ if (ax == 0) pc = imm; }}
        else if (op == BNZ) {{ if (ax != 0) pc = imm; }}
        else if (op == ENT) {{ sp = sp - 8; mem_write_int(sp, bp); bp = sp; sp = sp - imm; }}
        else if (op == ADJ) {{ sp = sp + imm; }}
        else if (op == LEV) {{ sp = bp; bp = mem_read_int(sp); sp = sp + 8; pc = mem_read_int(sp); sp = sp + 8; }}
        else if (op == LI)  {{ ax = mem_read_int(ax); }}
        else if (op == LC)  {{ ax = mem_read_byte(ax); }}
        else if (op == SI)  {{ a = mem_read_int(sp); sp = sp + 8; mem_write_int(a, ax); }}
        else if (op == SC)  {{ a = mem_read_int(sp); sp = sp + 8; mem_write_byte(a, (byte)ax); }}
        else if (op == PSH) {{ sp = sp - 8; mem_write_int(sp, ax); }}
        else if (op == OR)  {{ ax = mem_read_int(sp) | ax; sp = sp + 8; }}
        else if (op == XOR) {{ ax = mem_read_int(sp) ^ ax; sp = sp + 8; }}
        else if (op == AND) {{ ax = mem_read_int(sp) & ax; sp = sp + 8; }}
        else if (op == EQ)  {{ ax = mem_read_int(sp) == ax; sp = sp + 8; }}
        else if (op == NE)  {{ ax = mem_read_int(sp) != ax; sp = sp + 8; }}
        else if (op == LT)  {{ ax = mem_read_int(sp) < ax; sp = sp + 8; }}
        else if (op == GT)  {{ ax = mem_read_int(sp) > ax; sp = sp + 8; }}
        else if (op == LE)  {{ ax = mem_read_int(sp) <= ax; sp = sp + 8; }}
        else if (op == GE)  {{ ax = mem_read_int(sp) >= ax; sp = sp + 8; }}
        else if (op == SHL) {{ ax = mem_read_int(sp) << ax; sp = sp + 8; }}
        else if (op == SHR) {{ ax = (int64)((unsigned long long)mem_read_int(sp) >> ax); sp = sp + 8; }}
        else if (op == ADD) {{ ax = mem_read_int(sp) + ax; sp = sp + 8; }}
        else if (op == SUB) {{ ax = mem_read_int(sp) - ax; sp = sp + 8; }}
        else if (op == MUL) {{ ax = mem_read_int(sp) * ax; sp = sp + 8; }}
        else if (op == DIV) {{ ax = mem_read_int(sp) / ax; sp = sp + 8; }}
        else if (op == MOD) {{ ax = mem_read_int(sp) % ax; sp = sp + 8; }}
        else if (op == EXIT) {{ return (int)mem_read_int(sp); }}
        else if (op == MALC) {{ ax = (int64)malloc((size_t)mem_read_int(sp)); sp = sp + 8; }}
        else if (op == FREE) {{ free((void *)mem_read_int(sp)); sp = sp + 8; }}
        /* Extended opcodes */
        else if (op == GETC_EXT) {{ ax = getchar(); }}
        else if (op == PUTC_EXT) {{ ax = (int)mem_read_int(sp); putchar((int)ax); }}
        else {{
            printf("Unknown opcode: %lld at pc=%lld\\n", op, pc - 8);
            return -1;
        }}

        cycle++;
        if (cycle > 100000000) {{
            printf("Cycle limit exceeded\\n");
            return -1;
        }}
    }}

    return (int)ax;
}}

/* Main */
int main(int argc, char **argv) {{
    vm_init();
    return vm_run();
}}
'''

    return bundled_source


def main():
    parser = argparse.ArgumentParser(description='Bundle ONNX C + weights + program into executable')
    parser.add_argument('--runtime', help='Path to ONNX C runtime (optional)')
    parser.add_argument('--weights', help='Path to weights binary (optional)')
    parser.add_argument('--program', required=True, help='Path to C source program')
    parser.add_argument('--output', required=True, help='Output C file path')
    parser.add_argument('--minimal', action='store_true', help='Use minimal VM (no neural)')

    args = parser.parse_args()

    print(f"Bundling executable:")
    print(f"  Program: {args.program}")
    print(f"  Output:  {args.output}")

    # Compile the program
    print(f"\nCompiling {args.program}...")
    bytecode_data, data_section = compile_program(args.program)
    print(f"  Bytecode: {len(bytecode_data)} bytes ({len(bytecode_data)//8} instructions)")
    print(f"  Data:     {len(data_section)} bytes")

    # Load weights if provided
    weights_data = b''
    if args.weights and os.path.exists(args.weights):
        print(f"\nLoading weights from {args.weights}...")
        weights_data = load_weights(args.weights)
        print(f"  Weights: {len(weights_data)} bytes")

    # Generate bundled source
    if args.minimal or not args.runtime:
        print("\nGenerating minimal bundled executable...")
        program_name = os.path.splitext(os.path.basename(args.output))[0]
        bundled = create_minimal_bundled(bytecode_data, data_section, program_name)
    else:
        print(f"\nGenerating bundled executable with {args.runtime}...")
        program_name = os.path.splitext(os.path.basename(args.output))[0]
        bundled = generate_bundled_c(args.runtime, weights_data, bytecode_data,
                                     data_section, program_name)

    # Write output
    with open(args.output, 'w') as f:
        f.write(bundled)

    print(f"\nWrote {args.output}")
    print(f"\nTo compile:")
    print(f"  gcc -O2 -o {os.path.splitext(args.output)[0]} {args.output}")


if __name__ == "__main__":
    main()
