"""Phase 11.C audit script.

Walk every ``DeclarativeAttentionHeadSpec`` instance in
``c4_release/neural_vm/unified_compiler/ops/*.py`` and classify each head's
K-side and Q-side gating:

  - k_gates_on_mark_only : K-side touches a MARK_* dim but NO OP_* dim.
  - k_gates_on_op        : K-side touches at least one OP_* dim.
  - q_implies_op         : Q-side touches at least one OP_* dim
                           (so K-side MARK_* is redundant — easy migration
                           target when combined with k_gates_on_mark_only).

For each head we emit one row with the classification + which MARK_* / OP_*
dim names appear on each side.

Run:
    python tools/phase11c_audit.py > .agent-logs/phase11c_audit.md
"""

from __future__ import annotations

import ast
import sys
from pathlib import Path
from typing import Optional


REPO_ROOT = Path(__file__).resolve().parent.parent
OPS_DIR = REPO_ROOT / "c4_release" / "neural_vm" / "unified_compiler" / "ops"


def _bd_attr_name(expr: ast.AST) -> Optional[str]:
    """Return ``"MARK_FOO"`` for ``BD.MARK_FOO`` (or for ``BD.MARK_FOO + n``)."""

    while isinstance(expr, ast.BinOp):
        # BD.OP_FOO + 3   -> recurse into the side that's an attribute access
        left_name = _bd_attr_name(expr.left)
        if left_name is not None:
            return left_name
        right_name = _bd_attr_name(expr.right)
        if right_name is not None:
            return right_name
        return None
    if isinstance(expr, ast.Attribute) and isinstance(expr.value, ast.Name):
        # Accept any one-letter dim-proxy name (BD is the canonical one).
        if expr.value.id in {"BD", "bd"}:
            return expr.attr
    return None


def _resolve_dim_arg(call: ast.Call) -> Optional[str]:
    """For ``AP(slot, dim, weight)`` or ``AO(out_dim, slot, weight)`` return
    the ``BD.<name>`` of the residual-stream dim.

    - ``AP``: second positional arg is ``dim``.
    - ``AO``: first positional arg is ``out_dim``.
    """

    fname = call.func.id if isinstance(call.func, ast.Name) else None
    if fname == "AP":
        # AP(slot, dim, weight) — dim is args[1] or kw "dim"
        if len(call.args) >= 2:
            return _bd_attr_name(call.args[1])
        for kw in call.keywords:
            if kw.arg == "dim":
                return _bd_attr_name(kw.value)
    elif fname == "AO":
        if len(call.args) >= 1:
            return _bd_attr_name(call.args[0])
        for kw in call.keywords:
            if kw.arg == "out_dim":
                return _bd_attr_name(kw.value)
    return None


def _gather_dim_names(node: ast.AST) -> set[str]:
    """Walk ``node`` collecting every ``BD.<NAME>`` referenced in any
    ``AP(...)`` / ``AO(...)`` call (including those generated by comprehensions
    / generator expressions / tuple multiplication)."""

    names: set[str] = set()
    for sub in ast.walk(node):
        if isinstance(sub, ast.Call) and isinstance(sub.func, ast.Name):
            if sub.func.id in {"AP", "AO"}:
                name = _resolve_dim_arg(sub)
                if name is not None:
                    names.add(name)
                continue
        # Bare BD.<NAME> outside an AP/AO call — also relevant (some helpers
        # build writes from a base dim attr alone).
        if isinstance(sub, ast.Attribute) and isinstance(sub.value, ast.Name):
            if sub.value.id in {"BD", "bd"} and (sub.attr.startswith("MARK_") or sub.attr.startswith("OP_")):
                names.add(sub.attr)
    return names


def _spec_head_idx(call: ast.Call) -> Optional[str]:
    """Return a printable head_idx expression for the spec call."""

    for kw in call.keywords:
        if kw.arg == "head_idx":
            try:
                return ast.unparse(kw.value)
            except Exception:
                return "<unparse-failed>"
    return None


def _spec_section(call: ast.Call, name: str) -> Optional[ast.AST]:
    for kw in call.keywords:
        if kw.arg == name:
            return kw.value
    return None


def classify_head(call: ast.Call) -> dict:
    q_node = _spec_section(call, "q")
    k_node = _spec_section(call, "k")

    q_names = _gather_dim_names(q_node) if q_node is not None else set()
    k_names = _gather_dim_names(k_node) if k_node is not None else set()

    q_marks = sorted(n for n in q_names if n.startswith("MARK_"))
    q_ops = sorted(n for n in q_names if n.startswith("OP_"))
    k_marks = sorted(n for n in k_names if n.startswith("MARK_"))
    k_ops = sorted(n for n in k_names if n.startswith("OP_"))

    if k_ops:
        category = "k_gates_on_op"
    elif k_marks:
        category = "k_gates_on_mark_only"
    else:
        category = "k_no_mark_no_op"

    q_implies_op = bool(q_ops)

    return {
        "category": category,
        "q_implies_op": q_implies_op,
        "q_marks": q_marks,
        "q_ops": q_ops,
        "k_marks": k_marks,
        "k_ops": k_ops,
    }


def audit_file(path: Path) -> list[dict]:
    src = path.read_text()
    try:
        tree = ast.parse(src, filename=str(path))
    except SyntaxError as exc:
        print(f"# SyntaxError in {path}: {exc}", file=sys.stderr)
        return []

    rows: list[dict] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            if node.func.id != "DeclarativeAttentionHeadSpec":
                continue
            info = classify_head(node)
            info["file"] = path.name
            info["lineno"] = node.lineno
            info["head_idx"] = _spec_head_idx(node) or "?"
            # Try to find enclosing function for context.
            info["enclosing"] = _find_enclosing_func(tree, node)
            rows.append(info)
    return rows


def _find_enclosing_func(tree: ast.AST, target: ast.AST) -> str:
    best = None
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            # ast nodes have lineno + end_lineno
            tl = getattr(target, "lineno", None)
            if tl is None:
                continue
            sl = getattr(node, "lineno", None)
            el = getattr(node, "end_lineno", None)
            if sl is not None and el is not None and sl <= tl <= el:
                if best is None or (best.end_lineno - best.lineno) > (el - sl):
                    best = node
    return best.name if best is not None else "<module>"


def main() -> None:
    files = sorted(p for p in OPS_DIR.glob("*.py"))
    all_rows: list[dict] = []
    for path in files:
        all_rows.extend(audit_file(path))

    # Also scan control_flow_heads / flag_gated_ops style additional files
    # (already in OPS_DIR — covered by the glob above).

    total = len(all_rows)
    by_cat: dict[str, int] = {}
    for row in all_rows:
        by_cat[row["category"]] = by_cat.get(row["category"], 0) + 1

    q_implies = sum(1 for r in all_rows if r["q_implies_op"])
    easy = sum(
        1
        for r in all_rows
        if r["category"] == "k_gates_on_mark_only" and r["q_implies_op"]
    )

    print("# Phase 11.C audit — DeclarativeAttentionHeadSpec K-gate classification")
    print()
    print(f"- Total heads scanned: **{total}**")
    print(f"- K-side categories:")
    for cat in ("k_gates_on_op", "k_gates_on_mark_only", "k_no_mark_no_op"):
        print(f"  - `{cat}`: **{by_cat.get(cat, 0)}**")
    print(f"- Q-side has OP_* gate: **{q_implies}**")
    print(
        f"- **Easy migrations** (K=MARK_only AND Q implies OP_): **{easy}**"
    )
    print()
    print("## Per-head verdicts")
    print()
    print("| file | line | head_idx | enclosing | category | q_implies_op | q_marks | q_ops | k_marks | k_ops |")
    print("|---|---|---|---|---|---|---|---|---|---|")
    for r in all_rows:
        print(
            "| {file} | {lineno} | {head_idx} | {enclosing} | {category} | {q_implies_op} | {q_marks} | {q_ops} | {k_marks} | {k_ops} |".format(
                file=r["file"],
                lineno=r["lineno"],
                head_idx=r["head_idx"],
                enclosing=r["enclosing"],
                category=r["category"],
                q_implies_op="YES" if r["q_implies_op"] else "no",
                q_marks=",".join(r["q_marks"]) or "-",
                q_ops=",".join(r["q_ops"]) or "-",
                k_marks=",".join(r["k_marks"]) or "-",
                k_ops=",".join(r["k_ops"]) or "-",
            )
        )

    print()
    print("## Easy migration candidates")
    print()
    print("Heads where K-side is `MARK_*` only AND Q-side already pins an OP_*. ")
    print("These are *structural* candidates -- a direct K-side OP_* addition would")
    print("further constrain the K-gate to opcode-discriminative behaviour, matching")
    print("the Phase 11.C goal. **NOTE:** structural candidacy does not imply")
    print("byte-identity-safe migration: the OP_* dim must be non-zero at the")
    print("K-attended residual position at the head's layer. Many candidates fail")
    print("this check because the OP_* marker is only written by a *later* layer.")
    print()
    print("| file | line | head_idx | enclosing | q_ops | k_marks (current) | notes |")
    print("|---|---|---|---|---|---|---|")
    for r in all_rows:
        if r["category"] == "k_gates_on_mark_only" and r["q_implies_op"]:
            print(
                "| {file} | {lineno} | {head_idx} | {enclosing} | {q_ops} | {k_marks} | structural only -- check OP_* residual timing |".format(
                    file=r["file"],
                    lineno=r["lineno"],
                    head_idx=r["head_idx"],
                    enclosing=r["enclosing"],
                    q_ops=",".join(r["q_ops"]),
                    k_marks=",".join(r["k_marks"]),
                )
            )


if __name__ == "__main__":
    main()
