/*
 * ONNX Runtime - C4 Compatible Implementation
 *
 * A limited ONNX runtime that can load and execute ONNX models.
 * Implements core operations needed for transformer inference.
 *
 * Supported Operations:
 *   - Gemm (General Matrix Multiply)
 *   - Add
 *   - Mul
 *   - Sub
 *   - Div
 *   - MatMul
 *   - Relu
 *   - Sigmoid
 *   - Tanh
 *   - Softmax
 *   - Reshape
 *   - Transpose
 *
 * Binary Format (simplified, generated by Python exporter):
 *   Header:
 *     magic: 4 bytes "ONNX"
 *     version: 4 bytes
 *     num_tensors: 4 bytes
 *     num_nodes: 4 bytes
 *
 *   Tensors (repeated num_tensors times):
 *     name_len: 4 bytes
 *     name: name_len bytes
 *     ndims: 4 bytes
 *     dims: ndims * 4 bytes
 *     data_type: 4 bytes (0=float, 1=int)
 *     data_size: 4 bytes (in elements)
 *     data: data_size * 4 bytes (fixed-point for float)
 *
 *   Nodes (repeated num_nodes times):
 *     op_type: 4 bytes (enum)
 *     num_inputs: 4 bytes
 *     inputs: num_inputs * 4 bytes (tensor indices)
 *     num_outputs: 4 bytes
 *     outputs: num_outputs * 4 bytes (tensor indices)
 *     num_attrs: 4 bytes
 *     attrs: variable (depends on op)
 *
 * Build with gcc:
 *   gcc -O2 -o onnx_runtime_c4 onnx_runtime_c4.c
 *
 * Build with c4:
 *   ./c4 onnx_runtime_c4.c
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ============ Fixed-Point Arithmetic (16.16) ============ */
/* Shared math with neural_bundler.py runtime — identical implementations. */

int SCALE;      /* 16.16 fixed point: 65536 */
int HALF;       /* Rounding: 32768 */

int init_fp() {
    SCALE = 65536;
    HALF = 32768;
    return 0;
}

int fp_mul(int a, int b) {
    return (a / 256) * (b / 256);
}

int fp_div(int a, int b) {
    if (b == 0) return 0;
    return (a * 256) / (b / 256);
}

/* 2^x via bit shift + degree-3 polynomial for fractional part.
 * exp(x) = 2^(x * log2(e)), where log2(e) = 1.4427 ≈ 94548 in 16.16.
 *
 * For f in [0,1), 2^f ≈ 65536 + 45426*f + 15743*f^2 + 3638*f^3
 * All products via fp_mul to stay in 32-bit int. */
int fp_pow2(int x) {
    int int_part;
    int frac;
    int f2;
    int f3;
    int val;
    int neg;

    if (x >= 0) {
        int_part = x / 65536;
    } else {
        int_part = 0 - ((0 - x + 65535) / 65536);
    }
    frac = x - int_part * 65536;

    f2 = fp_mul(frac, frac);
    f3 = fp_mul(f2, frac);
    val = 65536
        + fp_mul(45426, frac)
        + fp_mul(15743, f2)
        + fp_mul(3638, f3);

    if (int_part >= 0) {
        if (int_part >= 20) return 0x7FFFFFFF;
        return val << int_part;
    } else {
        neg = 0 - int_part;
        if (neg >= 30) return 0;
        return val >> neg;
    }
}

int fp_exp(int x) {
    int y;
    y = fp_mul(x, 94548);  /* x * log2(e) */
    if (y > 20 * 65536) return 0x7FFFFFFF;
    if (y < 0 - 30 * 65536) return 0;
    return fp_pow2(y);
}

int fp_sigmoid(int x) {
    int enx;
    int denom;

    if (x >= SCALE * 8) return SCALE;
    if (x <= 0 - SCALE * 8) return 0;
    enx = fp_exp(0 - x);
    denom = SCALE + enx;
    if (denom == 0) return SCALE;
    return fp_div(SCALE, denom);
}

int fp_silu(int x) {
    return fp_mul(x, fp_sigmoid(x));
}

int fp_relu(int x) {
    if (x < 0) return 0;
    return x;
}

int fp_tanh(int x) {
    int sig;
    sig = fp_sigmoid(x * 2);
    return sig * 2 - SCALE;
}

/* ============ Tensor Structure ============ */

int MAX_TENSORS;
int MAX_DIMS;
int MAX_NAME;

/* Tensor storage */
int **tensor_data;     /* Array of data pointers */
int *tensor_size;      /* Size in elements */
int *tensor_ndims;     /* Number of dimensions */
int **tensor_dims;     /* Array of dimension arrays */
char **tensor_names;   /* Tensor names */
int num_tensors;

/* Sparse tensor storage (COO format) */
int **tensor_sparse_idx;  /* COO indices (NULL if dense) */
int **tensor_sparse_val;  /* COO values (NULL if dense) */
int *tensor_nnz;          /* nonzero count per tensor */

/* ============ Operation Types ============ */

int OP_GEMM;
int OP_ADD;
int OP_MUL;
int OP_SUB;
int OP_DIV;
int OP_MATMUL;
int OP_RELU;
int OP_SIGMOID;
int OP_SILU;
int OP_TANH;
int OP_SOFTMAX;
int OP_RESHAPE;
int OP_TRANSPOSE;
int OP_IDENTITY;
int OP_CONCAT;
int OP_SLICE;
int OP_SCALE;

int init_ops() {
    OP_GEMM = 0;
    OP_ADD = 1;
    OP_MUL = 2;
    OP_SUB = 3;
    OP_DIV = 4;
    OP_MATMUL = 5;
    OP_RELU = 6;
    OP_SIGMOID = 7;
    OP_SILU = 8;
    OP_TANH = 9;
    OP_SOFTMAX = 10;
    OP_RESHAPE = 11;
    OP_TRANSPOSE = 12;
    OP_IDENTITY = 13;
    OP_CONCAT = 14;
    OP_SLICE = 15;
    OP_SCALE = 16;
    return 0;
}

/* Node structure */
int *node_op;          /* Operation type */
int *node_num_inputs;
int **node_inputs;     /* Input tensor indices */
int *node_num_outputs;
int **node_outputs;    /* Output tensor indices */
int num_nodes;

/* ============ Tensor Operations ============ */

int init_tensors() {
    int i;

    MAX_TENSORS = 256;
    MAX_DIMS = 8;
    MAX_NAME = 64;

    tensor_data = malloc(MAX_TENSORS * sizeof(int *));
    tensor_size = malloc(MAX_TENSORS * sizeof(int));
    tensor_ndims = malloc(MAX_TENSORS * sizeof(int));
    tensor_dims = malloc(MAX_TENSORS * sizeof(int *));
    tensor_names = malloc(MAX_TENSORS * sizeof(char *));
    tensor_sparse_idx = malloc(MAX_TENSORS * sizeof(int *));
    tensor_sparse_val = malloc(MAX_TENSORS * sizeof(int *));
    tensor_nnz = malloc(MAX_TENSORS * sizeof(int));

    i = 0;
    while (i < MAX_TENSORS) {
        tensor_data[i] = 0;
        tensor_size[i] = 0;
        tensor_ndims[i] = 0;
        tensor_dims[i] = malloc(MAX_DIMS * sizeof(int));
        tensor_names[i] = malloc(MAX_NAME);
        tensor_names[i][0] = 0;
        tensor_sparse_idx[i] = 0;
        tensor_sparse_val[i] = 0;
        tensor_nnz[i] = 0;
        i = i + 1;
    }

    num_tensors = 0;
    return 0;
}

int init_nodes() {
    int i;
    int MAX_NODES;
    int MAX_IO;

    MAX_NODES = 512;
    MAX_IO = 8;

    node_op = malloc(MAX_NODES * sizeof(int));
    node_num_inputs = malloc(MAX_NODES * sizeof(int));
    node_inputs = malloc(MAX_NODES * sizeof(int *));
    node_num_outputs = malloc(MAX_NODES * sizeof(int));
    node_outputs = malloc(MAX_NODES * sizeof(int *));

    i = 0;
    while (i < MAX_NODES) {
        node_inputs[i] = malloc(MAX_IO * sizeof(int));
        node_outputs[i] = malloc(MAX_IO * sizeof(int));
        i = i + 1;
    }

    num_nodes = 0;
    return 0;
}

/* Allocate tensor with given dimensions */
int alloc_tensor(int idx, int ndims, int *dims) {
    int size;
    int i;

    size = 1;
    i = 0;
    while (i < ndims) {
        tensor_dims[idx][i] = dims[i];
        size = size * dims[i];
        i = i + 1;
    }

    tensor_ndims[idx] = ndims;
    tensor_size[idx] = size;
    tensor_data[idx] = malloc(size * sizeof(int));

    /* Zero initialize */
    i = 0;
    while (i < size) {
        tensor_data[idx][i] = 0;
        i = i + 1;
    }

    return 0;
}

/* Get linear index for multi-dimensional access */
int get_linear_idx(int tensor_idx, int *indices) {
    int idx;
    int stride;
    int i;
    int ndims;

    ndims = tensor_ndims[tensor_idx];
    idx = 0;
    stride = 1;

    i = ndims - 1;
    while (i >= 0) {
        idx = idx + indices[i] * stride;
        stride = stride * tensor_dims[tensor_idx][i];
        i = i - 1;
    }

    return idx;
}

/* ============ Core ONNX Operations ============ */

/* Add: C = A + B (element-wise with broadcasting) */
int op_add(int out_idx, int a_idx, int b_idx) {
    int i;
    int size;
    int *a;
    int *b;
    int *c;

    size = tensor_size[out_idx];
    a = tensor_data[a_idx];
    b = tensor_data[b_idx];
    c = tensor_data[out_idx];

    i = 0;
    while (i < size) {
        c[i] = a[i % tensor_size[a_idx]] + b[i % tensor_size[b_idx]];
        i = i + 1;
    }

    return 0;
}

/* Mul: C = A * B (element-wise) */
int op_mul(int out_idx, int a_idx, int b_idx) {
    int i;
    int size;
    int *a;
    int *b;
    int *c;

    size = tensor_size[out_idx];
    a = tensor_data[a_idx];
    b = tensor_data[b_idx];
    c = tensor_data[out_idx];

    i = 0;
    while (i < size) {
        c[i] = fp_mul(a[i % tensor_size[a_idx]], b[i % tensor_size[b_idx]]);
        i = i + 1;
    }

    return 0;
}

/* Sub: C = A - B */
int op_sub(int out_idx, int a_idx, int b_idx) {
    int i;
    int size;

    size = tensor_size[out_idx];

    i = 0;
    while (i < size) {
        tensor_data[out_idx][i] =
            tensor_data[a_idx][i % tensor_size[a_idx]] -
            tensor_data[b_idx][i % tensor_size[b_idx]];
        i = i + 1;
    }

    return 0;
}

/* Div: C = A / B */
int op_div(int out_idx, int a_idx, int b_idx) {
    int i;
    int size;

    size = tensor_size[out_idx];

    i = 0;
    while (i < size) {
        tensor_data[out_idx][i] = fp_div(
            tensor_data[a_idx][i % tensor_size[a_idx]],
            tensor_data[b_idx][i % tensor_size[b_idx]]);
        i = i + 1;
    }

    return 0;
}

/* MatMul: C[m,n] = A[m,k] @ B[k,n] */
int op_matmul(int out_idx, int a_idx, int b_idx) {
    int m;
    int k;
    int n;
    int i;
    int j;
    int l;
    int sum;
    int *a;
    int *b;
    int *c;

    /* Assuming 2D tensors */
    m = tensor_dims[a_idx][0];
    k = tensor_dims[a_idx][1];
    n = tensor_dims[b_idx][1];

    a = tensor_data[a_idx];
    b = tensor_data[b_idx];
    c = tensor_data[out_idx];

    i = 0;
    while (i < m) {
        j = 0;
        while (j < n) {
            sum = 0;
            l = 0;
            while (l < k) {
                sum = sum + fp_mul(a[i * k + l], b[l * n + j]);
                l = l + 1;
            }
            c[i * n + j] = sum;
            j = j + 1;
        }
        i = i + 1;
    }

    return 0;
}

/* Gemm: Y = alpha * A @ B + beta * C */
int op_gemm(int out_idx, int a_idx, int b_idx, int c_idx, int alpha, int beta) {
    int m;
    int k;
    int n;
    int i;
    int j;
    int l;
    int sum;
    int *a;
    int *b;
    int *c;
    int *y;

    m = tensor_dims[a_idx][0];
    k = tensor_dims[a_idx][1];
    n = tensor_dims[b_idx][1];

    a = tensor_data[a_idx];
    b = tensor_data[b_idx];
    c = tensor_data[c_idx];
    y = tensor_data[out_idx];

    i = 0;
    while (i < m) {
        j = 0;
        while (j < n) {
            sum = 0;
            l = 0;
            while (l < k) {
                sum = sum + fp_mul(a[i * k + l], b[l * n + j]);
                l = l + 1;
            }
            y[i * n + j] = fp_mul(alpha, sum) + fp_mul(beta, c[j % tensor_size[c_idx]]);
            j = j + 1;
        }
        i = i + 1;
    }

    return 0;
}

/* Relu: Y = max(0, X) */
int op_relu(int out_idx, int in_idx) {
    int i;
    int size;

    size = tensor_size[in_idx];

    i = 0;
    while (i < size) {
        tensor_data[out_idx][i] = fp_relu(tensor_data[in_idx][i]);
        i = i + 1;
    }

    return 0;
}

/* Sigmoid: Y = 1 / (1 + exp(-X)) */
int op_sigmoid(int out_idx, int in_idx) {
    int i;
    int size;

    size = tensor_size[in_idx];

    i = 0;
    while (i < size) {
        tensor_data[out_idx][i] = fp_sigmoid(tensor_data[in_idx][i]);
        i = i + 1;
    }

    return 0;
}

/* SiLU: Y = X * sigmoid(X) */
int op_silu(int out_idx, int in_idx) {
    int i;
    int size;

    size = tensor_size[in_idx];

    i = 0;
    while (i < size) {
        tensor_data[out_idx][i] = fp_silu(tensor_data[in_idx][i]);
        i = i + 1;
    }

    return 0;
}

/* Tanh: Y = tanh(X) */
int op_tanh(int out_idx, int in_idx) {
    int i;
    int size;

    size = tensor_size[in_idx];

    i = 0;
    while (i < size) {
        tensor_data[out_idx][i] = fp_tanh(tensor_data[in_idx][i]);
        i = i + 1;
    }

    return 0;
}

/* Softmax: Y[i] = exp(X[i]) / sum(exp(X[j])) along last axis */
int op_softmax(int out_idx, int in_idx) {
    int batch_size;
    int last_dim;
    int ndims;
    int b;
    int i;
    int max_val;
    int sum;
    int offset;

    ndims = tensor_ndims[in_idx];
    last_dim = tensor_dims[in_idx][ndims - 1];
    batch_size = tensor_size[in_idx] / last_dim;

    b = 0;
    while (b < batch_size) {
        offset = b * last_dim;

        /* Find max for numerical stability */
        max_val = tensor_data[in_idx][offset];
        i = 1;
        while (i < last_dim) {
            if (tensor_data[in_idx][offset + i] > max_val) {
                max_val = tensor_data[in_idx][offset + i];
            }
            i = i + 1;
        }

        /* Compute exp and sum */
        sum = 0;
        i = 0;
        while (i < last_dim) {
            tensor_data[out_idx][offset + i] =
                fp_exp(tensor_data[in_idx][offset + i] - max_val);
            sum = sum + tensor_data[out_idx][offset + i];
            i = i + 1;
        }

        /* Normalize */
        if (sum > 0) {
            i = 0;
            while (i < last_dim) {
                tensor_data[out_idx][offset + i] =
                    fp_div(tensor_data[out_idx][offset + i], sum);
                i = i + 1;
            }
        }

        b = b + 1;
    }

    return 0;
}

/* Reshape: just copy with new shape */
int op_reshape(int out_idx, int in_idx) {
    int i;
    int size;

    size = tensor_size[in_idx];

    i = 0;
    while (i < size) {
        tensor_data[out_idx][i] = tensor_data[in_idx][i];
        i = i + 1;
    }

    return 0;
}

/* Identity: Y = X */
int op_identity(int out_idx, int in_idx) {
    int i;
    int size;

    size = tensor_size[in_idx];

    i = 0;
    while (i < size) {
        tensor_data[out_idx][i] = tensor_data[in_idx][i];
        i = i + 1;
    }

    return 0;
}

/* Concat: concatenate multiple 1D tensors along axis 0 */
int op_concat(int out_idx, int *in_indices, int num_in) {
    int i;
    int j;
    int offset;
    int size;

    offset = 0;
    i = 0;
    while (i < num_in) {
        size = tensor_size[in_indices[i]];
        j = 0;
        while (j < size) {
            tensor_data[out_idx][offset + j] = tensor_data[in_indices[i]][j];
            j = j + 1;
        }
        offset = offset + size;
        i = i + 1;
    }

    return 0;
}

/* Slice: extract range [start:end] from 1D tensor */
int op_slice(int out_idx, int in_idx, int start, int end) {
    int i;
    int len;

    len = end - start;
    i = 0;
    while (i < len) {
        tensor_data[out_idx][i] = tensor_data[in_idx][start + i];
        i = i + 1;
    }

    return 0;
}

/* Scale: multiply all elements by a scalar (fixed-point) */
int op_scale(int out_idx, int in_idx, int scalar) {
    int i;
    int size;

    size = tensor_size[in_idx];
    i = 0;
    while (i < size) {
        tensor_data[out_idx][i] = fp_mul(tensor_data[in_idx][i], scalar);
        i = i + 1;
    }

    return 0;
}

/* Sparse MatMul: out = in @ W_sparse (COO format) */
int op_matmul_sparse(int out_idx, int in_idx, int *sp_indices, int *sp_values, int nnz, int ncols, int out_size) {
    int i;
    int row;
    int col;
    int *out;
    int *in;

    out = tensor_data[out_idx];
    in = tensor_data[in_idx];

    i = 0;
    while (i < out_size) { out[i] = 0; i = i + 1; }

    i = 0;
    while (i < nnz) {
        row = sp_indices[i] / ncols;
        col = sp_indices[i] % ncols;
        out[col] = out[col] + fp_mul(in[row], sp_values[i]);
        i = i + 1;
    }

    return 0;
}

/* ============ Subgraph Storage (v3) ============ */

int MAX_SUBGRAPHS;
int MAX_SG_NODES;
int MAX_SG_IO;

int num_subgraphs;
char **sg_names;
int *sg_num_inputs;
int *sg_num_outputs;
int *sg_num_temps;
int **sg_temp_sizes;
int *sg_num_nodes;
int **sg_node_op;
int ***sg_node_inputs;
int **sg_node_num_in;
int ***sg_node_outputs;
int **sg_node_num_out;

int init_subgraphs() {
    int i;
    int j;

    MAX_SUBGRAPHS = 32;
    MAX_SG_NODES = 16;
    MAX_SG_IO = 8;

    sg_names = malloc(MAX_SUBGRAPHS * sizeof(char *));
    sg_num_inputs = malloc(MAX_SUBGRAPHS * sizeof(int));
    sg_num_outputs = malloc(MAX_SUBGRAPHS * sizeof(int));
    sg_num_temps = malloc(MAX_SUBGRAPHS * sizeof(int));
    sg_temp_sizes = malloc(MAX_SUBGRAPHS * sizeof(int *));
    sg_num_nodes = malloc(MAX_SUBGRAPHS * sizeof(int));
    sg_node_op = malloc(MAX_SUBGRAPHS * sizeof(int *));
    sg_node_inputs = malloc(MAX_SUBGRAPHS * sizeof(int **));
    sg_node_num_in = malloc(MAX_SUBGRAPHS * sizeof(int *));
    sg_node_outputs = malloc(MAX_SUBGRAPHS * sizeof(int **));
    sg_node_num_out = malloc(MAX_SUBGRAPHS * sizeof(int *));

    i = 0;
    while (i < MAX_SUBGRAPHS) {
        sg_names[i] = malloc(64);
        sg_names[i][0] = 0;
        sg_temp_sizes[i] = malloc(16 * sizeof(int));
        sg_node_op[i] = malloc(MAX_SG_NODES * sizeof(int));
        sg_node_inputs[i] = malloc(MAX_SG_NODES * sizeof(int *));
        sg_node_num_in[i] = malloc(MAX_SG_NODES * sizeof(int));
        sg_node_outputs[i] = malloc(MAX_SG_NODES * sizeof(int *));
        sg_node_num_out[i] = malloc(MAX_SG_NODES * sizeof(int));
        j = 0;
        while (j < MAX_SG_NODES) {
            sg_node_inputs[i][j] = malloc(MAX_SG_IO * sizeof(int));
            sg_node_outputs[i][j] = malloc(MAX_SG_IO * sizeof(int));
            j = j + 1;
        }
        i = i + 1;
    }
    num_subgraphs = 0;

    return 0;
}

/* ============ Subgraph Executor ============ */

/* Resolve a subgraph node reference to a data pointer.
 * ref >= 0: global tensor index
 * ref < 0: local ref:
 *   -1..-num_inputs: subgraph inputs
 *   -(num_inputs+1)..-(num_inputs+num_temps): temps
 *   -(num_inputs+num_temps+1)..: outputs */
int *sg_resolve(int ref, int sg, int **inputs, int **outputs, int **temps) {
    int local;
    int ni;
    int nt;
    if (ref >= 0) return tensor_data[ref];
    local = (0 - ref) - 1;
    ni = sg_num_inputs[sg];
    nt = sg_num_temps[sg];
    if (local < ni) return inputs[local];
    local = local - ni;
    if (local < nt) return temps[local];
    local = local - nt;
    return outputs[local];
}

int sg_resolve_size(int ref, int sg, int *in_sizes, int *out_sizes) {
    int local;
    int ni;
    int nt;
    if (ref >= 0) return tensor_size[ref];
    local = (0 - ref) - 1;
    ni = sg_num_inputs[sg];
    nt = sg_num_temps[sg];
    if (local < ni) return in_sizes[local];
    local = local - ni;
    if (local < nt) return sg_temp_sizes[sg][local];
    local = local - nt;
    return out_sizes[local];
}

int run_subgraph(int sg, int **inputs, int **outputs, int *in_sizes, int *out_sizes) {
    int **temps;
    int n;
    int i;
    int j;
    int op;
    int *src;
    int *dst;
    int src_size;
    int dst_size;
    int w_idx;
    int m;
    int offset;
    int len;

    n = sg_num_temps[sg];
    temps = malloc(n * sizeof(int *));
    i = 0;
    while (i < n) {
        temps[i] = malloc(sg_temp_sizes[sg][i] * sizeof(int));
        j = 0;
        while (j < sg_temp_sizes[sg][i]) { temps[i][j] = 0; j = j + 1; }
        i = i + 1;
    }

    /* Execute nodes */
    i = 0;
    while (i < sg_num_nodes[sg]) {
        op = sg_node_op[sg][i];
        dst = sg_resolve(sg_node_outputs[sg][i][0], sg, inputs, outputs, temps);
        dst_size = sg_resolve_size(sg_node_outputs[sg][i][0], sg, in_sizes, out_sizes);

        if (op == OP_MATMUL) {
            /* dst = src @ weight_tensor */
            src = sg_resolve(sg_node_inputs[sg][i][0], sg, inputs, outputs, temps);
            w_idx = sg_node_inputs[sg][i][1];
            src_size = sg_resolve_size(sg_node_inputs[sg][i][0], sg, in_sizes, out_sizes);
            /* Use sparse matmul if tensor has sparse data */
            if (w_idx >= 0 && tensor_sparse_idx[w_idx] != 0) {
                int si;
                int row;
                int col;
                int ncols;
                int nnz;
                int *sp_idx;
                int *sp_val;

                nnz = tensor_nnz[w_idx];
                ncols = tensor_dims[w_idx][1];
                sp_idx = tensor_sparse_idx[w_idx];
                sp_val = tensor_sparse_val[w_idx];

                si = 0;
                while (si < dst_size) { dst[si] = 0; si = si + 1; }
                si = 0;
                while (si < nnz) {
                    row = sp_idx[si] / ncols;
                    col = sp_idx[si] % ncols;
                    dst[col] = dst[col] + fp_mul(src[row], sp_val[si]);
                    si = si + 1;
                }
            } else {
                /* Dense matmul: out[n] = in[m] @ W[m*n] */
                m = src_size;
                j = 0;
                while (j < dst_size) {
                    int acc;
                    int k;
                    acc = 0;
                    k = 0;
                    while (k < m) {
                        acc = acc + fp_mul(src[k], tensor_data[w_idx][k * dst_size + j]);
                        k = k + 1;
                    }
                    dst[j] = acc;
                    j = j + 1;
                }
            }
        }
        else if (op == OP_SOFTMAX) {
            int max_val;
            int sum;
            int si;

            src = sg_resolve(sg_node_inputs[sg][i][0], sg, inputs, outputs, temps);
            max_val = src[0];
            si = 1;
            while (si < dst_size) {
                if (src[si] > max_val) max_val = src[si];
                si = si + 1;
            }
            sum = 0;
            si = 0;
            while (si < dst_size) {
                dst[si] = fp_exp(src[si] - max_val);
                sum = sum + dst[si];
                si = si + 1;
            }
            if (sum > 0) {
                si = 0;
                while (si < dst_size) {
                    dst[si] = fp_div(dst[si], sum);
                    si = si + 1;
                }
            }
        }
        else if (op == OP_CONCAT) {
            /* Concatenate all inputs */
            offset = 0;
            j = 0;
            while (j < sg_node_num_in[sg][i]) {
                src = sg_resolve(sg_node_inputs[sg][i][j], sg, inputs, outputs, temps);
                src_size = sg_resolve_size(sg_node_inputs[sg][i][j], sg, in_sizes, out_sizes);
                m = 0;
                while (m < src_size) {
                    dst[offset + m] = src[m];
                    m = m + 1;
                }
                offset = offset + src_size;
                j = j + 1;
            }
        }
        else if (op == OP_SLICE) {
            /* dst = src[start:end] */
            src = sg_resolve(sg_node_inputs[sg][i][0], sg, inputs, outputs, temps);
            offset = sg_node_inputs[sg][i][1];  /* start */
            len = sg_node_inputs[sg][i][2] - offset;  /* end - start */
            j = 0;
            while (j < len) {
                dst[j] = src[offset + j];
                j = j + 1;
            }
        }
        else if (op == OP_SCALE) {
            /* dst = src * scalar_fp */
            src = sg_resolve(sg_node_inputs[sg][i][0], sg, inputs, outputs, temps);
            src_size = sg_resolve_size(sg_node_inputs[sg][i][0], sg, in_sizes, out_sizes);
            m = sg_node_inputs[sg][i][1];  /* scalar value in 16.16 FP */
            j = 0;
            while (j < src_size) {
                dst[j] = fp_mul(src[j], m);
                j = j + 1;
            }
        }
        else {
            printf("Subgraph unknown op: %d\n", op);
        }

        i = i + 1;
    }

    /* Free temps */
    i = 0;
    while (i < n) {
        free(temps[i]);
        i = i + 1;
    }
    free(temps);

    return 0;
}

/* Find subgraph by name */
int find_subgraph(char *name) {
    int i;
    int j;
    int match;
    i = 0;
    while (i < num_subgraphs) {
        j = 0;
        match = 1;
        while (sg_names[i][j] && name[j]) {
            if (sg_names[i][j] != name[j]) { match = 0; }
            j = j + 1;
        }
        if (match && sg_names[i][j] == name[j]) return i;
        i = i + 1;
    }
    return -1;
}

/* ============ Model Execution ============ */

/* Execute a single node */
int execute_node(int node_idx) {
    int op;
    int out;
    int in0;
    int in1;
    int in2;

    op = node_op[node_idx];
    out = node_outputs[node_idx][0];
    in0 = node_inputs[node_idx][0];

    if (node_num_inputs[node_idx] > 1) {
        in1 = node_inputs[node_idx][1];
    } else {
        in1 = 0;
    }

    if (node_num_inputs[node_idx] > 2) {
        in2 = node_inputs[node_idx][2];
    } else {
        in2 = 0;
    }

    if (op == OP_ADD) {
        op_add(out, in0, in1);
    } else if (op == OP_MUL) {
        op_mul(out, in0, in1);
    } else if (op == OP_SUB) {
        op_sub(out, in0, in1);
    } else if (op == OP_DIV) {
        op_div(out, in0, in1);
    } else if (op == OP_MATMUL) {
        if (tensor_sparse_idx[in1] != 0) {
            op_matmul_sparse(out, in0, tensor_sparse_idx[in1],
                             tensor_sparse_val[in1], tensor_nnz[in1],
                             tensor_dims[in1][1], tensor_size[out]);
        } else {
            op_matmul(out, in0, in1);
        }
    } else if (op == OP_GEMM) {
        op_gemm(out, in0, in1, in2, SCALE, SCALE);
    } else if (op == OP_RELU) {
        op_relu(out, in0);
    } else if (op == OP_SIGMOID) {
        op_sigmoid(out, in0);
    } else if (op == OP_SILU) {
        op_silu(out, in0);
    } else if (op == OP_TANH) {
        op_tanh(out, in0);
    } else if (op == OP_SOFTMAX) {
        op_softmax(out, in0);
    } else if (op == OP_RESHAPE) {
        op_reshape(out, in0);
    } else if (op == OP_IDENTITY) {
        op_identity(out, in0);
    } else if (op == OP_CONCAT) {
        op_concat(out, node_inputs[node_idx], node_num_inputs[node_idx]);
    } else if (op == OP_SLICE) {
        /* Slice params encoded in input indices: in0=tensor, in1=start, in2=end */
        op_slice(out, in0, in1, in2);
    } else if (op == OP_SCALE) {
        /* Scale param encoded in in1 */
        op_scale(out, in0, in1);
    } else {
        printf("Unknown op: %d\n", op);
        return -1;
    }

    return 0;
}

/* Execute entire model (sequential) */
int run_model() {
    int i;

    i = 0;
    while (i < num_nodes) {
        execute_node(i);
        i = i + 1;
    }

    return 0;
}


/* ============ Binary Model Loading ============ */

int read_int(FILE *f) {
    int val;
    unsigned char buf[4];

    if (fread(buf, 1, 4, f) != 4) return -1;

    /* Little-endian */
    val = buf[0] | (buf[1] << 8) | (buf[2] << 16) | (buf[3] << 24);
    return val;
}

int load_model(char *filename) {
    FILE *f;
    int magic;
    int version;
    int n_tensors;
    int n_nodes;
    int i;
    int j;
    int k;
    int name_len;
    int ndims;
    int dims[8];
    int data_size;
    int storage_type;
    int nnz;
    int op;
    int num_in;
    int num_out;

    f = fopen(filename, "rb");
    if (!f) {
        printf("Error: cannot open %s\n", filename);
        return -1;
    }

    /* Read header */
    magic = read_int(f);
    if (magic != 0x584E4E4F) {  /* "ONNX" in little-endian */
        printf("Error: invalid magic number\n");
        fclose(f);
        return -1;
    }

    version = read_int(f);
    n_tensors = read_int(f);
    n_nodes = read_int(f);

    printf("Loading model: version=%d, tensors=%d, nodes=%d\n",
           version, n_tensors, n_nodes);

    /* Load tensors */
    i = 0;
    while (i < n_tensors) {
        name_len = read_int(f);
        if (name_len > 0 && name_len < MAX_NAME) {
            fread(tensor_names[i], 1, name_len, f);
            tensor_names[i][name_len] = 0;
        }

        ndims = read_int(f);
        j = 0;
        while (j < ndims) {
            dims[j] = read_int(f);
            j = j + 1;
        }

        if (version >= 3) {
            /* v3: storage_type field before data */
            storage_type = read_int(f);
        } else {
            /* v2: data_type field (ignored), always dense */
            read_int(f);
            storage_type = 0;
        }

        if (storage_type == 1) {
            /* Sparse COO */
            nnz = read_int(f);
            alloc_tensor(i, ndims, dims);
            tensor_nnz[i] = nnz;
            tensor_sparse_idx[i] = malloc(nnz * sizeof(int));
            tensor_sparse_val[i] = malloc(nnz * sizeof(int));
            j = 0;
            while (j < nnz) {
                tensor_sparse_idx[i][j] = read_int(f);
                j = j + 1;
            }
            j = 0;
            while (j < nnz) {
                tensor_sparse_val[i][j] = read_int(f);
                j = j + 1;
            }
            /* Also reconstruct dense data for ops that need it */
            j = 0;
            while (j < nnz) {
                tensor_data[i][tensor_sparse_idx[i][j]] = tensor_sparse_val[i][j];
                j = j + 1;
            }
        } else {
            /* Dense */
            data_size = read_int(f);
            alloc_tensor(i, ndims, dims);
            j = 0;
            while (j < data_size) {
                tensor_data[i][j] = read_int(f);
                j = j + 1;
            }
        }

        i = i + 1;
    }
    num_tensors = n_tensors;

    if (version >= 3) {
        /* Load subgraphs (v3) */
        i = 0;
        while (i < n_nodes) {  /* n_nodes is actually num_subgraphs in v3 */
            name_len = read_int(f);
            j = 0;
            while (j < name_len && j < 63) {
                sg_names[i][j] = fgetc(f);
                j = j + 1;
            }
            sg_names[i][j] = 0;

            sg_num_inputs[i] = read_int(f);
            sg_num_outputs[i] = read_int(f);
            sg_num_temps[i] = read_int(f);
            j = 0;
            while (j < sg_num_temps[i]) {
                sg_temp_sizes[i][j] = read_int(f);
                j = j + 1;
            }

            sg_num_nodes[i] = read_int(f);
            j = 0;
            while (j < sg_num_nodes[i]) {
                sg_node_op[i][j] = read_int(f);
                num_in = read_int(f);
                sg_node_num_in[i][j] = num_in;
                k = 0;
                while (k < num_in) {
                    sg_node_inputs[i][j][k] = read_int(f);
                    k = k + 1;
                }
                num_out = read_int(f);
                sg_node_num_out[i][j] = num_out;
                k = 0;
                while (k < num_out) {
                    sg_node_outputs[i][j][k] = read_int(f);
                    k = k + 1;
                }
                j = j + 1;
            }

            printf("  Subgraph: %s (%d inputs, %d outputs, %d nodes)\n",
                   sg_names[i], sg_num_inputs[i], sg_num_outputs[i], sg_num_nodes[i]);
            i = i + 1;
        }
        num_subgraphs = n_nodes;
        num_nodes = 0;
    } else {
        /* Load nodes (v1/v2 style) */
        i = 0;
        while (i < n_nodes) {
            op = read_int(f);
            num_in = read_int(f);

            node_op[i] = op;
            node_num_inputs[i] = num_in;

            j = 0;
            while (j < num_in) {
                node_inputs[i][j] = read_int(f);
                j = j + 1;
            }

            num_out = read_int(f);
            node_num_outputs[i] = num_out;

            j = 0;
            while (j < num_out) {
                node_outputs[i][j] = read_int(f);
                j = j + 1;
            }

            i = i + 1;
        }
        num_nodes = n_nodes;
    }

    fclose(f);
    printf("Model loaded successfully\n");
    return 0;
}

/* ============ Test Operations ============ */

int test_ops() {
    int dims2[2];
    int dims1[1];
    int i;

    printf("=== ONNX Runtime C4 - Operation Tests ===\n\n");

    /* Create test tensors */
    dims2[0] = 2;
    dims2[1] = 3;
    alloc_tensor(0, 2, dims2);  /* A: 2x3 */
    alloc_tensor(1, 2, dims2);  /* B: 2x3 */
    alloc_tensor(2, 2, dims2);  /* C: 2x3 (output) */

    /* Initialize A and B */
    i = 0;
    while (i < 6) {
        tensor_data[0][i] = (i + 1) * SCALE;  /* A = [1,2,3,4,5,6] */
        tensor_data[1][i] = (i + 1) * SCALE;  /* B = [1,2,3,4,5,6] */
        i = i + 1;
    }

    /* Test Add */
    printf("Add test:\n");
    op_add(2, 0, 1);
    printf("  A + B = [");
    i = 0;
    while (i < 6) {
        printf("%d", tensor_data[2][i] / SCALE);
        if (i < 5) printf(", ");
        i = i + 1;
    }
    printf("] (expected [2,4,6,8,10,12])\n");

    /* Test Mul */
    printf("Mul test:\n");
    op_mul(2, 0, 1);
    printf("  A * B = [");
    i = 0;
    while (i < 6) {
        printf("%d", tensor_data[2][i] / SCALE);
        if (i < 5) printf(", ");
        i = i + 1;
    }
    printf("] (expected [1,4,9,16,25,36])\n");

    /* Test Relu */
    printf("Relu test:\n");
    tensor_data[0][0] = 0 - 2 * SCALE;  /* -2 */
    tensor_data[0][1] = 0 - 1 * SCALE;  /* -1 */
    tensor_data[0][2] = 0;               /* 0 */
    tensor_data[0][3] = 1 * SCALE;       /* 1 */
    tensor_data[0][4] = 2 * SCALE;       /* 2 */
    tensor_data[0][5] = 3 * SCALE;       /* 3 */
    op_relu(2, 0);
    printf("  relu([-2,-1,0,1,2,3]) = [");
    i = 0;
    while (i < 6) {
        printf("%d", tensor_data[2][i] / SCALE);
        if (i < 5) printf(", ");
        i = i + 1;
    }
    printf("] (expected [0,0,0,1,2,3])\n");

    /* Test MatMul */
    printf("\nMatMul test:\n");
    dims2[0] = 2;
    dims2[1] = 2;
    alloc_tensor(3, 2, dims2);  /* A: 2x2 */
    alloc_tensor(4, 2, dims2);  /* B: 2x2 */
    alloc_tensor(5, 2, dims2);  /* C: 2x2 */

    tensor_data[3][0] = 1 * SCALE;
    tensor_data[3][1] = 2 * SCALE;
    tensor_data[3][2] = 3 * SCALE;
    tensor_data[3][3] = 4 * SCALE;

    tensor_data[4][0] = 5 * SCALE;
    tensor_data[4][1] = 6 * SCALE;
    tensor_data[4][2] = 7 * SCALE;
    tensor_data[4][3] = 8 * SCALE;

    op_matmul(5, 3, 4);
    printf("  [[1,2],[3,4]] @ [[5,6],[7,8]] = [[%d,%d],[%d,%d]]\n",
           tensor_data[5][0] / SCALE, tensor_data[5][1] / SCALE,
           tensor_data[5][2] / SCALE, tensor_data[5][3] / SCALE);
    printf("  (expected [[19,22],[43,50]])\n");

    /* Test Softmax */
    printf("\nSoftmax test:\n");
    dims1[0] = 4;
    alloc_tensor(6, 1, dims1);
    alloc_tensor(7, 1, dims1);

    tensor_data[6][0] = 1 * SCALE;
    tensor_data[6][1] = 2 * SCALE;
    tensor_data[6][2] = 3 * SCALE;
    tensor_data[6][3] = 4 * SCALE;

    op_softmax(7, 6);
    printf("  softmax([1,2,3,4]) = [%.3f, %.3f, %.3f, %.3f]\n",
           (float)tensor_data[7][0] / SCALE,
           (float)tensor_data[7][1] / SCALE,
           (float)tensor_data[7][2] / SCALE,
           (float)tensor_data[7][3] / SCALE);
    printf("  (expected [0.032, 0.087, 0.237, 0.644])\n");

    printf("\n=== Tests complete ===\n");
    return 0;
}

/* ============ V3 Subgraph Tests ============ */

int test_v3_subgraphs() {
    int sg;
    int *byte_oh;
    int *hi;
    int *lo;
    int *a_oh;
    int *b_oh;
    int *cin_oh;
    int *sum_out;
    int *cout_out;
    int *r_out;
    int *lo_out;
    int *hi_out;
    int *sg_in[3];
    int *sg_out[2];
    int in_sz[3];
    int out_sz[2];
    int i;
    int pass;
    int total;
    int got;
    int expected;

    pass = 0;
    total = 0;

    byte_oh = malloc(256 * sizeof(int));
    hi = malloc(16 * sizeof(int));
    lo = malloc(16 * sizeof(int));
    a_oh = malloc(16 * sizeof(int));
    b_oh = malloc(16 * sizeof(int));
    cin_oh = malloc(2 * sizeof(int));
    sum_out = malloc(16 * sizeof(int));
    cout_out = malloc(2 * sizeof(int));
    r_out = malloc(16 * sizeof(int));
    lo_out = malloc(16 * sizeof(int));
    hi_out = malloc(16 * sizeof(int));

    printf("\n=== V3 Subgraph Tests ===\n");

    /* Test b2n: byte 0xAB -> hi=0xA, lo=0xB */
    sg = find_subgraph("b2n");
    if (sg >= 0) {
        i = 0; while (i < 256) { byte_oh[i] = 0; i = i + 1; } byte_oh[0xAB] = SCALE;
        sg_in[0] = byte_oh; in_sz[0] = 256;
        sg_out[0] = hi; sg_out[1] = lo;
        out_sz[0] = 16; out_sz[1] = 16;
        run_subgraph(sg, sg_in, sg_out, in_sz, out_sz);

        got = 0; i = 1; while (i < 16) { if (hi[i] > hi[got]) got = i; i = i + 1; }
        total++; if (got == 0xA) pass++; else printf("  FAIL b2n(0xAB).hi: got %d expected 10\n", got);
        got = 0; i = 1; while (i < 16) { if (lo[i] > lo[got]) got = i; i = i + 1; }
        total++; if (got == 0xB) pass++; else printf("  FAIL b2n(0xAB).lo: got %d expected 11\n", got);
        printf("  b2n: %d/%d\n", pass, total);
    } else {
        printf("  b2n: SKIP (not found)\n");
    }

    /* Test n2b: hi=0xA, lo=0xB -> byte=0xAB */
    sg = find_subgraph("n2b");
    if (sg >= 0) {
        i = 0; while (i < 16) { a_oh[i] = 0; i = i + 1; } a_oh[0xA] = SCALE;
        i = 0; while (i < 16) { b_oh[i] = 0; i = i + 1; } b_oh[0xB] = SCALE;
        sg_in[0] = a_oh; sg_in[1] = b_oh;
        in_sz[0] = 16; in_sz[1] = 16;
        sg_out[0] = byte_oh;
        out_sz[0] = 256;
        run_subgraph(sg, sg_in, sg_out, in_sz, out_sz);
        got = 0; i = 1; while (i < 256) { if (byte_oh[i] > byte_oh[got]) got = i; i = i + 1; }
        total++; if (got == 0xAB) pass++; else printf("  FAIL n2b(A,B): got %d expected 171\n", got);
        printf("  n2b: 1/1\n");
    } else {
        printf("  n2b: SKIP (not found)\n");
    }

    /* Test nib_add: 8+8+0 = sum=0, cout=1 */
    sg = find_subgraph("nib_add");
    if (sg >= 0) {
        i = 0; while (i < 16) { a_oh[i] = 0; i = i + 1; } a_oh[8] = SCALE;
        i = 0; while (i < 16) { b_oh[i] = 0; i = i + 1; } b_oh[8] = SCALE;
        i = 0; while (i < 2) { cin_oh[i] = 0; i = i + 1; } cin_oh[0] = SCALE;
        sg_in[0] = a_oh; sg_in[1] = b_oh; sg_in[2] = cin_oh;
        in_sz[0] = 16; in_sz[1] = 16; in_sz[2] = 2;
        sg_out[0] = sum_out; sg_out[1] = cout_out;
        out_sz[0] = 16; out_sz[1] = 2;
        run_subgraph(sg, sg_in, sg_out, in_sz, out_sz);
        got = 0; i = 1; while (i < 16) { if (sum_out[i] > sum_out[got]) got = i; i = i + 1; }
        total++; if (got == 0) pass++; else printf("  FAIL nib_add(8,8,0).sum: got %d expected 0\n", got);
        got = 0; i = 1; while (i < 2) { if (cout_out[i] > cout_out[got]) got = i; i = i + 1; }
        total++; if (got == 1) pass++; else printf("  FAIL nib_add(8,8,0).cout: got %d expected 1\n", got);
        printf("  nib_add: 2/2\n");
    } else {
        printf("  nib_add: SKIP (not found)\n");
    }

    /* Test nib_xor: 0xF ^ 0xA = 5 */
    sg = find_subgraph("nib_xor");
    if (sg >= 0) {
        i = 0; while (i < 16) { a_oh[i] = 0; i = i + 1; } a_oh[0xF] = SCALE;
        i = 0; while (i < 16) { b_oh[i] = 0; i = i + 1; } b_oh[0xA] = SCALE;
        sg_in[0] = a_oh; sg_in[1] = b_oh;
        in_sz[0] = 16; in_sz[1] = 16;
        sg_out[0] = r_out;
        out_sz[0] = 16;
        run_subgraph(sg, sg_in, sg_out, in_sz, out_sz);
        got = 0; i = 1; while (i < 16) { if (r_out[i] > r_out[got]) got = i; i = i + 1; }
        total++; if (got == 5) pass++; else printf("  FAIL nib_xor(F,A): got %d expected 5\n", got);
        printf("  nib_xor: 1/1\n");
    } else {
        printf("  nib_xor: SKIP (not found)\n");
    }

    /* Test nib_mul: 3*4 -> lo=12, hi=0 */
    sg = find_subgraph("nib_mul");
    if (sg >= 0) {
        i = 0; while (i < 16) { a_oh[i] = 0; i = i + 1; } a_oh[3] = SCALE;
        i = 0; while (i < 16) { b_oh[i] = 0; i = i + 1; } b_oh[4] = SCALE;
        sg_in[0] = a_oh; sg_in[1] = b_oh;
        in_sz[0] = 16; in_sz[1] = 16;
        sg_out[0] = lo_out; sg_out[1] = hi_out;
        out_sz[0] = 16; out_sz[1] = 16;
        run_subgraph(sg, sg_in, sg_out, in_sz, out_sz);
        got = 0; i = 1; while (i < 16) { if (lo_out[i] > lo_out[got]) got = i; i = i + 1; }
        total++; if (got == 12) pass++; else printf("  FAIL nib_mul(3,4).lo: got %d expected 12\n", got);
        got = 0; i = 1; while (i < 16) { if (hi_out[i] > hi_out[got]) got = i; i = i + 1; }
        total++; if (got == 0) pass++; else printf("  FAIL nib_mul(3,4).hi: got %d expected 0\n", got);
        printf("  nib_mul: 2/2\n");
    } else {
        printf("  nib_mul: SKIP (not found)\n");
    }

    printf("\nTotal: %d/%d", pass, total);
    if (pass == total) {
        printf(" ALL PASSED\n");
    } else {
        printf(" SOME FAILED\n");
    }

    free(byte_oh); free(hi); free(lo);
    free(a_oh); free(b_oh); free(cin_oh);
    free(sum_out); free(cout_out); free(r_out);
    free(lo_out); free(hi_out);

    return pass == total ? 0 : 1;
}

/* ============ Main ============ */

int main(int argc, char **argv) {
    init_fp();
    init_ops();
    init_tensors();
    init_nodes();
    init_subgraphs();

    if (argc > 1) {
        /* Load and run model */
        if (load_model(argv[1]) == 0) {
            if (num_subgraphs > 0) {
                /* v3: run subgraph tests */
                return test_v3_subgraphs();
            } else {
                /* v1/v2: run top-level nodes */
                run_model();
                printf("Model execution complete\n");
            }
        }
    } else {
        /* Run tests */
        test_ops();
    }

    return 0;
}
