"""
Autoregressive VM Runner - generation loop and compatibility boundary.

The core model is a decoder-only transformer (`AutoregressiveVM`). This file
is the thin runtime around that model: it builds the prefix context, performs
the standard autoregressive generation loop, and handles explicit external I/O.

Purity notes:
  - `pure_attention_memory=True` is the strict mode. In that mode, runner-side
    VM-memory fallbacks are blocked and reported via `get_pure_attention_report()`.
  - Tool/I/O boundary handlers (`OPEN/READ/CLOS/PRTF/GETCHAR/PUTCHAR`) are
    intentionally external.
  - Anything else in this file that mutates VM state is transitional
    compatibility/debugging scaffolding while full attention-memory execution is
    being completed.

IO strategy:
  PUTCHAR — Fully autoregressive. The model routes AX -> OUTPUT -> byte logits;
            the runner only reads generated bytes.

  GETCHAR — Runner-side injection. The runner reads stdin and overwrites AX in
            the just-completed step. This is an explicit external boundary, not
            part of the pure transformer.
"""

import os
import torch
import warnings
from typing import List, Optional, Callable, Any, Dict
from dataclasses import dataclass, field

from .vm_step import AutoregressiveVM, Token
from .weight_setter import set_weights
from .embedding import Opcode
from .constants import INSTR_WIDTH, PC_OFFSET

# Opcodes that emit TOOL_CALL instead of STEP_END when tool calling is enabled.
# When model emits STEP_END for these (weights not set, or enable_tool_calling=False),
# runner still dispatches at STEP_END (backward compatible).
_TOOL_CALL_OPS = {
    Opcode.PRTF,
    Opcode.OPEN,
    Opcode.READ,
    Opcode.CLOS,
}

# Runner-side fallback ops (blocked in pure_attention_memory mode).
# These mutate/consult shadow memory or apply runner semantic corrections.
# SI/SC removed: _track_memory_write handles shadow updates from MEM tokens.
# LI/LC removed: L15 softmax1 memory lookup produces correct AX values
# when MEM sections are retained in context and MEM_STORE is injected.
_RUNNER_VM_MEMORY_OPS = {
    # Opcode.ADJ,  # Now works fully neurally via L7/L8/L9/L6!
    # Opcode.MALC,  # Now implemented in C4 stdlib (src/stdlib/memory.c4)
    # Opcode.FREE,  # Now implemented in C4 stdlib (src/stdlib/memory.c4)
    # Opcode.MSET,  # Now implemented in C4 stdlib (src/stdlib/memory.c4)
    # Opcode.MCMP,  # Now implemented in C4 stdlib (src/stdlib/memory.c4)
}

# Ops that write runner shadow memory through _track_memory_write.
# SI/SC: no longer blocked in pure_attention_memory mode — tracking always runs
# since other handlers (LI/LC, MALC, etc.) still read from _memory.
_RUNNER_TRACKED_MEMORY_OPS = {Opcode.ENT, Opcode.JSR}

# Store ops whose MEM sections are retained in context for L15 memory lookup.
_MEM_STORE_OPS = {Opcode.SI, Opcode.SC, Opcode.PSH, Opcode.ENT, Opcode.JSR}

_OPCODE_NAME = {
    v: k for k, v in vars(Opcode).items() if k.isupper() and isinstance(v, int)
}

# Binary ops that pop one operand from stack (SP += 8).
# Model handles byte-0 in weights; runner corrects multi-byte carry.
_BINARY_POP_OPS = {
    Opcode.ADD,
    Opcode.SUB,
    Opcode.MUL,
    Opcode.DIV,
    Opcode.MOD,
    Opcode.EQ,
    Opcode.NE,
    Opcode.LT,
    Opcode.GT,
    Opcode.LE,
    Opcode.GE,
    Opcode.OR,
    Opcode.XOR,
    Opcode.AND,
    Opcode.SHL,
    Opcode.SHR,
    Opcode.SI,
    Opcode.SC,
}

_NEURAL_32BIT_OPS = {
    Opcode.ADD,
    Opcode.SUB,
    Opcode.OR,
    Opcode.XOR,
    Opcode.AND,
}

_RUNNER_ALU_OPS = _BINARY_POP_OPS - _NEURAL_32BIT_OPS - {Opcode.SI, Opcode.SC}


@dataclass
class ToolCall:
    """A tool call request from the VM to an external handler."""

    call_type: str  # "printf", "open", "read", "close"
    call_id: int
    params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ToolResponse:
    """Response from external handler back to the VM."""

    call_id: int
    success: bool
    result: Any = None


class AutoregressiveVMRunner:
    """Generation loop for the autoregressive VM.

    Analogous to an LLM inference loop:
    - Build context (system prompt): bytecode + data + argv as tokens
    - Generate tokens autoregressively (model forward + greedy decode)
    - Detect I/O boundary (output bytes, halt)

    Supports two I/O modes:
    1. Legacy mode (conversational_io=False): Python handlers for I/O syscalls
    2. Conversational mode (conversational_io=True): Truly autoregressive I/O
       - Output: Model generates </thinking>, output text, <thinking>
       - Input: Model extracts from <user_input> tags in context
       - All I/O is part of the token stream (100% autoregressive)
    """

    def __init__(
        self,
        d_model=512,
        n_layers=17,  # Updated from 16 for LEV Phase 3 (L16 routing layer)
        n_heads=8,
        ffn_hidden=4096,
        max_seq_len=4096,
        pure_attention_memory=False,
        conversational_io=False,
        debug_ent_lev=False,
        debug_memory=False,
        use_kv_cache=True,
        max_mem_history=64,
    ):
        self.model = AutoregressiveVM(
            d_model=d_model,
            n_layers=n_layers,
            n_heads=n_heads,
            ffn_hidden=ffn_hidden,
            max_seq_len=max_seq_len,
        )
        # Load hand-crafted transformer weights for VM execution
        set_weights(self.model, enable_conversational_io=conversational_io)

        # Move model to GPU if available for ~20-100x speedup
        if torch.cuda.is_available():
            self.model = self.model.cuda()

        self.model.eval()

        # Syscall dispatch table
        # NOTE ON PURITY:
        # - Tool boundary handlers (OPEN/READ/CLOS/PRTF/GETCHAR/PUTCHAR) are
        #   intentionally external.
        # - VM semantic handlers below are transitional fallbacks for bring-up
        #   and debugging. In pure_attention_memory mode, these paths are
        #   blocked so execution depends on transformer/autoregressive behavior.
        self._syscall_handlers = {
            Opcode.CLOS: self._syscall_clos,
            Opcode.OPEN: self._syscall_open,
            Opcode.READ: self._syscall_read,
            Opcode.PRTF: self._syscall_prtf,
        }

        # File descriptor tracking
        self._open_fds = {}  # fd → name

        # Bump allocator state
        self._heap_base = 0x10000  # Start of heap

        # Conversational I/O mode flag
        # When True, I/O operations are handled autoregressively:
        # - Output (printf/putchar): Model generates THINKING_END, output text, THINKING_START
        # - Input (read/getchar): Model extracts from USER_INPUT section in context
        # When False, I/O operations use Python handlers (legacy mode)
        self.conversational_io = conversational_io
        self._heap_ptr = 0x10000  # Current allocation pointer
        self._alloc_sizes = {}  # addr → size (for FREE zero-fill)

        # Shadow memory: sparse dict tracking all stores (PSH, SI, SC, etc.)
        # Enables runner-side syscalls to read stack arguments beyond STACK0.
        # All entries are byte-granularity (addr → uint8).
        self._memory = {}  # addr → byte value

        # SP tracking for multi-byte correctness (PSH/ADJ handlers use this)
        self._last_sp = 0

        # PC tracking for exec_pc computation (function-call dispatch)
        self._last_pc = None

        # BP tracking for ENT/LEV handlers
        self._last_bp = 0

        # AX tracking for multi-byte preservation across steps.
        # Weights carry byte 0 only; runner re-applies bytes 1-3 each step.
        self._last_ax = 0

        # Debug flags
        self._debug_ent = debug_ent_lev
        self._debug_lev = debug_ent_lev
        self._debug_memory = debug_memory

        # KV cache parameters for memory history eviction
        # When use_kv_cache=True, _mem_history tracks unique memory addresses accessed
        # and evicts oldest entries when exceeding max_mem_history (LRU eviction)
        self.use_kv_cache = use_kv_cache
        self.max_mem_history = max_mem_history
        self._mem_history = {}  # addr → token sequence for memory value
        self._mem_access_order = []  # LRU tracking: most recent at end

        self._func_call_handlers = {}

        # If True: disable runner VM-memory emulation paths and only allow
        # explicit external tool boundary handling.
        self.pure_attention_memory = pure_attention_memory
        self._pure_attention_report = {}

    def run(
        self,
        bytecode,
        data=b"",
        argv=None,
        stdin="",
        max_steps=100000,
        tool_handler=None,
    ):
        """Run a program via autoregressive generation.

        Args:
            bytecode: List of packed instructions (op | imm<<8)
            data: Data section bytes
            argv: List of argument strings
            stdin: Input string
            max_steps: Maximum VM steps (each step = 39 tokens)
            tool_handler: Optional callback(ToolCall) -> ToolResponse for I/O

        Returns:
            (output_string, exit_code) tuple
        """
        self._bytecode = bytecode
        self._stdin_buffer = list(stdin) if stdin else []
        self._stdin_pos = 0
        self._tool_handler = tool_handler
        self._tool_call_id = 0
        self._last_pc = None
        self._last_bp = 0x10000  # Initial BP (same as model embedding STACK_INIT)
        self._last_sp = 0x10000  # Initial SP (same as model embedding STACK_INIT)
        self._mem_history = {}  # addr → 9-token MEM section (latest wins)
        self._mem_access_order = []  # LRU tracking: most recent at end
        self.model.embed.set_mem_history_end(0)  # reset stale boundary from prior runs
        self._pure_attention_report = {
            "enabled": bool(self.pure_attention_memory),
            "blocked_vm_memory_ops": {},
            "blocked_track_memory_ops": {},
            "external_tool_ops": {},
            "halted": False,
        }

        # Load data section into shadow memory at 0x10000
        # C4 compiler uses data_base = 0x10000 (src/compiler.py:339)
        data = data or b""
        if isinstance(data, (bytes, bytearray)):
            for i, b in enumerate(data):
                self._memory[0x10000 + i] = b
        elif isinstance(data, list):
            for i, b in enumerate(data):
                self._memory[0x10000 + i] = b

        # Set heap base past end of data section, aligned to 8
        data_end = 0x10000 + len(data)
        self._heap_base = (data_end + 7) & ~7
        self._heap_ptr = self._heap_base

        context = self._build_context(bytecode, data, argv or [], stdin)
        prefix_len = len(context)  # code + data prefix length (immutable)
        output = []

        # Set initial opcode for MoE routing (first instruction)
        init_exec = self._exec_pc() // INSTR_WIDTH
        if 0 <= init_exec < len(bytecode):
            opcode = bytecode[init_exec] & 0xFF
            self.model.set_active_opcode(opcode)

        step_num = 0  # Track VM steps for conversational I/O handling

        # Context windowing prevents O(n²) blowup while preserving CODE section.
        # The CODE section (bytecode) is needed for L5 fetch heads to read instructions.
        # Keep prefix (CODE + DATA) + last 512 tokens of dynamic content (MEM + steps).
        for i in range(max_steps * Token.STEP_TOKENS):
            # Apply context windowing preserving prefix (CODE/DATA sections)
            # Without prefix, model can't attend to bytecode for instruction fetch
            if len(context) > prefix_len + 512:
                generation_context = context[:prefix_len] + context[-512:]
            else:
                generation_context = context
            next_token = self.model.generate_next(generation_context, use_incremental=False)
            context.append(next_token)

            pos_in_step = i % Token.STEP_TOKENS
            if pos_in_step == Token.STEP_TOKENS - 1 and next_token not in (Token.STEP_END, Token.HALT, Token.TOOL_CALL):
                context[-1] = Token.STEP_END
                next_token = Token.STEP_END

            # Debug: Print step progress
            if self._debug_ent or self._debug_lev:
                if i % 35 == 0:  # Every step
                    pc = self._extract_register(context, Token.REG_PC) if len(context) > 20 else None
                    ax = self._extract_register(context, Token.REG_AX) if len(context) > 20 else None
                    pc_val = pc if pc is not None else 0
                    ax_val = ax if ax is not None else 0
                    print(f"[STEP {i//35}] token {i}/{max_steps * Token.STEP_TOKENS}, PC=0x{pc_val:08x}, AX=0x{ax_val:08x}", flush=True)

            # Hybrid conversational I/O: handle THINKING_END
            if self.conversational_io and next_token == Token.THINKING_END:
                exec_pc = self._exec_pc()
                # Extract format string pointer from STACK0 (model output)
                fmt_ptr = self._extract_register(context, Token.STACK0)
                # FALLBACK: If model outputs 0, read from shadow memory at SP
                # The format string pointer was pushed to stack before PRTF
                if not fmt_ptr:
                    fmt_ptr = self._mem_load_word(self._last_sp)
                    print(f"[HYBRID] Format ptr from shadow memory at SP=0x{self._last_sp:08x}: 0x{fmt_ptr:08x}")
                else:
                    print(f"[HYBRID] Format string pointer: 0x{fmt_ptr:08x}")
                if fmt_ptr:
                    # Read format string from memory
                    fmt_str = []
                    addr = fmt_ptr
                    while len(fmt_str) < 256:  # Safety limit
                        byte_val = self._memory.get(addr, 0)
                        if byte_val == 0:  # Null terminator
                            break
                        fmt_str.append(byte_val)
                        addr += 1

                    # Emit output bytes (literal string for now, no format specifiers)
                    print(f"[HYBRID] Format string: {bytes(fmt_str)}")
                    for byte_val in fmt_str:
                        context.append(byte_val)
                        output.append(chr(byte_val))  # Convert to char for output buffer

                    # Emit THINKING_START to resume execution
                    context.append(Token.THINKING_START)

                    # Calculate post-PRTF state:
                    # - PC advances to next instruction
                    # - SP pops the format string pointer argument
                    new_pc = exec_pc + INSTR_WIDTH
                    new_sp = (self._last_sp + 8) & 0xFFFFFFFF
                    stack0_val = self._mem_load_word(new_sp) if new_sp else 0

                    # Inject synthetic step with correct state
                    self._inject_synthetic_step(
                        context, new_pc, self._last_ax, new_sp, self._last_bp, stack0_val
                    )

                    # Update runner state
                    self._last_pc = new_pc
                    self._last_sp = new_sp

                    print(f"[HYBRID] Emitted {len(fmt_str)} bytes + THINKING_START + synthetic step (PC=0x{new_pc:04x}, SP=0x{new_sp:08x})")
                continue

            if next_token == Token.STEP_END:
                if step_num < 3:
                    step_num += 1  # Increment step counter
                # Extract PC and identify opcodes
                op = None
                instr_idx = None
                if step_num <= 3:
                    exec_pc = self._exec_pc()  # PC being executed this step
                if step_num <= 3:
                    pc = self._extract_register(context, Token.REG_PC)  # Next PC from output
                if step_num <= 3:
                    # Get opcode being executed this step
                    exec_idx = exec_pc // INSTR_WIDTH
                    exec_op = None
                    exec_opname = "?"
                    if 0 <= exec_idx < len(bytecode):
                        exec_op = bytecode[exec_idx] & 0xFF
                        # Find opcode name
                        for name in dir(Opcode):
                            if not name.startswith('_') and getattr(Opcode, name) == exec_op:
                                exec_opname = name
                                break

                # BUG FIX 2026-04-16: Dispatch func_call_handlers BEFORE syscall_handlers.
                # func_call_handlers process the CURRENT instruction (exec_pc) and set
                # _last_ax correctly. syscall_handlers process the NEXT instruction (output pc)
                # and may read _last_ax. If syscall runs first, _last_ax gets clobbered.
                # Example: PSH step - handler should set STACK0=_last_ax, but _syscall_prtf
                # (for next instruction) was running first and setting _last_ax=0.

                exec_idx = self._exec_pc() // INSTR_WIDTH
                if self._dispatch_step(context, bytecode, exec_idx, prefix_len, output):
                    break

            elif next_token == Token.TOOL_CALL:
                pc = self._extract_register(context, Token.REG_PC)
                if pc is not None:
                    instr_idx = pc // INSTR_WIDTH
                    if 0 <= instr_idx < len(bytecode):
                        op = bytecode[instr_idx] & 0xFF
                        handler = self._syscall_handlers.get(op)
                        if handler:
                            if not self._should_block_vm_memory_handler(op):
                                handler(context, output)
                                if op in _TOOL_CALL_OPS:
                                    self._record_pure_attention("external_tool_ops", op)
                        if not self._should_block_track_memory(op):
                            self._track_memory_write(context, op)

                exec_idx = self._exec_pc() // INSTR_WIDTH
                if self._dispatch_step(context, bytecode, exec_idx, prefix_len, output):
                    break

            # Halt detection
            if next_token == Token.HALT:
                # Preserve final AX value before exiting
                # Use full _last_ax value (not byte merge) because it's the canonical value
                self._override_register_in_last_step(context, Token.REG_AX, self._last_ax)
                self._pure_attention_report["halted"] = True
                break

        return "".join(output), self._decode_exit_code(context)

    def get_pure_attention_report(self):
        """Return diagnostics for pure-attention-memory mode."""
        return dict(self._pure_attention_report)

    def _should_block_vm_memory_handler(self, op):
        return self.pure_attention_memory and op in _RUNNER_VM_MEMORY_OPS

    def _should_block_track_memory(self, op):
        return self.pure_attention_memory and op in _RUNNER_TRACKED_MEMORY_OPS

    def _record_pure_attention(self, bucket, op):
        if not self.pure_attention_memory:
            return
        name = _OPCODE_NAME.get(op, str(op))
        slot = self._pure_attention_report[bucket]
        slot[name] = slot.get(name, 0) + 1

    def _compute_alu(self, op, stack_val, ax_val):
        if op == Opcode.ADD:
            return (stack_val + ax_val) & 0xFFFFFFFF
        elif op == Opcode.SUB:
            return (stack_val - ax_val) & 0xFFFFFFFF
        elif op == Opcode.MUL:
            return (stack_val * ax_val) & 0xFFFFFFFF
        elif op == Opcode.DIV:
            return (stack_val // ax_val) if ax_val else 0
        elif op == Opcode.MOD:
            return (stack_val % ax_val) if ax_val else 0
        elif op == Opcode.OR:
            return stack_val | ax_val
        elif op == Opcode.XOR:
            return stack_val ^ ax_val
        elif op == Opcode.AND:
            return stack_val & ax_val
        elif op == Opcode.SHL:
            return (stack_val << ax_val) & 0xFFFFFFFF
        elif op == Opcode.SHR:
            return (stack_val >> ax_val) & 0xFFFFFFFF if ax_val < 32 else 0
        elif op == Opcode.EQ:
            return 1 if stack_val == ax_val else 0
        elif op == Opcode.NE:
            return 1 if stack_val != ax_val else 0
        elif op == Opcode.LT:
            sx_s = stack_val - 0x1000000 if stack_val >= 0x800000 else stack_val
            sx_a = ax_val - 0x1000000 if ax_val >= 0x800000 else ax_val
            return 1 if sx_s < sx_a else 0
        elif op == Opcode.GT:
            sx_s = stack_val - 0x1000000 if stack_val >= 0x800000 else stack_val
            sx_a = ax_val - 0x1000000 if ax_val >= 0x800000 else ax_val
            return 1 if sx_s > sx_a else 0
        elif op == Opcode.LE:
            sx_s = stack_val - 0x1000000 if stack_val >= 0x800000 else stack_val
            sx_a = ax_val - 0x1000000 if ax_val >= 0x800000 else ax_val
            return 1 if sx_s <= sx_a else 0
        elif op == Opcode.GE:
            sx_s = stack_val - 0x1000000 if stack_val >= 0x800000 else stack_val
            sx_a = ax_val - 0x1000000 if ax_val >= 0x800000 else ax_val
            return 1 if sx_s >= sx_a else 0
        return 0

    def _signed_imm(self, instr):
        imm = instr >> 8
        if imm >= 0x800000:
            imm -= 0x1000000
        return imm

    def _dispatch_step(self, context, bytecode, exec_idx, prefix_len, output):
        exec_op = bytecode[exec_idx] & 0xFF if 0 <= exec_idx < len(bytecode) else None
        if exec_op is None:
            return False

        pc = self._extract_register(context, Token.REG_PC)
        op = None
        if pc is not None:
            instr_idx = pc // INSTR_WIDTH
            if 0 <= instr_idx < len(bytecode):
                op = bytecode[instr_idx] & 0xFF
                handler = self._syscall_handlers.get(op)
                if handler:
                    if self._should_block_vm_memory_handler(op):
                        self._record_pure_attention("blocked_vm_memory_ops", op)
                    else:
                        handler(context, output)
                        if op in _TOOL_CALL_OPS:
                            self._record_pure_attention("external_tool_ops", op)
                if self._should_block_track_memory(op):
                    self._record_pure_attention("blocked_track_memory_ops", op)
                else:
                    self._track_memory_write(context, op)

        func_handler = self._func_call_handlers.get(exec_op)
        if func_handler:
            func_handler(context, output)

        opcodes_with_pc_handling = {Opcode.JMP, Opcode.BZ, Opcode.BNZ, Opcode.EXIT,
                                    Opcode.LEV, Opcode.ENT, Opcode.JSR}
        opcodes_with_pc_handling.update(self._func_call_handlers.keys())
        if exec_op not in opcodes_with_pc_handling:
            next_pc = (self._exec_pc() + INSTR_WIDTH) & 0xFFFFFFFF
            self._override_register_in_last_step(context, Token.REG_PC, next_pc)

        if exec_op not in {Opcode.ENT, Opcode.LEV}:
            self._override_register_in_last_step(context, Token.REG_BP, self._last_bp)

        if 0 <= exec_idx < len(bytecode):
            if exec_op == Opcode.PSH:
                self._last_sp = (self._last_sp - 8) & 0xFFFFFFFF
                self._inject_mem_section(self._last_sp, self._last_ax)
                self._mem_store_word(self._last_sp, self._last_ax)
                self._override_register_in_last_step(context, Token.REG_SP, self._last_sp)
                self._override_register_in_last_step(context, Token.STACK0, self._last_ax)
            elif exec_op == Opcode.JSR:
                self._last_sp = (self._last_sp - 8) & 0xFFFFFFFF
                return_addr = (self._exec_pc() + INSTR_WIDTH) & 0xFFFFFFFF
                self._inject_mem_section(self._last_sp, return_addr)
                self._mem_store_word(self._last_sp, return_addr)
                self._override_register_in_last_step(context, Token.REG_SP, self._last_sp)
                self._override_register_in_last_step(context, Token.STACK0, return_addr)
                jsr_target_idx = bytecode[exec_idx] >> 8
                jsr_target_pc = self._resolve_target_pc(jsr_target_idx)
                self._last_pc = jsr_target_pc
                self._override_register_in_last_step(context, Token.REG_PC, jsr_target_pc)
            elif exec_op == Opcode.ENT:
                self._last_sp = (self._last_sp - 8) & 0xFFFFFFFF
                self._inject_mem_section(self._last_sp, self._last_bp)
                self._mem_store_word(self._last_sp, self._last_bp)
                self._last_bp = self._last_sp
                self._override_register_in_last_step(context, Token.REG_BP, self._last_bp)
                imm = bytecode[exec_idx] >> 8
                if imm >= 0x800000:
                    imm -= 0x1000000
                self._last_sp = (self._last_bp + imm * 4) & 0xFFFFFFFF
                self._override_register_in_last_step(context, Token.REG_SP, self._last_sp)
                self._last_pc = (self._exec_pc() + INSTR_WIDTH) & 0xFFFFFFFF
                self._override_register_in_last_step(context, Token.REG_PC, self._last_pc)
            elif exec_op == Opcode.LEV:
                saved_bp = self._mem_load_word(self._last_bp) if self._last_bp else 0
                return_addr = self._mem_load_word(self._last_bp + 8) if self._last_bp else 0
                if saved_bp:
                    self._last_bp = saved_bp
                    self._override_register_in_last_step(context, Token.REG_BP, saved_bp)
                if return_addr:
                    self._last_pc = return_addr
                    self._override_register_in_last_step(context, Token.REG_PC, return_addr)
                self._last_sp = (self._last_bp + 16) & 0xFFFFFFFF
                self._override_register_in_last_step(context, Token.REG_SP, self._last_sp)
            elif exec_op == Opcode.JMP:
                target_idx = bytecode[exec_idx] >> 8
                target_pc = self._resolve_target_pc(target_idx)
                self._last_pc = target_pc
                self._override_register_in_last_step(context, Token.REG_PC, target_pc)
            elif exec_op == Opcode.BZ:
                target_idx = bytecode[exec_idx] >> 8
                target_pc = self._resolve_target_pc(target_idx)
                if self._last_ax == 0:
                    self._last_pc = target_pc
                    self._override_register_in_last_step(context, Token.REG_PC, target_pc)
                else:
                    self._last_pc = (self._exec_pc() + INSTR_WIDTH) & 0xFFFFFFFF
                    self._override_register_in_last_step(context, Token.REG_PC, self._last_pc)
            elif exec_op == Opcode.BNZ:
                target_idx = bytecode[exec_idx] >> 8
                target_pc = self._resolve_target_pc(target_idx)
                if self._last_ax != 0:
                    self._last_pc = target_pc
                    self._override_register_in_last_step(context, Token.REG_PC, target_pc)
                else:
                    self._last_pc = (self._exec_pc() + INSTR_WIDTH) & 0xFFFFFFFF
                    self._override_register_in_last_step(context, Token.REG_PC, self._last_pc)
            elif exec_op == Opcode.ADJ:
                instr = bytecode[exec_idx]
                imm = instr >> 8
                if imm >= 0x800000:
                    imm -= 0x1000000
                self._last_sp = (self._last_sp + imm) & 0xFFFFFFFF
                self._override_register_in_last_step(context, Token.REG_SP, self._last_sp)
            elif exec_op in _BINARY_POP_OPS:
                stack_val = self._mem_load_word(self._last_sp) if self._last_sp else 0
                alu_result = self._compute_alu(exec_op, stack_val, self._last_ax)
                self._last_sp = (self._last_sp + 8) & 0xFFFFFFFF
                self._last_ax = alu_result
                self._override_register_in_last_step(context, Token.REG_SP, self._last_sp)
                self._override_register_in_last_step(context, Token.REG_AX, alu_result)
            elif exec_op == Opcode.LI:
                addr = self._last_ax
                val = self._mem_load_word(addr)
                self._last_ax = val
                self._override_register_in_last_step(context, Token.REG_AX, val)
            elif exec_op == Opcode.LC:
                addr = self._last_ax
                val = self._memory.get(addr, 0)
                self._last_ax = val
                self._override_register_in_last_step(context, Token.REG_AX, val)
            elif exec_op == Opcode.SI:
                addr = self._mem_load_word(self._last_sp) if self._last_sp else 0
                self._last_sp = (self._last_sp + 8) & 0xFFFFFFFF
                self._mem_store_word(addr, self._last_ax)
                self._inject_mem_section(addr, self._last_ax)
                self._override_register_in_last_step(context, Token.REG_SP, self._last_sp)
            elif exec_op == Opcode.SC:
                addr = self._mem_load_word(self._last_sp) if self._last_sp else 0
                self._last_sp = (self._last_sp + 8) & 0xFFFFFFFF
                self._memory[addr] = self._last_ax & 0xFF
                self._override_register_in_last_step(context, Token.REG_SP, self._last_sp)
            elif exec_op not in (Opcode.IMM, Opcode.LEA, Opcode.JMP, Opcode.BZ, Opcode.BNZ,
                                 Opcode.LI, Opcode.LC, Opcode.EXIT, Opcode.NOP):
                sp_model = self._extract_register(context, Token.REG_SP)
                if sp_model is not None:
                    self._last_sp = sp_model

            if exec_op not in (Opcode.PSH, Opcode.JSR, Opcode.ENT, Opcode.LEV, Opcode.ADJ) and exec_op not in _BINARY_POP_OPS:
                stack0_val = self._mem_load_word(self._last_sp) if self._last_sp else 0
                self._override_register_in_last_step(context, Token.STACK0, stack0_val)

        ax = self._extract_register(context, Token.REG_AX)
        if ax is not None:
            AX_MODIFYING_OPS = {Opcode.IMM, Opcode.LEA,
                               Opcode.ADD, Opcode.SUB, Opcode.MUL, Opcode.DIV, Opcode.MOD,
                               Opcode.OR, Opcode.XOR, Opcode.AND, Opcode.SHL, Opcode.SHR}
            if exec_op == Opcode.IMM:
                exec_pc_imm = self._exec_pc()
                exec_idx_imm = exec_pc_imm // INSTR_WIDTH
                if 0 <= exec_idx_imm < len(bytecode):
                    instr = bytecode[exec_idx_imm]
                    imm = instr >> 8
                    if imm >= 0x800000:
                        imm -= 0x1000000
                    imm &= 0xFFFFFFFF
                    self._override_ax_in_last_step(context, imm)
            elif exec_op in AX_MODIFYING_OPS:
                if exec_op in _BINARY_POP_OPS:
                    pass
                elif exec_op == Opcode.LEA:
                    imm = bytecode[exec_idx] >> 8
                    if imm >= 0x800000:
                        imm -= 0x1000000
                    alu_result = (self._last_bp + imm) & 0xFFFFFFFF
                    self._last_ax = alu_result
                    self._override_register_in_last_step(context, Token.REG_AX, alu_result)
                else:
                    merged = (ax & 0xFF) | (self._last_ax & 0xFFFFFF00)
                    self._last_ax = merged
                    self._override_register_in_last_step(context, Token.REG_AX, merged)
            elif exec_op in (Opcode.PSH, Opcode.JSR, Opcode.ENT, Opcode.LEV,
                            Opcode.SI, Opcode.SC, Opcode.LI, Opcode.LC,
                            Opcode.JMP, Opcode.BZ, Opcode.BNZ, Opcode.EXIT,
                            Opcode.NOP, Opcode.ADJ):
                self._override_register_in_last_step(context, Token.REG_AX, self._last_ax)
            else:
                merged = (ax & 0xFF) | (self._last_ax & 0xFFFFFF00)
                self._last_ax = merged
                self._override_register_in_last_step(context, Token.REG_AX, merged)

        if exec_op not in (Opcode.ENT, Opcode.LEV, Opcode.JMP, Opcode.BZ, Opcode.BNZ, Opcode.JSR):
            pc = self._extract_register(context, Token.REG_PC)
            if pc is not None:
                self._last_pc = pc

        next_exec = self._exec_pc() // INSTR_WIDTH
        if 0 <= next_exec < len(bytecode):
            self.model.set_active_opcode(bytecode[next_exec] & 0xFF)
        else:
            self.model.set_active_opcode(None)

        if exec_op in _MEM_STORE_OPS and exec_op not in self._func_call_handlers:
            mem_section = self._extract_mem_section(context)
            if mem_section is not None:
                addr = sum((mem_section[1 + j] & 0xFF) << (j * 8) for j in range(4))
                self._track_mem_access(addr, mem_section)

        if exec_op == Opcode.EXIT:
            self._override_register_in_last_step(context, Token.REG_AX, self._last_ax)
            return True

        last_step = context[-(Token.STEP_TOKENS):]
        mem_flat = []
        for tokens in self._mem_history.values():
            mem_flat.extend(tokens)
        context[prefix_len:] = mem_flat + list(last_step)
        self.model.embed.set_mem_history_end(prefix_len + len(mem_flat))
        return False

    def _build_context(self, bytecode, data, argv, stdin=""):
        """Encode program as token sequence (context prefix).

        Format:
            [CODE_START] op0 imm0_b0..b3 pad0..2 op1 imm1_b0..b3 pad0..2 ... [CODE_END]
            [DATA_START] data_bytes... [DATA_END]
            [USER_INPUT_START] byte0 byte1 ... byteN [USER_INPUT_END]  (if stdin)
            argv0_chars... \\0 argv1_chars... \\0

        Each instruction is 8 tokens: opcode + 4 immediate bytes + 3 padding bytes.
        This matches INSTR_WIDTH from constants.py (5 data + 3 padding for 8-byte alignment).
        """
        from .constants import IMMEDIATE_SIZE, PADDING_SIZE

        tokens = [Token.CODE_START]

        for instr in bytecode:
            op = instr & 0xFF
            imm = instr >> 8
            tokens.append(op)
            for i in range(IMMEDIATE_SIZE):
                tokens.append((imm >> (i * 8)) & 0xFF)
            # Add padding bytes for 8-byte instruction alignment
            for _ in range(PADDING_SIZE):
                tokens.append(0)

        tokens.append(Token.CODE_END)
        tokens.append(Token.DATA_START)

        if isinstance(data, (bytes, bytearray)):
            tokens.extend(data)
        elif isinstance(data, list):
            tokens.extend(data)

        tokens.append(Token.DATA_END)

        # User input (stdin) as marked block
        if stdin:
            tokens.append(Token.USER_INPUT_START)
            tokens.extend(ord(c) for c in stdin)
            tokens.append(Token.USER_INPUT_END)

        if argv:
            for arg in argv:
                tokens.extend(ord(c) for c in arg)
                tokens.append(0)  # null terminator

        return tokens

    def _is_output_byte(self, context):
        """Detect if a PUTCHAR step just completed.

        Tracks PC and looks up the opcode in the original bytecode.
        """
        if len(context) < 2:
            return False
        if context[-1] != Token.STEP_END:
            return False
        pc = self._extract_register(context, Token.REG_PC)
        if pc is None:
            return False
        instr_idx = pc // INSTR_WIDTH
        if 0 <= instr_idx < len(self._bytecode):
            return (self._bytecode[instr_idx] & 0xFF) == Opcode.PUTCHAR
        return False

    def _extract_register(self, context, marker_token):
        """Extract 32-bit register value from the last completed step.

        Scans back from the end to find the marker token, then reads
        the 4 value bytes (little-endian).
        """
        scan_back = Token.STEP_TOKENS + 5  # step size + margin
        for i in range(len(context) - 1, max(0, len(context) - scan_back), -1):
            if context[i] == marker_token and i + 4 < len(context):
                val = 0
                for j in range(4):
                    val |= (context[i + 1 + j] & 0xFF) << (j * 8)
                return val
        return None

    def _extract_output_byte(self, context):
        """Extract output byte from the last completed step's AX register."""
        val = self._extract_register(context, Token.REG_AX)
        if val is not None:
            return chr(val & 0xFF)
        return None

    def _inject_getchar(self, context):
        """Runner-side GETCHAR: inject next stdin byte into context.

        This is NOT autoregressive — the runner directly overwrites the
        AX register bytes the model generated. The model has no mechanism
        to read from the stdin buffer in its weights.

        If stdin is exhausted, injects -1 (0xFFFFFFFF) for EOF.
        """
        if self._stdin_pos < len(self._stdin_buffer):
            byte_val = ord(self._stdin_buffer[self._stdin_pos])
            self._stdin_pos += 1
        else:
            byte_val = 0xFFFFFFFF  # EOF = -1

        self._override_ax_in_last_step(context, byte_val)

    def _override_ax_in_last_step(self, context, value):
        """Override AX register bytes in the last completed step.

        Scans back from STEP_END to find REG_AX marker and replaces
        the 4 value bytes with the given value (little-endian).
        Also updates _last_ax for multi-byte preservation across steps.
        """
        self._last_ax = value & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_AX, value)

    def _override_register_in_last_step(self, context, marker_token, value):
        """Override any register's bytes in the last completed step.

        Scans back to find the marker token and replaces
        the 4 value bytes with the given value (little-endian).
        """
        scan_back = Token.STEP_TOKENS + 5
        for i in range(len(context) - 1, max(0, len(context) - scan_back), -1):
            if context[i] == marker_token and i + 4 < len(context):
                for j in range(4):
                    context[i + 1 + j] = (value >> (j * 8)) & 0xFF
                return

    def _inject_synthetic_step(self, context, pc, ax, sp, bp, stack0=0):
        """Inject a complete synthetic step into context.

        Used after PRTF handling to resume execution with correct state.
        Format: [REG_PC, b0..b3, REG_AX, b0..b3, REG_SP, b0..b3,
                 REG_BP, b0..b3, STACK0, b0..b3, MEM, b0..b8, STEP_END]
        """
        # PC: 5 tokens
        context.append(Token.REG_PC)
        for i in range(4):
            context.append((pc >> (i * 8)) & 0xFF)
        # AX: 5 tokens
        context.append(Token.REG_AX)
        for i in range(4):
            context.append((ax >> (i * 8)) & 0xFF)
        # SP: 5 tokens
        context.append(Token.REG_SP)
        for i in range(4):
            context.append((sp >> (i * 8)) & 0xFF)
        # BP: 5 tokens
        context.append(Token.REG_BP)
        for i in range(4):
            context.append((bp >> (i * 8)) & 0xFF)
        # STACK0: 5 tokens
        context.append(Token.STACK0)
        for i in range(4):
            context.append((stack0 >> (i * 8)) & 0xFF)
        # MEM: 9 tokens (marker + 8 bytes, all zeros for no-op)
        context.append(Token.MEM)
        for _ in range(8):
            context.append(0)
        # STEP_END
        context.append(Token.STEP_END)

    def _extract_stack0(self, context):
        """Extract 32-bit STACK0 (*sp) value from the last completed step."""
        return self._extract_register(context, Token.STACK0)

    def _track_memory_write(self, context, op):
        """Track memory writes to maintain shadow memory state.

        Called after each step. Updates _memory dict for opcodes that
        store to memory. All store ops (PSH, SI, SC, ENT, JSR) now
        generate MEM section bytes via L14 attention heads.

        Extracts addr/value from MEM section for shadow memory tracking.
        """
        if op in (Opcode.PSH, Opcode.SI, Opcode.SC, Opcode.ENT, Opcode.JSR):
            addr, value = self._extract_mem_write(context)
            if addr is not None:
                if op == Opcode.SC:
                    # SC stores a single byte
                    self._memory[addr] = value & 0xFF
                else:
                    self._mem_store_word(addr, value)

    def _extract_mem_write(self, context):
        """Extract memory write (addr, value) from MEM section of last step."""
        scan_back = Token.STEP_TOKENS + 5
        for i in range(len(context) - 1, max(0, len(context) - scan_back), -1):
            if context[i] == Token.MEM and i + 8 < len(context):
                addr = 0
                for j in range(4):
                    addr |= (context[i + 1 + j] & 0xFF) << (j * 8)
                value = 0
                for j in range(4):
                    value |= (context[i + 5 + j] & 0xFF) << (j * 8)
                return addr, value
        return None, None

    def _extract_mem_section(self, context):
        """Extract 9-token MEM section [MEM, a0-3, v0-3] from last step."""
        scan_back = Token.STEP_TOKENS + 5
        for i in range(len(context) - 1, max(0, len(context) - scan_back), -1):
            if context[i] == Token.MEM and i + 8 < len(context):
                mem_section = list(context[i:i + 9])
                if self._debug_memory:
                    print(f"  [MEM EXTRACT] Found MEM at index {i}, section tokens: {mem_section}", flush=True)
                return mem_section
        return None

    def _mem_store_word(self, addr, value):
        """Store a 32-bit value as 4 little-endian bytes in shadow memory."""
        value = value & 0xFFFFFFFF
        for i in range(4):
            self._memory[addr + i] = (value >> (i * 8)) & 0xFF

    def _inject_mem_section(self, addr, value):
        """Inject a MEM section into _mem_history for L15 lookup.

        This bridges the gap between handler-corrected memory and neural L15:
        - Handlers know the correct addr/value (from tracking state)
        - L15 reads from MEM sections in context (which may have wrong neural output)
        - This injects a corrected MEM section so L15 can find the right data

        MEM section format: [MEM, a0, a1, a2, a3, v0, v1, v2, v3]
        """
        addr = addr & 0xFFFFFFFF
        value = value & 0xFFFFFFFF
        mem_section = [
            Token.MEM,
            (addr >> 0) & 0xFF,
            (addr >> 8) & 0xFF,
            (addr >> 16) & 0xFF,
            (addr >> 24) & 0xFF,
            (value >> 0) & 0xFF,
            (value >> 8) & 0xFF,
            (value >> 16) & 0xFF,
            (value >> 24) & 0xFF,
        ]
        self._track_mem_access(addr, mem_section)
        if self._debug_memory:
            print(f"  [MEM INJECT] addr=0x{addr:08x}, value=0x{value:08x}", flush=True)

    def _track_mem_access(self, addr, mem_section):
        """Track memory access with LRU eviction when exceeding max_mem_history.

        Args:
            addr: Memory address accessed
            mem_section: 9-token MEM section [Token.MEM, addr_bytes[4], value_bytes[4]]
        """
        # Update LRU order: remove if exists, then append to end (most recent)
        if addr in self._mem_access_order:
            self._mem_access_order.remove(addr)
        self._mem_access_order.append(addr)

        # Store the memory section
        self._mem_history[addr] = mem_section

        # LRU eviction: remove oldest entries if exceeding max_mem_history
        while len(self._mem_history) > self.max_mem_history and self.max_mem_history > 0:
            oldest_addr = self._mem_access_order.pop(0)
            if oldest_addr in self._mem_history:
                del self._mem_history[oldest_addr]

    def _mem_load_word(self, addr):
        """Load a 32-bit value from 4 little-endian bytes in shadow memory."""
        val = 0
        for i in range(4):
            val |= self._memory.get(addr + i, 0) << (i * 8)
        return val

    def _read_stack_arg(self, context, arg_index):
        """Read argument from stack by index.

        C4 pushes args left-to-right, so at syscall time:
          arg_index 0 = sp[0] = STACK0 (last pushed = last formal arg)
          arg_index 1 = sp[1] = memory[sp+8]
          arg_index 2 = sp[2] = memory[sp+16]

        For a C call f(a, b, c): push a, push b, push c, SYSCALL
          sp[0] = c, sp[1] = b, sp[2] = a
        """
        if arg_index == 0:
            return self._extract_stack0(context) or 0
        sp = self._extract_register(context, Token.REG_SP)
        if sp is None:
            return 0
        return self._mem_load_word(sp + arg_index * 8)

    # -----------------------------------------------------------------
    # Tool calling helpers
    # -----------------------------------------------------------------

    def _next_tool_call_id(self):
        """Return a monotonically increasing tool call ID."""
        self._tool_call_id += 1
        return self._tool_call_id

    def _read_string(self, ptr, max_len=4096):
        """Read null-terminated string from shadow memory.

        Args:
            ptr: Starting address in _memory
            max_len: Safety limit on string length

        Returns:
            The decoded string (empty string if ptr is 0 or invalid).
        """
        if ptr == 0:
            return ""
        chars = []
        for i in range(max_len):
            c = self._memory.get(ptr + i, 0)
            if c == 0:
                break
            chars.append(chr(c & 0xFF))
        return "".join(chars)

    def _format_printf(self, fmt, args):
        """Simple printf-style formatting.

        Supports: %d, %s, %c, %x, %%
        For %s args, resolves pointers via _read_string().

        Args:
            fmt: Format string
            args: List of integer arguments

        Returns:
            Formatted output string
        """
        result = []
        i = 0
        arg_idx = 0

        while i < len(fmt):
            if fmt[i] == "%" and i + 1 < len(fmt):
                spec = fmt[i + 1]
                arg = args[arg_idx] if arg_idx < len(args) else 0
                if spec == "d" or spec == "i":
                    # Signed interpretation
                    if arg >= 0x80000000:
                        arg = arg - 0x100000000
                    result.append(str(arg))
                    arg_idx += 1
                elif spec == "s":
                    result.append(self._read_string(arg))
                    arg_idx += 1
                elif spec == "c":
                    result.append(chr(arg & 0xFF))
                    arg_idx += 1
                elif spec == "x":
                    result.append(format(arg & 0xFFFFFFFF, "x"))
                    arg_idx += 1
                elif spec == "%":
                    result.append("%")
                else:
                    result.append("%" + spec)
                i += 2
            else:
                result.append(fmt[i])
                i += 1

        return "".join(result)

    # -----------------------------------------------------------------
    # Syscall handlers
    # -----------------------------------------------------------------

    def _syscall_clos(self, context, output):
        """CLOS (close) — close fd, optionally via tool_handler.

        C4: close(fd) → push fd, CLOS. So fd = sp[0] = STACK0.
        """
        fd = self._extract_stack0(context) or 0

        if self._tool_handler:
            call = ToolCall("close", self._next_tool_call_id(), {"fd": fd})
            resp = self._tool_handler(call)
            result = 0 if resp.success else 0xFFFFFFFF
        else:
            # Default: just remove from tracking
            self._open_fds.pop(fd, None)
            result = 0

        self._override_ax_in_last_step(context, result)

    def _syscall_open(self, context, output):
        """OPEN — open file, optionally via tool_handler.

        C4: open(path, mode) → push path_ptr, push mode, OPEN.
        So: sp[0]=mode, sp[1]=path_ptr.
        """
        mode = self._read_stack_arg(context, 0)  # sp[0] = mode
        path_ptr = self._read_stack_arg(context, 1)  # sp[1] = path_ptr
        path = self._read_string(path_ptr)
        mode_str = {0: "r", 1: "w", 2: "a"}.get(mode, "r")

        if self._tool_handler:
            call = ToolCall(
                "open", self._next_tool_call_id(), {"path": path, "mode": mode_str}
            )
            resp = self._tool_handler(call)
            result = resp.result if resp.success else 0xFFFFFFFF
        else:
            # Default: real file I/O
            try:
                flags = os.O_RDONLY if mode == 0 else os.O_WRONLY | os.O_CREAT
                fd = os.open(path, flags, 0o644)
                self._open_fds[fd] = path
                result = fd
            except OSError:
                result = 0xFFFFFFFF  # -1

        self._override_ax_in_last_step(context, result & 0xFFFFFFFF)

    def _syscall_read(self, context, output):
        """READ — read from fd, optionally via tool_handler.

        C4: read(fd, buf, count) → push fd, push buf_ptr, push count, READ.
        So: sp[0]=count, sp[1]=buf_ptr, sp[2]=fd.
        """
        count = self._read_stack_arg(context, 0)  # sp[0] = count
        buf_ptr = self._read_stack_arg(context, 1)  # sp[1] = buf_ptr
        fd = self._read_stack_arg(context, 2)  # sp[2] = fd

        if self._tool_handler:
            call = ToolCall(
                "read",
                self._next_tool_call_id(),
                {"fd": fd, "buf_ptr": buf_ptr, "size": count},
            )
            resp = self._tool_handler(call)
            if resp.success and resp.result is not None:
                data = resp.result
                if isinstance(data, (bytes, bytearray)):
                    for i, b in enumerate(data):
                        self._memory[buf_ptr + i] = b
                    result = len(data)
                elif isinstance(data, int):
                    result = data
                else:
                    result = 0
            else:
                result = 0xFFFFFFFF  # -1
        else:
            # Default: real file I/O
            try:
                data = os.read(fd, count)
                for i, b in enumerate(data):
                    self._memory[buf_ptr + i] = b
                result = len(data)
            except OSError:
                result = 0xFFFFFFFF  # -1

        self._override_ax_in_last_step(context, result & 0xFFFFFFFF)

    def _syscall_prtf(self, context, output):
        """PRTF (printf) — formatted print, optionally via tool_handler.

        C4 convention: printf(fmt, a, b, ...) pushes left-to-right.
        At PRTF time the ADJ instruction immediately follows, telling us argc.
        sp[argc-1] = fmt_ptr (first pushed, deepest).
        sp[argc-2..0] = remaining args from second to last.
        """
        # Determine argc by peeking at the next instruction (ADJ n)
        pc = self._extract_register(context, Token.REG_PC)
        argc = 0
        if pc is not None:
            adj_idx = pc // INSTR_WIDTH + 1  # next instruction after PRTF
            if 0 <= adj_idx < len(self._bytecode):
                adj_instr = self._bytecode[adj_idx]
                adj_op = adj_instr & 0xFF
                if adj_op == Opcode.ADJ:
                    adj_imm = adj_instr >> 8
                    argc = adj_imm // 8

        if argc < 1:
            # Can't determine args — fallback
            self._override_ax_in_last_step(context, 0)
            return

        # Read fmt_ptr (deepest on stack = sp[argc-1])
        fmt_ptr = self._read_stack_arg(context, argc - 1)
        fmt_str = self._read_string(fmt_ptr)

        # Read remaining args: sp[argc-2] is first vararg, sp[0] is last
        args = []
        for i in range(argc - 2, -1, -1):
            args.append(self._read_stack_arg(context, i))

        if self._tool_handler:
            call = ToolCall(
                "printf", self._next_tool_call_id(), {"format": fmt_str, "args": args}
            )
            resp = self._tool_handler(call)
            if resp.success and resp.result is not None:
                formatted = str(resp.result)
                result = len(formatted)
            else:
                result = 0
        else:
            # Default: format directly and append to output
            formatted = self._format_printf(fmt_str, args)
            output.append(formatted)
            result = len(formatted)

        self._override_ax_in_last_step(context, result & 0xFFFFFFFF)

    def _exec_pc(self):
        """Compute PC of the instruction that was just executed.

        The output PC from the PREVIOUS step is the address where
        execution will continue (after PC increment or jump). This
        means the instruction we're CURRENTLY executing is at that
        address.

        Example (with PC_OFFSET=2, INSTR_WIDTH=8):
          Step 0: Execute JSR at PC=2, output PC=18 (jump)
          Step 1: Execute instruction at PC=18 (not PC=26!)

        For the very first step, _last_pc is None and we return PC_OFFSET
        (the PC of the first instruction).
        """
        if self._last_pc is None:
            return PC_OFFSET
        return self._last_pc

    @staticmethod
    def _resolve_target_pc(target):
        if target % INSTR_WIDTH == PC_OFFSET:
            return target
        return target * INSTR_WIDTH + PC_OFFSET

    def _decode_exit_code(self, context):
        """Extract exit code from the last REG_AX before HALT."""
        for i in range(len(context) - 1, -1, -1):
            if context[i] == Token.REG_AX and i + 4 < len(context):
                val = 0
                for j in range(4):
                    val |= (context[i + 1 + j] & 0xFF) << (j * 8)
                return val
        return 0


# =============================================================================
# Demo / Test
# =============================================================================


def demo():
    """Demonstrate autoregressive VM runner."""
    print("=" * 60)
    print("AUTOREGRESSIVE VM RUNNER")
    print("Decoder-only transformer with generation loop")
    print("=" * 60)

    # Test 1: Build context for a simple program
    print("\n--- Context Building ---")
    runner = AutoregressiveVMRunner()

    program = [
        Opcode.IMM | (42 << 8),  # IMM 42
        Opcode.EXIT,  # EXIT
    ]

    runner._bytecode = program
    ctx = runner._build_context(program, b"", [])
    print(f"Program: IMM 42; EXIT")
    print(f"Context length: {len(ctx)} tokens")
    print(f"Tokens: {ctx}")

    # Verify context structure
    assert ctx[0] == Token.CODE_START
    assert ctx[1] == Opcode.IMM  # First instruction opcode
    assert ctx[2] == 42  # Immediate byte 0
    assert ctx[3] == 0  # Immediate byte 1
    assert ctx[4] == 0  # Immediate byte 2
    assert ctx[5] == 0  # Immediate byte 3
    assert ctx[6] == Opcode.EXIT  # Second instruction opcode
    code_end_idx = ctx.index(Token.CODE_END)
    print(f"CODE section: tokens 0..{code_end_idx}")
    print(f"Context verified OK")

    # Test 2: Model forward pass
    print("\n--- Model Forward Pass ---")
    model = runner.model
    param_count = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {param_count:,}")

    token_ids = torch.tensor([ctx], dtype=torch.long)
    with torch.no_grad():
        logits = model(token_ids)
    print(f"Input shape:  {token_ids.shape}")
    print(f"Output shape: {logits.shape}")
    print(f"Output vocab: {logits.shape[-1]} (expected {Token.VOCAB_SIZE})")

    # Test 3: Single token generation
    print("\n--- Token Generation ---")
    next_token = model.generate_next(ctx)
    print(f"Generated next token: {next_token}")
    print(f"(Note: random with unset weights)")

    # Test 4: Context building with data and argv
    print("\n--- Context with Data & Argv ---")
    program2 = [
        Opcode.IMM | (5 << 8),
        Opcode.PSH,
        Opcode.IMM | (3 << 8),
        Opcode.ADD,
        Opcode.EXIT,
    ]
    ctx2 = runner._build_context(
        program2, b"\x48\x65\x6c\x6c\x6f", ["hello", "world"], ""
    )
    print(f"Program: IMM 5; PSH; IMM 3; ADD; EXIT")
    print(f"Data: b'Hello'")
    print(f"Argv: ['hello', 'world']")
    print(f"Context length: {len(ctx2)} tokens")

    data_start = ctx2.index(Token.DATA_START)
    data_end = ctx2.index(Token.DATA_END)
    print(f"DATA section: tokens {data_start}..{data_end}")
    print(f"Data bytes: {ctx2[data_start + 1 : data_end]}")

    print("\n" + "=" * 60)
    print("Demo complete!")
    print("Note: Model has zero/random weights. Correct output requires")
    print("weight setting (follow-up step).")
    print("=" * 60)


if __name__ == "__main__":
    demo()
