"""
Autoregressive VM Runner - generation loop and compatibility boundary.

The core model is a decoder-only transformer (`AutoregressiveVM`). This file
is the thin runtime around that model: it builds the prefix context, performs
the standard autoregressive generation loop, and handles explicit external I/O.

Purity notes:
  - `pure_attention_memory=True` is the strict mode. In that mode, runner-side
    VM-memory fallbacks are blocked and reported via `get_pure_attention_report()`.
  - Tool/I/O boundary handlers (`OPEN/READ/CLOS/PRTF/GETCHAR/PUTCHAR`) are
    intentionally external.
  - Anything else in this file that mutates VM state is transitional
    compatibility/debugging scaffolding while full attention-memory execution is
    being completed.

IO strategy:
  PUTCHAR — Fully autoregressive. The model routes AX -> OUTPUT -> byte logits;
            the runner only reads generated bytes.

  GETCHAR — Runner-side injection. The runner reads stdin and overwrites AX in
            the just-completed step. This is an explicit external boundary, not
            part of the pure transformer.
"""

import os
import torch
import warnings
from typing import List, Optional, Callable, Any, Dict
from dataclasses import dataclass, field

from .vm_step import AutoregressiveVM, Token, set_vm_weights
from .embedding import Opcode
from .constants import INSTR_WIDTH, PC_OFFSET

# Opcodes that emit TOOL_CALL instead of STEP_END when tool calling is enabled.
# When model emits STEP_END for these (weights not set, or enable_tool_calling=False),
# runner still dispatches at STEP_END (backward compatible).
_TOOL_CALL_OPS = {
    Opcode.PRTF,
    Opcode.OPEN,
    Opcode.READ,
    Opcode.CLOS,
    Opcode.PUTCHAR,
    Opcode.GETCHAR,
}

# Runner-side fallback ops (blocked in pure_attention_memory mode).
# These mutate/consult shadow memory or apply runner semantic corrections.
# SI/SC removed: _track_memory_write handles shadow updates from MEM tokens.
# LI/LC removed: L15 softmax1 memory lookup produces correct AX values
# when MEM sections are retained in context and MEM_STORE is injected.
_RUNNER_VM_MEMORY_OPS = {
    Opcode.ADJ,
    Opcode.MALC,
    Opcode.FREE,
    Opcode.MSET,
    Opcode.MCMP,
}

# Ops that write runner shadow memory through _track_memory_write.
# SI/SC: no longer blocked in pure_attention_memory mode — tracking always runs
# since other handlers (LI/LC, MALC, etc.) still read from _memory.
_RUNNER_TRACKED_MEMORY_OPS = {Opcode.ENT, Opcode.JSR}

# Store ops whose MEM sections are retained in context for L15 memory lookup.
_MEM_STORE_OPS = {Opcode.SI, Opcode.SC, Opcode.PSH, Opcode.ENT, Opcode.JSR}

_OPCODE_NAME = {
    v: k for k, v in vars(Opcode).items() if k.isupper() and isinstance(v, int)
}

# Binary ops that pop one operand from stack (SP += 8).
# Model handles byte-0 in weights; runner corrects multi-byte carry.
_BINARY_POP_OPS = {
    Opcode.ADD,
    Opcode.SUB,
    Opcode.MUL,
    Opcode.DIV,
    Opcode.MOD,
    Opcode.EQ,
    Opcode.NE,
    Opcode.LT,
    Opcode.GT,
    Opcode.LE,
    Opcode.GE,
    Opcode.OR,
    Opcode.XOR,
    Opcode.AND,
    Opcode.SHL,
    Opcode.SHR,
    Opcode.SI,
    Opcode.SC,
}


@dataclass
class ToolCall:
    """A tool call request from the VM to an external handler."""

    call_type: str  # "printf", "open", "read", "close"
    call_id: int
    params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ToolResponse:
    """Response from external handler back to the VM."""

    call_id: int
    success: bool
    result: Any = None


class AutoregressiveVMRunner:
    """Generation loop for the autoregressive VM.

    Analogous to an LLM inference loop:
    - Build context (system prompt): bytecode + data + argv as tokens
    - Generate tokens autoregressively (model forward + greedy decode)
    - Detect I/O boundary (output bytes, halt)

    Supports two I/O modes:
    1. Legacy mode (conversational_io=False): Python handlers for I/O syscalls
    2. Conversational mode (conversational_io=True): Truly autoregressive I/O
       - Output: Model generates </thinking>, output text, <thinking>
       - Input: Model extracts from <user_input> tags in context
       - All I/O is part of the token stream (100% autoregressive)
    """

    def __init__(
        self,
        d_model=512,
        n_layers=16,
        n_heads=8,
        ffn_hidden=4096,
        max_seq_len=4096,
        pure_attention_memory=False,
        conversational_io=False,
    ):
        self.model = AutoregressiveVM(
            d_model=d_model,
            n_layers=n_layers,
            n_heads=n_heads,
            ffn_hidden=ffn_hidden,
            max_seq_len=max_seq_len,
        )
        # Load hand-crafted transformer weights for VM execution
        set_vm_weights(self.model)
        self.model.eval()

        # Syscall dispatch table
        # NOTE ON PURITY:
        # - Tool boundary handlers (OPEN/READ/CLOS/PRTF/GETCHAR/PUTCHAR) are
        #   intentionally external.
        # - VM semantic handlers below are transitional fallbacks for bring-up
        #   and debugging. In pure_attention_memory mode, these paths are
        #   blocked so execution depends on transformer/autoregressive behavior.
        self._syscall_handlers = {
            Opcode.PUTCHAR: self._syscall_putchar,
            Opcode.GETCHAR: self._syscall_getchar,
            # DIV/MOD removed — neural (DivModModule after L10)
            # LI/LC handlers removed: L15 softmax1 memory lookup produces
            # correct AX values with MEM section retention + MEM_STORE injection.
            # SI/SC handlers removed: _track_memory_write provides equivalent
            # shadow memory updates via L14-generated MEM section extraction.
            Opcode.ADJ: self._syscall_adj,
            Opcode.MALC: self._syscall_malc,
            Opcode.FREE: self._syscall_free,
            Opcode.CLOS: self._syscall_clos,
            Opcode.OPEN: self._syscall_open,
            Opcode.READ: self._syscall_read,
            Opcode.PRTF: self._syscall_prtf,
            Opcode.MSET: self._syscall_mset,
            Opcode.MCMP: self._syscall_mcmp,
        }

        # File descriptor tracking
        self._open_fds = {}  # fd → name

        # Bump allocator state
        self._heap_base = 0x10000  # Start of heap

        # Conversational I/O mode flag
        # When True, I/O operations are handled autoregressively:
        # - Output (printf/putchar): Model generates THINKING_END, output text, THINKING_START
        # - Input (read/getchar): Model extracts from USER_INPUT section in context
        # When False, I/O operations use Python handlers (legacy mode)
        self.conversational_io = conversational_io
        self._heap_ptr = 0x10000  # Current allocation pointer
        self._alloc_sizes = {}  # addr → size (for FREE zero-fill)

        # Shadow memory: sparse dict tracking all stores (PSH, SI, SC, etc.)
        # Enables runner-side syscalls to read stack arguments beyond STACK0.
        # All entries are byte-granularity (addr → uint8).
        self._memory = {}  # addr → byte value

        # SP tracking for multi-byte correctness (PSH/ADJ handlers use this)
        self._last_sp = 0

        # PC tracking for exec_pc computation (function-call dispatch)
        self._last_pc = None

        # BP tracking for ENT/LEV handlers
        self._last_bp = 0

        # AX tracking for multi-byte preservation across steps.
        # Weights carry byte 0 only; runner re-applies bytes 1-3 each step.
        self._last_ax = 0

        # Function-call handlers dispatched by exec_pc (not output PC).
        # These are runner-side compatibility shims for full 32-bit correctness
        # while the corresponding neural memory paths are being completed.
        self._func_call_handlers = {
            Opcode.IMM: self._handler_imm,
            Opcode.LEA: self._handler_lea,
            Opcode.JSR: self._handler_jsr,
            Opcode.ENT: self._handler_ent,
            Opcode.LEV: self._handler_lev,
            # Stack operations
            Opcode.PSH: self._handler_psh,
            # Arithmetic operations (neural weights broken, using fallback)
            Opcode.ADD: self._handler_add,
            Opcode.SUB: self._handler_sub,
            Opcode.MUL: self._handler_mul,
            Opcode.DIV: self._handler_div,
            Opcode.MOD: self._handler_mod,
            # Bitwise operations (neural weights broken, using fallback)
            Opcode.OR: self._handler_or,
            Opcode.XOR: self._handler_xor,
            Opcode.AND: self._handler_and,
            # Shift operations (neural weights broken, using fallback)
            Opcode.SHL: self._handler_shl,
            Opcode.SHR: self._handler_shr,
        }

        # If True: disable runner VM-memory emulation paths and only allow
        # explicit external tool boundary handling.
        self.pure_attention_memory = pure_attention_memory
        self._pure_attention_report = {}

    def run(
        self,
        bytecode,
        data=b"",
        argv=None,
        stdin="",
        max_steps=100000,
        tool_handler=None,
    ):
        """Run a program via autoregressive generation.

        Args:
            bytecode: List of packed instructions (op | imm<<8)
            data: Data section bytes
            argv: List of argument strings
            stdin: Input string
            max_steps: Maximum VM steps (each step = 39 tokens)
            tool_handler: Optional callback(ToolCall) -> ToolResponse for I/O

        Returns:
            (output_string, exit_code) tuple
        """
        self._bytecode = bytecode
        self._stdin_buffer = list(stdin) if stdin else []
        self._stdin_pos = 0
        self._tool_handler = tool_handler
        self._tool_call_id = 0
        self._last_pc = None
        self._last_bp = 0
        self._last_sp = 0
        self._mem_history = {}  # addr → 9-token MEM section (latest wins)
        self.model.embed.set_mem_history_end(0)  # reset stale boundary from prior runs
        self._pure_attention_report = {
            "enabled": bool(self.pure_attention_memory),
            "blocked_vm_memory_ops": {},
            "blocked_track_memory_ops": {},
            "external_tool_ops": {},
            "halted": False,
        }

        # Load data section into shadow memory at 0x10000
        # C4 compiler uses data_base = 0x10000 (src/compiler.py:339)
        data = data or b""
        if isinstance(data, (bytes, bytearray)):
            for i, b in enumerate(data):
                self._memory[0x10000 + i] = b
        elif isinstance(data, list):
            for i, b in enumerate(data):
                self._memory[0x10000 + i] = b

        # Set heap base past end of data section, aligned to 8
        data_end = 0x10000 + len(data)
        self._heap_base = (data_end + 7) & ~7
        self._heap_ptr = self._heap_base

        context = self._build_context(bytecode, data, argv or [], stdin)
        prefix_len = len(context)  # code + data prefix length (immutable)
        output = []

        # Set initial opcode for MoE routing (first instruction)
        init_exec = self._exec_pc() // INSTR_WIDTH
        if 0 <= init_exec < len(bytecode):
            self.model.set_active_opcode(bytecode[init_exec] & 0xFF)

        step_num = 0  # Track step number for debugging
        for _ in range(max_steps * Token.STEP_TOKENS):
            next_token = self.model.generate_next(context)
            context.append(next_token)

            if next_token == Token.STEP_END:
                step_num += 1  # Increment step counter
                # Extract PC and dispatch syscall handler
                op = None
                instr_idx = None
                exec_pc = self._exec_pc()  # PC being executed this step
                pc = self._extract_register(context, Token.REG_PC)  # Next PC from output
                # Get opcode being executed this step
                exec_idx = exec_pc // INSTR_WIDTH
                exec_op = None
                exec_opname = "?"
                if 0 <= exec_idx < len(bytecode):
                    exec_op = bytecode[exec_idx] & 0xFF
                    # Find opcode name
                    for name in dir(Opcode):
                        if not name.startswith('_') and getattr(Opcode, name) == exec_op:
                            exec_opname = name
                            break

                if pc is not None:
                    instr_idx = pc // INSTR_WIDTH
                    if 0 <= instr_idx < len(bytecode):
                        op = bytecode[instr_idx] & 0xFF
                        handler = self._syscall_handlers.get(op)
                        if handler:
                            if self._should_block_vm_memory_handler(op):
                                self._record_pure_attention("blocked_vm_memory_ops", op)
                            else:
                                handler(context, output)
                                if op in _TOOL_CALL_OPS:
                                    self._record_pure_attention("external_tool_ops", op)
                        # Transitional runner SP byte corrections for fallback
                        # execution. Disabled in pure-attention mode.
                        if not self.pure_attention_memory:
                            # Correct SP for binary pop ops (model only handles byte 0)
                            if op in _BINARY_POP_OPS:
                                new_sp = (self._last_sp + 8) & 0xFFFFFFFF
                                self._override_register_in_last_step(
                                    context, Token.REG_SP, new_sp
                                )
                            # PSH SP multi-byte borrow correction
                            if op == Opcode.PSH:
                                new_sp = (self._last_sp - 8) & 0xFFFFFFFF
                                self._override_register_in_last_step(
                                    context, Token.REG_SP, new_sp
                                )
                            # ADJ SP multi-byte correction
                            if op == Opcode.ADJ:
                                instr = bytecode[instr_idx]
                                imm = instr >> 8
                                if imm >= 0x800000:
                                    imm -= 0x1000000
                                new_sp = (self._last_sp + imm) & 0xFFFFFFFF
                                self._override_register_in_last_step(
                                    context, Token.REG_SP, new_sp
                                )
                        # Track memory writes AFTER handler (handler may override SP/STACK0)
                        if self._should_block_track_memory(op):
                            self._record_pure_attention("blocked_track_memory_ops", op)
                        else:
                            self._track_memory_write(context, op)
                # Dispatch function-call handlers (use exec_pc, not output pc)
                exec_op = None
                exec_idx = self._exec_pc() // INSTR_WIDTH
                if 0 <= exec_idx < len(bytecode):
                    exec_op = bytecode[exec_idx] & 0xFF
                    func_handler = self._func_call_handlers.get(exec_op)
                    if func_handler:
                        func_handler(context, output)
                    else:
                        # Generic PC advancement for opcodes without handlers
                        # SKIP for opcodes that handle PC themselves or have handlers
                        # func_call_handlers handle their own PC advancement
                        opcodes_with_pc_handling = {Opcode.JMP, Opcode.BZ, Opcode.BNZ, Opcode.EXIT}
                        opcodes_with_pc_handling.update(self._func_call_handlers.keys())
                        if exec_op not in opcodes_with_pc_handling:
                            # Model doesn't advance PC neurally for all opcodes, so we do it here
                            exec_pc = self._exec_pc()
                            next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
                            self._override_register_in_last_step(context, Token.REG_PC, next_pc)
                # Update SP/BP/PC tracking (prefer deterministic SP evolution)
                if 0 <= exec_idx < len(bytecode):
                    # CRITICAL: Only extract SP for opcodes that modify SP
                    # PSH, JSR, ENT, LEV modify SP. Binary ops (OR, AND, etc.) also pop stack.
                    # Don't extract SP for IMM/LEA - they don't modify SP!
                    if exec_op in self._func_call_handlers:
                        SP_MODIFYING_OPS = {Opcode.PSH, Opcode.JSR, Opcode.ENT, Opcode.LEV,
                                           Opcode.ADD, Opcode.SUB, Opcode.MUL, Opcode.DIV, Opcode.MOD,
                                           Opcode.OR, Opcode.XOR, Opcode.AND, Opcode.SHL, Opcode.SHR}
                        if exec_op in SP_MODIFYING_OPS:
                            sp = self._extract_register(context, Token.REG_SP)
                            if sp is not None:
                                self._last_sp = sp
                        # CRITICAL: Only extract BP for ENT/LEV (they actually modify BP)
                        if exec_op in (Opcode.ENT, Opcode.LEV):
                            bp = self._extract_register(context, Token.REG_BP)
                            if bp is not None:
                                self._last_bp = bp
                    elif op is not None:
                        # Keep runner SP canonical for stack semantics.
                        if op == Opcode.PSH:
                            self._last_sp = (self._last_sp - 8) & 0xFFFFFFFF
                        elif op == Opcode.ADJ:
                            instr = bytecode[instr_idx]
                            imm = instr >> 8
                            if imm >= 0x800000:
                                imm -= 0x1000000
                            self._last_sp = (self._last_sp + imm) & 0xFFFFFFFF
                        elif op in _BINARY_POP_OPS:
                            self._last_sp = (self._last_sp + 8) & 0xFFFFFFFF
                # AX multi-byte preservation
                ax = self._extract_register(context, Token.REG_AX)
                if ax is not None:
                    # Check the EXECUTED opcode (exec_op), not the next opcode (op)
                    # Handlers (IMM, LEA, etc.) set full AX value - extract and trust it
                    if exec_op in self._func_call_handlers:
                        # Handlers override full 32-bit AX. Extract the overridden value.
                        self._last_ax = ax
                    elif op in (Opcode.LI, Opcode.LC):
                        # L15 produces correct output for all bytes. Trust transformer.
                        self._last_ax = ax
                    else:
                        # Normal merge: byte 0 from weights, bytes 1-3 from _last_ax
                        merged = (ax & 0xFF) | (self._last_ax & 0xFFFFFF00)
                        self._last_ax = merged
                        self._override_register_in_last_step(context, Token.REG_AX, merged)

                # BP tracking moved to func_call_handlers block above (ENT/LEV modify BP)
                # Don't extract BP from model output for normal opcodes - it's wrong!
                pc = self._extract_register(context, Token.REG_PC)
                if pc is not None:
                    self._last_pc = pc

                # Set next step's active opcode for MoE routing
                next_exec = self._exec_pc() // INSTR_WIDTH
                if 0 <= next_exec < len(bytecode):
                    self.model.set_active_opcode(bytecode[next_exec] & 0xFF)
                else:
                    self.model.set_active_opcode(None)

                # Capture MEM section from store ops for L15 memory lookup
                if op in _MEM_STORE_OPS:
                    mem_section = self._extract_mem_section(context)
                    if mem_section is not None:
                        addr = sum((mem_section[1 + j] & 0xFF) << (j * 8) for j in range(4))
                        self._mem_history[addr] = mem_section

                # Context pruning: keep prefix + retained MEM sections + last step.
                # MEM sections from prior store ops are needed by L15 softmax1
                # memory lookup. Deduplication by address ensures latest-wins.
                last_step = context[-(Token.STEP_TOKENS):]
                mem_flat = []
                for tokens in self._mem_history.values():
                    mem_flat.extend(tokens)
                context[prefix_len:] = mem_flat + list(last_step)
                self.model.embed.set_mem_history_end(prefix_len + len(mem_flat))

            elif next_token == Token.TOOL_CALL:
                # Model signaled a tool call — extract registers and dispatch
                op = None
                instr_idx = None
                pc = self._extract_register(context, Token.REG_PC)
                if pc is not None:
                    instr_idx = pc // INSTR_WIDTH
                    if 0 <= instr_idx < len(bytecode):
                        op = bytecode[instr_idx] & 0xFF
                        handler = self._syscall_handlers.get(op)
                        if handler:
                            if self._should_block_vm_memory_handler(op):
                                self._record_pure_attention("blocked_vm_memory_ops", op)
                            else:
                                handler(context, output)
                                if op in _TOOL_CALL_OPS:
                                    self._record_pure_attention("external_tool_ops", op)
                        if self._should_block_track_memory(op):
                            self._record_pure_attention("blocked_track_memory_ops", op)
                        else:
                            self._track_memory_write(context, op)
                # Dispatch function-call handlers (use exec_pc, not output pc)
                exec_op = None
                exec_idx = self._exec_pc() // INSTR_WIDTH
                if 0 <= exec_idx < len(bytecode):
                    exec_op = bytecode[exec_idx] & 0xFF
                    func_handler = self._func_call_handlers.get(exec_op)
                    if func_handler:
                        func_handler(context, output)
                    else:
                        # Generic PC advancement for opcodes without handlers
                        # SKIP for opcodes that handle PC themselves or have handlers
                        # func_call_handlers handle their own PC advancement
                        opcodes_with_pc_handling = {Opcode.JMP, Opcode.BZ, Opcode.BNZ, Opcode.EXIT}
                        opcodes_with_pc_handling.update(self._func_call_handlers.keys())
                        if exec_op not in opcodes_with_pc_handling:
                            # Model doesn't advance PC neurally for all opcodes, so we do it here
                            exec_pc = self._exec_pc()
                            next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
                            self._override_register_in_last_step(context, Token.REG_PC, next_pc)
                # Update SP/BP/PC tracking (prefer deterministic SP evolution)
                if 0 <= exec_idx < len(bytecode):
                    if exec_op in self._func_call_handlers:
                        sp = self._extract_register(context, Token.REG_SP)
                        if sp is not None:
                            self._last_sp = sp
                    elif op is not None:
                        if op == Opcode.PSH:
                            self._last_sp = (self._last_sp - 8) & 0xFFFFFFFF
                        elif op == Opcode.ADJ:
                            instr = bytecode[instr_idx]
                            imm = instr >> 8
                            if imm >= 0x800000:
                                imm -= 0x1000000
                            self._last_sp = (self._last_sp + imm) & 0xFFFFFFFF
                        elif op in _BINARY_POP_OPS:
                            self._last_sp = (self._last_sp + 8) & 0xFFFFFFFF
                # AX multi-byte preservation (same as STEP_END branch)
                ax = self._extract_register(context, Token.REG_AX)
                if ax is not None:
                    merged = (ax & 0xFF) | (self._last_ax & 0xFFFFFF00)
                    self._last_ax = merged
                    self._override_register_in_last_step(context, Token.REG_AX, merged)

                bp = self._extract_register(context, Token.REG_BP)
                if bp is not None:
                    self._last_bp = bp
                pc = self._extract_register(context, Token.REG_PC)
                if pc is not None:
                    self._last_pc = pc

                # Set next step's active opcode for MoE routing
                next_exec = self._exec_pc() // INSTR_WIDTH
                if 0 <= next_exec < len(bytecode):
                    self.model.set_active_opcode(bytecode[next_exec] & 0xFF)
                else:
                    self.model.set_active_opcode(None)

                # Capture MEM section from store ops for L15 memory lookup
                if op in _MEM_STORE_OPS:
                    mem_section = self._extract_mem_section(context)
                    if mem_section is not None:
                        addr = sum((mem_section[1 + j] & 0xFF) << (j * 8) for j in range(4))
                        self._mem_history[addr] = mem_section

                # Context pruning (same as STEP_END branch)
                last_step = context[-(Token.STEP_TOKENS):]
                mem_flat = []
                for tokens in self._mem_history.values():
                    mem_flat.extend(tokens)
                context[prefix_len:] = mem_flat + list(last_step)
                self.model.embed.set_mem_history_end(prefix_len + len(mem_flat))

            # Halt detection
            if next_token == Token.HALT:
                # Apply AX bytes 1-3 preservation before exiting
                ax = self._extract_register(context, Token.REG_AX)
                if ax is not None:
                    merged = (ax & 0xFF) | (self._last_ax & 0xFFFFFF00)
                    self._override_register_in_last_step(context, Token.REG_AX, merged)
                self._pure_attention_report["halted"] = True
                break

        return "".join(output), self._decode_exit_code(context)

    def get_pure_attention_report(self):
        """Return diagnostics for pure-attention-memory mode."""
        return dict(self._pure_attention_report)

    def _should_block_vm_memory_handler(self, op):
        return self.pure_attention_memory and op in _RUNNER_VM_MEMORY_OPS

    def _should_block_track_memory(self, op):
        return self.pure_attention_memory and op in _RUNNER_TRACKED_MEMORY_OPS

    def _record_pure_attention(self, bucket, op):
        if not self.pure_attention_memory:
            return
        name = _OPCODE_NAME.get(op, str(op))
        slot = self._pure_attention_report[bucket]
        slot[name] = slot.get(name, 0) + 1

    def _build_context(self, bytecode, data, argv, stdin=""):
        """Encode program as token sequence (context prefix).

        Format:
            [CODE_START] op0 imm0_b0 imm0_b1 imm0_b2 imm0_b3 op1 ... [CODE_END]
            [DATA_START] data_bytes... [DATA_END]
            [USER_INPUT_START] byte0 byte1 ... byteN [USER_INPUT_END]  (if stdin)
            argv0_chars... \\0 argv1_chars... \\0

        Each instruction is 5 tokens: opcode byte + 4 immediate bytes (little-endian).
        """
        tokens = [Token.CODE_START]

        for instr in bytecode:
            op = instr & 0xFF
            imm = instr >> 8
            tokens.append(op)
            for i in range(4):
                tokens.append((imm >> (i * 8)) & 0xFF)

        tokens.append(Token.CODE_END)
        tokens.append(Token.DATA_START)

        if isinstance(data, (bytes, bytearray)):
            tokens.extend(data)
        elif isinstance(data, list):
            tokens.extend(data)

        tokens.append(Token.DATA_END)

        # User input (stdin) as marked block
        if stdin:
            tokens.append(Token.USER_INPUT_START)
            tokens.extend(ord(c) for c in stdin)
            tokens.append(Token.USER_INPUT_END)

        if argv:
            for arg in argv:
                tokens.extend(ord(c) for c in arg)
                tokens.append(0)  # null terminator

        return tokens

    def _is_output_byte(self, context):
        """Detect if a PUTCHAR step just completed.

        Tracks PC and looks up the opcode in the original bytecode.
        """
        if len(context) < 2:
            return False
        if context[-1] != Token.STEP_END:
            return False
        pc = self._extract_register(context, Token.REG_PC)
        if pc is None:
            return False
        instr_idx = pc // INSTR_WIDTH
        if 0 <= instr_idx < len(self._bytecode):
            return (self._bytecode[instr_idx] & 0xFF) == Opcode.PUTCHAR
        return False

    def _extract_register(self, context, marker_token):
        """Extract 32-bit register value from the last completed step.

        Scans back from the end to find the marker token, then reads
        the 4 value bytes (little-endian).
        """
        scan_back = Token.STEP_TOKENS + 5  # step size + margin
        for i in range(len(context) - 1, max(0, len(context) - scan_back), -1):
            if context[i] == marker_token and i + 4 < len(context):
                val = 0
                for j in range(4):
                    val |= (context[i + 1 + j] & 0xFF) << (j * 8)
                return val
        return None

    def _extract_output_byte(self, context):
        """Extract output byte from the last completed step's AX register."""
        val = self._extract_register(context, Token.REG_AX)
        if val is not None:
            return chr(val & 0xFF)
        return None

    def _inject_getchar(self, context):
        """Runner-side GETCHAR: inject next stdin byte into context.

        This is NOT autoregressive — the runner directly overwrites the
        AX register bytes the model generated. The model has no mechanism
        to read from the stdin buffer in its weights.

        If stdin is exhausted, injects -1 (0xFFFFFFFF) for EOF.
        """
        if self._stdin_pos < len(self._stdin_buffer):
            byte_val = ord(self._stdin_buffer[self._stdin_pos])
            self._stdin_pos += 1
        else:
            byte_val = 0xFFFFFFFF  # EOF = -1

        self._override_ax_in_last_step(context, byte_val)

    def _override_ax_in_last_step(self, context, value):
        """Override AX register bytes in the last completed step.

        Scans back from STEP_END to find REG_AX marker and replaces
        the 4 value bytes with the given value (little-endian).
        Also updates _last_ax for multi-byte preservation across steps.
        """
        self._last_ax = value & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_AX, value)

    def _override_register_in_last_step(self, context, marker_token, value):
        """Override any register's bytes in the last completed step.

        Scans back to find the marker token and replaces
        the 4 value bytes with the given value (little-endian).
        """
        scan_back = Token.STEP_TOKENS + 5
        for i in range(len(context) - 1, max(0, len(context) - scan_back), -1):
            if context[i] == marker_token and i + 4 < len(context):
                for j in range(4):
                    context[i + 1 + j] = (value >> (j * 8)) & 0xFF
                return

    def _extract_stack0(self, context):
        """Extract 32-bit STACK0 (*sp) value from the last completed step."""
        return self._extract_register(context, Token.STACK0)

    def _track_memory_write(self, context, op):
        """Track memory writes to maintain shadow memory state.

        Called after each step. Updates _memory dict for opcodes that
        store to memory. All store ops (PSH, SI, SC, ENT, JSR) now
        generate MEM section bytes via L14 attention heads.

        Extracts addr/value from MEM section for shadow memory tracking.
        """
        if op in (Opcode.PSH, Opcode.SI, Opcode.SC, Opcode.ENT, Opcode.JSR):
            addr, value = self._extract_mem_write(context)
            if addr is not None:
                if op == Opcode.SC:
                    # SC stores a single byte
                    self._memory[addr] = value & 0xFF
                else:
                    self._mem_store_word(addr, value)

    def _extract_mem_write(self, context):
        """Extract memory write (addr, value) from MEM section of last step."""
        scan_back = Token.STEP_TOKENS + 5
        for i in range(len(context) - 1, max(0, len(context) - scan_back), -1):
            if context[i] == Token.MEM and i + 8 < len(context):
                addr = 0
                for j in range(4):
                    addr |= (context[i + 1 + j] & 0xFF) << (j * 8)
                value = 0
                for j in range(4):
                    value |= (context[i + 5 + j] & 0xFF) << (j * 8)
                return addr, value
        return None, None

    def _extract_mem_section(self, context):
        """Extract 9-token MEM section [MEM, a0-3, v0-3] from last step."""
        scan_back = Token.STEP_TOKENS + 5
        for i in range(len(context) - 1, max(0, len(context) - scan_back), -1):
            if context[i] == Token.MEM and i + 8 < len(context):
                return list(context[i:i + 9])
        return None

    def _mem_store_word(self, addr, value):
        """Store a 32-bit value as 4 little-endian bytes in shadow memory."""
        value = value & 0xFFFFFFFF
        for i in range(4):
            self._memory[addr + i] = (value >> (i * 8)) & 0xFF

    def _mem_load_word(self, addr):
        """Load a 32-bit value from 4 little-endian bytes in shadow memory."""
        val = 0
        for i in range(4):
            val |= self._memory.get(addr + i, 0) << (i * 8)
        return val

    def _read_stack_arg(self, context, arg_index):
        """Read argument from stack by index.

        C4 pushes args left-to-right, so at syscall time:
          arg_index 0 = sp[0] = STACK0 (last pushed = last formal arg)
          arg_index 1 = sp[1] = memory[sp+8]
          arg_index 2 = sp[2] = memory[sp+16]

        For a C call f(a, b, c): push a, push b, push c, SYSCALL
          sp[0] = c, sp[1] = b, sp[2] = a
        """
        if arg_index == 0:
            return self._extract_stack0(context) or 0
        sp = self._extract_register(context, Token.REG_SP)
        if sp is None:
            return 0
        return self._mem_load_word(sp + arg_index * 8)

    # -----------------------------------------------------------------
    # Tool calling helpers
    # -----------------------------------------------------------------

    def _next_tool_call_id(self):
        """Return a monotonically increasing tool call ID."""
        self._tool_call_id += 1
        return self._tool_call_id

    def _read_string(self, ptr, max_len=4096):
        """Read null-terminated string from shadow memory.

        Args:
            ptr: Starting address in _memory
            max_len: Safety limit on string length

        Returns:
            The decoded string (empty string if ptr is 0 or invalid).
        """
        if ptr == 0:
            return ""
        chars = []
        for i in range(max_len):
            c = self._memory.get(ptr + i, 0)
            if c == 0:
                break
            chars.append(chr(c & 0xFF))
        return "".join(chars)

    def _format_printf(self, fmt, args):
        """Simple printf-style formatting.

        Supports: %d, %s, %c, %x, %%
        For %s args, resolves pointers via _read_string().

        Args:
            fmt: Format string
            args: List of integer arguments

        Returns:
            Formatted output string
        """
        result = []
        i = 0
        arg_idx = 0

        while i < len(fmt):
            if fmt[i] == "%" and i + 1 < len(fmt):
                spec = fmt[i + 1]
                arg = args[arg_idx] if arg_idx < len(args) else 0
                if spec == "d" or spec == "i":
                    # Signed interpretation
                    if arg >= 0x80000000:
                        arg = arg - 0x100000000
                    result.append(str(arg))
                    arg_idx += 1
                elif spec == "s":
                    result.append(self._read_string(arg))
                    arg_idx += 1
                elif spec == "c":
                    result.append(chr(arg & 0xFF))
                    arg_idx += 1
                elif spec == "x":
                    result.append(format(arg & 0xFFFFFFFF, "x"))
                    arg_idx += 1
                elif spec == "%":
                    result.append("%")
                else:
                    result.append("%" + spec)
                i += 2
            else:
                result.append(fmt[i])
                i += 1

        return "".join(result)

    # -----------------------------------------------------------------
    # Syscall handlers
    # -----------------------------------------------------------------

    def _syscall_putchar(self, context, output):
        """PUTCHAR — read AX low byte, optionally via tool_handler."""
        byte_val = self._extract_output_byte(context)
        if byte_val is not None:
            if self._tool_handler:
                call = ToolCall(
                    "putchar", self._next_tool_call_id(), {"char": byte_val}
                )
                self._tool_handler(call)
            else:
                output.append(byte_val)

    def _syscall_getchar(self, context, output):
        """GETCHAR — inject next stdin byte into AX, optionally via tool_handler."""
        if self._tool_handler:
            call = ToolCall("getchar", self._next_tool_call_id(), {})
            resp = self._tool_handler(call)
            if resp.success and resp.result is not None:
                byte_val = resp.result & 0xFFFFFFFF
            else:
                byte_val = 0xFFFFFFFF  # EOF = -1
            self._override_ax_in_last_step(context, byte_val)
        else:
            self._inject_getchar(context)

    def _syscall_mul(self, context, output):
        """MUL — runner fallback multiply: AX = stack_top * AX.

        Uses runner shadow memory at last known SP as stack operand source.
        """
        rhs = self._extract_register(context, Token.REG_AX)
        if rhs is None:
            return
        lhs = self._mem_load_word(self._last_sp)
        result = (lhs * rhs) & 0xFFFFFFFF
        self._override_ax_in_last_step(context, result)

    def _syscall_div(self, context, output):
        """DIV — runner-side integer division: AX = STACK0 / AX."""
        a = self._extract_stack0(context)
        b = self._extract_register(context, Token.REG_AX)
        if a is not None and b is not None and b != 0:
            result = a // b
        else:
            result = 0  # division by zero → 0
        self._override_ax_in_last_step(context, result & 0xFFFFFFFF)

    def _syscall_mod(self, context, output):
        """MOD — runner-side modulo: AX = STACK0 % AX."""
        a = self._extract_stack0(context)
        b = self._extract_register(context, Token.REG_AX)
        if a is not None and b is not None and b != 0:
            result = a % b
        else:
            result = 0  # mod by zero → 0
        self._override_ax_in_last_step(context, result & 0xFFFFFFFF)

    def _syscall_li(self, context, output):
        """LI (load int) — AX = memory[AX] (32-bit, 4 LE bytes)."""
        addr = self._extract_register(context, Token.REG_AX)
        if addr is not None:
            value = self._mem_load_word(addr)
            self._override_ax_in_last_step(context, value & 0xFFFFFFFF)

    def _syscall_lc(self, context, output):
        """LC (load char) — AX = memory[AX] & 0xFF (8-bit)."""
        addr = self._extract_register(context, Token.REG_AX)
        if addr is not None:
            value = self._memory.get(addr, 0) & 0xFF
            self._override_ax_in_last_step(context, value)

    def _syscall_si(self, context, output):
        """SI (store int) — memory[STACK0] = AX (32-bit). No AX override."""
        addr = self._extract_stack0(context)
        ax = self._extract_register(context, Token.REG_AX)
        if addr is not None and ax is not None:
            self._mem_store_word(addr, ax)

    def _syscall_sc(self, context, output):
        """SC (store char) — memory[STACK0] = AX & 0xFF (8-bit). No AX override."""
        addr = self._extract_stack0(context)
        ax = self._extract_register(context, Token.REG_AX)
        if addr is not None and ax is not None:
            self._memory[addr] = ax & 0xFF

    def _syscall_psh(self, context, output):
        """PSH — runner fallback for stack semantics.

        Model is expected to handle SP decrement and STACK0=AX, but this
        fallback keeps semantics correct when those paths are incomplete.
        """
        ax = self._extract_register(context, Token.REG_AX)
        new_sp = (self._last_sp - 8) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        if ax is not None:
            self._override_register_in_last_step(context, Token.STACK0, ax)

    def _syscall_adj(self, context, output):
        """ADJ — SP += immediate. Override SP in context.

        Reads the signed immediate from bytecode (imm field of the ADJ instruction).
        """
        pc = self._extract_register(context, Token.REG_PC)
        if pc is None:
            return
        instr_idx = pc // INSTR_WIDTH
        if 0 <= instr_idx < len(self._bytecode):
            instr = self._bytecode[instr_idx]
            imm = instr >> 8
            # Sign-extend 24-bit immediate
            if imm >= 0x800000:
                imm -= 0x1000000
            new_sp = (self._last_sp + imm) & 0xFFFFFFFF
            self._override_register_in_last_step(context, Token.REG_SP, new_sp)

    def _syscall_malc(self, context, output):
        """MALC (malloc) — bump allocator. AX = allocated address.

        C4: malloc(size) → push size, MALC. So size = sp[0] = STACK0.
        """
        size = self._read_stack_arg(context, 0)  # sp[0] = size
        # Align to 8 bytes
        raw_size = size
        size = (size + 7) & ~7
        addr = self._heap_ptr
        self._heap_ptr += size
        self._alloc_sizes[addr] = raw_size
        self._override_ax_in_last_step(context, addr & 0xFFFFFFFF)

    def _syscall_free(self, context, output):
        """FREE — zero-fill freed region (ZFOD semantics).

        C4: free(ptr) → push ptr, FREE. So ptr = sp[0] = STACK0.
        With softmax1 attention, zero values are ignored, so zeroing
        memory effectively reclaims it.
        """
        ptr = self._read_stack_arg(context, 0)  # sp[0] = ptr
        size = self._alloc_sizes.pop(ptr, 0)
        # Zero-fill: remove entries from shadow memory (byte-level)
        for addr in range(ptr, ptr + size):
            self._memory.pop(addr, None)

    def _syscall_clos(self, context, output):
        """CLOS (close) — close fd, optionally via tool_handler.

        C4: close(fd) → push fd, CLOS. So fd = sp[0] = STACK0.
        """
        fd = self._extract_stack0(context) or 0

        if self._tool_handler:
            call = ToolCall("close", self._next_tool_call_id(), {"fd": fd})
            resp = self._tool_handler(call)
            result = 0 if resp.success else 0xFFFFFFFF
        else:
            # Default: just remove from tracking
            self._open_fds.pop(fd, None)
            result = 0

        self._override_ax_in_last_step(context, result)

    def _syscall_open(self, context, output):
        """OPEN — open file, optionally via tool_handler.

        C4: open(path, mode) → push path_ptr, push mode, OPEN.
        So: sp[0]=mode, sp[1]=path_ptr.
        """
        mode = self._read_stack_arg(context, 0)  # sp[0] = mode
        path_ptr = self._read_stack_arg(context, 1)  # sp[1] = path_ptr
        path = self._read_string(path_ptr)
        mode_str = {0: "r", 1: "w", 2: "a"}.get(mode, "r")

        if self._tool_handler:
            call = ToolCall(
                "open", self._next_tool_call_id(), {"path": path, "mode": mode_str}
            )
            resp = self._tool_handler(call)
            result = resp.result if resp.success else 0xFFFFFFFF
        else:
            # Default: real file I/O
            try:
                flags = os.O_RDONLY if mode == 0 else os.O_WRONLY | os.O_CREAT
                fd = os.open(path, flags, 0o644)
                self._open_fds[fd] = path
                result = fd
            except OSError:
                result = 0xFFFFFFFF  # -1

        self._override_ax_in_last_step(context, result & 0xFFFFFFFF)

    def _syscall_read(self, context, output):
        """READ — read from fd, optionally via tool_handler.

        C4: read(fd, buf, count) → push fd, push buf_ptr, push count, READ.
        So: sp[0]=count, sp[1]=buf_ptr, sp[2]=fd.
        """
        count = self._read_stack_arg(context, 0)  # sp[0] = count
        buf_ptr = self._read_stack_arg(context, 1)  # sp[1] = buf_ptr
        fd = self._read_stack_arg(context, 2)  # sp[2] = fd

        if self._tool_handler:
            call = ToolCall(
                "read",
                self._next_tool_call_id(),
                {"fd": fd, "buf_ptr": buf_ptr, "size": count},
            )
            resp = self._tool_handler(call)
            if resp.success and resp.result is not None:
                data = resp.result
                if isinstance(data, (bytes, bytearray)):
                    for i, b in enumerate(data):
                        self._memory[buf_ptr + i] = b
                    result = len(data)
                elif isinstance(data, int):
                    result = data
                else:
                    result = 0
            else:
                result = 0xFFFFFFFF  # -1
        else:
            # Default: real file I/O
            try:
                data = os.read(fd, count)
                for i, b in enumerate(data):
                    self._memory[buf_ptr + i] = b
                result = len(data)
            except OSError:
                result = 0xFFFFFFFF  # -1

        self._override_ax_in_last_step(context, result & 0xFFFFFFFF)

    def _syscall_prtf(self, context, output):
        """PRTF (printf) — formatted print, optionally via tool_handler.

        C4 convention: printf(fmt, a, b, ...) pushes left-to-right.
        At PRTF time the ADJ instruction immediately follows, telling us argc.
        sp[argc-1] = fmt_ptr (first pushed, deepest).
        sp[argc-2..0] = remaining args from second to last.
        """
        # Determine argc by peeking at the next instruction (ADJ n)
        pc = self._extract_register(context, Token.REG_PC)
        argc = 0
        if pc is not None:
            adj_idx = pc // INSTR_WIDTH + 1  # next instruction after PRTF
            if 0 <= adj_idx < len(self._bytecode):
                adj_instr = self._bytecode[adj_idx]
                adj_op = adj_instr & 0xFF
                if adj_op == Opcode.ADJ:
                    adj_imm = adj_instr >> 8
                    argc = adj_imm // 8

        if argc < 1:
            # Can't determine args — fallback
            self._override_ax_in_last_step(context, 0)
            return

        # Read fmt_ptr (deepest on stack = sp[argc-1])
        fmt_ptr = self._read_stack_arg(context, argc - 1)
        fmt_str = self._read_string(fmt_ptr)

        # Read remaining args: sp[argc-2] is first vararg, sp[0] is last
        args = []
        for i in range(argc - 2, -1, -1):
            args.append(self._read_stack_arg(context, i))

        if self._tool_handler:
            call = ToolCall(
                "printf", self._next_tool_call_id(), {"format": fmt_str, "args": args}
            )
            resp = self._tool_handler(call)
            if resp.success and resp.result is not None:
                formatted = str(resp.result)
                result = len(formatted)
            else:
                result = 0
        else:
            # Default: format directly and append to output
            formatted = self._format_printf(fmt_str, args)
            output.append(formatted)
            result = len(formatted)

        self._override_ax_in_last_step(context, result & 0xFFFFFFFF)

    def _syscall_mset(self, context, output):
        """MSET (memset) — fill memory region with a value.

        C4: memset(ptr, val, size) → push ptr, push val, push size, MSET.
        So: sp[0]=size, sp[1]=val, sp[2]=ptr.
        Returns ptr in AX.
        """
        size = self._read_stack_arg(context, 0)  # sp[0] = size
        val = self._read_stack_arg(context, 1)  # sp[1] = val
        ptr = self._read_stack_arg(context, 2)  # sp[2] = ptr
        val = val & 0xFF  # byte value
        for i in range(size):
            self._memory[ptr + i] = val
        self._override_ax_in_last_step(context, ptr & 0xFFFFFFFF)

    def _syscall_mcmp(self, context, output):
        """MCMP (memcmp) — compare two memory regions.

        C4: memcmp(p1, p2, size) → push p1, push p2, push size, MCMP.
        So: sp[0]=size, sp[1]=p2, sp[2]=p1.
        Returns: 0 if equal, <0 if p1<p2, >0 if p1>p2.
        """
        size = self._read_stack_arg(context, 0)  # sp[0] = size
        p2 = self._read_stack_arg(context, 1)  # sp[1] = p2
        p1 = self._read_stack_arg(context, 2)  # sp[2] = p1
        result = 0
        for i in range(size):
            a = self._memory.get(p1 + i, 0) & 0xFF
            b = self._memory.get(p2 + i, 0) & 0xFF
            if a != b:
                result = a - b
                break
        # Convert negative results to unsigned 32-bit
        self._override_ax_in_last_step(context, result & 0xFFFFFFFF)

    # -----------------------------------------------------------------
    # Function-call handlers (dispatched by exec_pc)
    # -----------------------------------------------------------------

    def _exec_pc(self):
        """Compute PC of the instruction that was just executed.

        The output PC from the PREVIOUS step is the address where
        execution will continue (after PC increment or jump). This
        means the instruction we're CURRENTLY executing is at that
        address.

        Example (with PC_OFFSET=2, INSTR_WIDTH=8):
          Step 0: Execute JSR at PC=2, output PC=18 (jump)
          Step 1: Execute instruction at PC=18 (not PC=26!)

        For the very first step, _last_pc is None and we return PC_OFFSET
        (the PC of the first instruction).
        """
        if self._last_pc is None:
            return PC_OFFSET
        return self._last_pc

    def _handler_imm(self, context, output):
        """IMM -- Load immediate value into AX."""
        exec_pc = self._exec_pc()
        exec_idx = exec_pc // INSTR_WIDTH
        if exec_idx < 0 or exec_idx >= len(self._bytecode):
            return
        instr = self._bytecode[exec_idx]
        imm = instr >> 8
        # Sign-extend 24-bit immediate
        if imm >= 0x800000:
            imm -= 0x1000000
        self._override_ax_in_last_step(context, imm & 0xFFFFFFFF)
        # Advance PC
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_psh(self, context, output):
        """PSH -- Push AX to stack."""
        ax = self._last_ax
        new_sp = (self._last_sp - 8) & 0xFFFFFFFF
        # Store to shadow memory
        self._mem_store_word(new_sp, ax)
        # Override SP and STACK0 in context
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_register_in_last_step(context, Token.STACK0, ax)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_add(self, context, output):
        """ADD -- Addition: AX = pop + AX."""
        rhs = self._last_ax
        lhs = self._mem_load_word(self._last_sp)
        result = (lhs + rhs) & 0xFFFFFFFF
        new_sp = (self._last_sp + 8) & 0xFFFFFFFF
        # Override SP and AX
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_ax_in_last_step(context, result)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_sub(self, context, output):
        """SUB -- Subtraction: AX = pop - AX."""
        rhs = self._last_ax
        lhs = self._mem_load_word(self._last_sp)
        result = (lhs - rhs) & 0xFFFFFFFF
        new_sp = (self._last_sp + 8) & 0xFFFFFFFF
        # Override SP and AX
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_ax_in_last_step(context, result)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_or(self, context, output):
        """OR -- Bitwise OR: AX = pop | AX."""
        rhs = self._last_ax
        lhs = self._mem_load_word(self._last_sp)
        result = (lhs | rhs) & 0xFFFFFFFF
        new_sp = (self._last_sp + 8) & 0xFFFFFFFF
        # Override SP and AX
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_ax_in_last_step(context, result)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_xor(self, context, output):
        """XOR -- Bitwise XOR: AX = pop ^ AX."""
        rhs = self._last_ax
        lhs = self._mem_load_word(self._last_sp)
        result = (lhs ^ rhs) & 0xFFFFFFFF
        new_sp = (self._last_sp + 8) & 0xFFFFFFFF
        # Override SP and AX
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_ax_in_last_step(context, result)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_and(self, context, output):
        """AND -- Bitwise AND: AX = pop & AX."""
        rhs = self._last_ax
        lhs = self._mem_load_word(self._last_sp)
        result = (lhs & rhs) & 0xFFFFFFFF
        new_sp = (self._last_sp + 8) & 0xFFFFFFFF
        # Override SP and AX
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_ax_in_last_step(context, result)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_shl(self, context, output):
        """SHL -- Left shift: AX = pop << AX."""
        rhs = self._last_ax
        lhs = self._mem_load_word(self._last_sp)
        result = (lhs << (rhs & 0x1F)) & 0xFFFFFFFF
        new_sp = (self._last_sp + 8) & 0xFFFFFFFF
        # Override SP and AX
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_ax_in_last_step(context, result)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_shr(self, context, output):
        """SHR -- Right shift: AX = pop >> AX."""
        rhs = self._last_ax
        lhs = self._mem_load_word(self._last_sp)
        result = (lhs >> (rhs & 0x1F)) & 0xFFFFFFFF
        new_sp = (self._last_sp + 8) & 0xFFFFFFFF
        # Override SP and AX
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_ax_in_last_step(context, result)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_mul(self, context, output):
        """MUL -- Multiply: AX = pop * AX."""
        rhs = self._last_ax
        lhs = self._mem_load_word(self._last_sp)
        result = (lhs * rhs) & 0xFFFFFFFF
        new_sp = (self._last_sp + 8) & 0xFFFFFFFF
        # Override SP and AX
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_ax_in_last_step(context, result)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_div(self, context, output):
        """DIV -- Divide: AX = pop / AX."""
        rhs = self._last_ax
        lhs = self._mem_load_word(self._last_sp)
        if rhs != 0:
            result = (lhs // rhs) & 0xFFFFFFFF
        else:
            result = 0  # division by zero
        new_sp = (self._last_sp + 8) & 0xFFFFFFFF
        # Override SP and AX
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_ax_in_last_step(context, result)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_mod(self, context, output):
        """MOD -- Modulo: AX = pop % AX."""
        rhs = self._last_ax
        lhs = self._mem_load_word(self._last_sp)
        if rhs != 0:
            result = (lhs % rhs) & 0xFFFFFFFF
        else:
            result = 0  # mod by zero
        new_sp = (self._last_sp + 8) & 0xFFFFFFFF
        # Override SP and AX
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_ax_in_last_step(context, result)
        # Advance PC
        exec_pc = self._exec_pc()
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)

    def _handler_lea(self, context, output):
        """LEA -- AX = BP + signed immediate."""
        exec_pc = self._exec_pc()
        exec_idx = exec_pc // INSTR_WIDTH
        if exec_idx < 0 or exec_idx >= len(self._bytecode):
            return
        instr = self._bytecode[exec_idx]
        imm = instr >> 8
        # Sign-extend 24-bit immediate
        if imm >= 0x800000:
            imm -= 0x1000000
        bp = self._last_bp
        result = (bp + imm) & 0xFFFFFFFF
        self._override_ax_in_last_step(context, result)

    def _handler_jsr(self, context, output):
        """JSR -- push return address, jump to target.

        Return address = exec_pc (JSR's own address).
        When LEV pops this and sets output PC = return_addr,
        the next step's exec_pc = return_addr + 5, which is
        the instruction after JSR.

        Also overrides PC to the jump target. The weight-based JMP relay
        has a one-step delay (reads previous step's AX flags), so it
        cannot fire on the first step. The runner ensures correctness
        by always overriding PC for JSR.
        """
        exec_pc = self._exec_pc()
        exec_idx = exec_pc // INSTR_WIDTH
        if exec_idx < 0 or exec_idx >= len(self._bytecode):
            return
        instr = self._bytecode[exec_idx]
        target = instr >> 8  # raw immediate = jump target PC value
        # Return address is the instruction AFTER JSR
        return_addr = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF

        # Read current SP from the just-generated step (not _last_sp which may be stale)
        current_sp = self._extract_register(context, Token.REG_SP)
        if current_sp is None:
            current_sp = self._last_sp
        new_sp = (current_sp - 8) & 0xFFFFFFFF


        # TEMPORARY: Restore ALL JSR overrides to verify baseline works
        # TODO: Remove overrides one by one after fixing issues
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_register_in_last_step(context, Token.STACK0, return_addr)
        self._override_register_in_last_step(context, Token.REG_PC, target)
        # Store return address in shadow memory
        self._mem_store_word(new_sp, return_addr)

    def _handler_ent(self, context, output):
        """ENT -- push BP, set new frame, allocate locals.

        *--sp = bp;  bp = sp;  sp -= imm;
        """
        exec_pc = self._exec_pc()
        exec_idx = exec_pc // INSTR_WIDTH
        if exec_idx < 0 or exec_idx >= len(self._bytecode):
            return
        instr = self._bytecode[exec_idx]
        imm = instr >> 8
        # Sign-extend 24-bit immediate
        if imm >= 0x800000:
            imm -= 0x1000000

        # CRITICAL: Use _last_sp/_last_bp, NOT model output!
        # ENT must see JSR's overridden SP. The model output is stale/wrong.
        old_sp = self._last_sp
        old_bp = self._last_bp

        # Push old BP: *--sp = bp
        push_addr = (old_sp - 8) & 0xFFFFFFFF
        # bp = sp (after push)
        new_bp = push_addr
        # sp -= imm (allocate locals)
        new_sp = (new_bp - imm) & 0xFFFFFFFF

        # Override all registers
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_register_in_last_step(context, Token.REG_BP, new_bp)
        self._override_register_in_last_step(context, Token.STACK0, old_bp)
        # ENT advances PC by INSTR_WIDTH (like other func_call handlers override PC)
        next_pc = (exec_pc + INSTR_WIDTH) & 0xFFFFFFFF
        self._override_register_in_last_step(context, Token.REG_PC, next_pc)
        # Shadow memory: store old BP at push_addr
        self._mem_store_word(push_addr, old_bp)

    def _handler_lev(self, context, output):
        """LEV -- restore frame, return.

        sp = bp;  bp = *sp++;  pc = *sp++;
        So: saved_bp = mem[old_bp], return_addr = mem[old_bp + 8]
        new_sp = old_bp + 16, new_bp = saved_bp, pc = return_addr
        """
        # CRITICAL: Use _last_bp, not model output!
        # LEV must see ENT's overridden BP. The model output is stale/wrong.
        old_bp = self._last_bp
        saved_bp = self._mem_load_word(old_bp)
        return_addr = self._mem_load_word(old_bp + 8)
        new_sp = (old_bp + 16) & 0xFFFFFFFF

        # Override all registers
        self._override_register_in_last_step(context, Token.REG_SP, new_sp)
        self._override_register_in_last_step(context, Token.REG_BP, saved_bp)
        self._override_register_in_last_step(context, Token.REG_PC, return_addr)
        # STACK0 = *new_sp (top of stack after restoring frame)
        stack0_val = self._mem_load_word(new_sp)
        self._override_register_in_last_step(context, Token.STACK0, stack0_val)

    def _decode_exit_code(self, context):
        """Extract exit code from the last REG_AX before HALT."""
        for i in range(len(context) - 1, -1, -1):
            if context[i] == Token.REG_AX and i + 4 < len(context):
                val = 0
                for j in range(4):
                    val |= (context[i + 1 + j] & 0xFF) << (j * 8)
                return val
        return 0


# =============================================================================
# Demo / Test
# =============================================================================


def demo():
    """Demonstrate autoregressive VM runner."""
    print("=" * 60)
    print("AUTOREGRESSIVE VM RUNNER")
    print("Decoder-only transformer with generation loop")
    print("=" * 60)

    # Test 1: Build context for a simple program
    print("\n--- Context Building ---")
    runner = AutoregressiveVMRunner()

    program = [
        Opcode.IMM | (42 << 8),  # IMM 42
        Opcode.EXIT,  # EXIT
    ]

    runner._bytecode = program
    ctx = runner._build_context(program, b"", [])
    print(f"Program: IMM 42; EXIT")
    print(f"Context length: {len(ctx)} tokens")
    print(f"Tokens: {ctx}")

    # Verify context structure
    assert ctx[0] == Token.CODE_START
    assert ctx[1] == Opcode.IMM  # First instruction opcode
    assert ctx[2] == 42  # Immediate byte 0
    assert ctx[3] == 0  # Immediate byte 1
    assert ctx[4] == 0  # Immediate byte 2
    assert ctx[5] == 0  # Immediate byte 3
    assert ctx[6] == Opcode.EXIT  # Second instruction opcode
    code_end_idx = ctx.index(Token.CODE_END)
    print(f"CODE section: tokens 0..{code_end_idx}")
    print(f"Context verified OK")

    # Test 2: Model forward pass
    print("\n--- Model Forward Pass ---")
    model = runner.model
    param_count = sum(p.numel() for p in model.parameters())
    print(f"Model parameters: {param_count:,}")

    token_ids = torch.tensor([ctx], dtype=torch.long)
    with torch.no_grad():
        logits = model(token_ids)
    print(f"Input shape:  {token_ids.shape}")
    print(f"Output shape: {logits.shape}")
    print(f"Output vocab: {logits.shape[-1]} (expected {Token.VOCAB_SIZE})")

    # Test 3: Single token generation
    print("\n--- Token Generation ---")
    next_token = model.generate_next(ctx)
    print(f"Generated next token: {next_token}")
    print(f"(Note: random with unset weights)")

    # Test 4: Context building with data and argv
    print("\n--- Context with Data & Argv ---")
    program2 = [
        Opcode.IMM | (5 << 8),
        Opcode.PSH,
        Opcode.IMM | (3 << 8),
        Opcode.ADD,
        Opcode.EXIT,
    ]
    ctx2 = runner._build_context(
        program2, b"\x48\x65\x6c\x6c\x6f", ["hello", "world"], ""
    )
    print(f"Program: IMM 5; PSH; IMM 3; ADD; EXIT")
    print(f"Data: b'Hello'")
    print(f"Argv: ['hello', 'world']")
    print(f"Context length: {len(ctx2)} tokens")

    data_start = ctx2.index(Token.DATA_START)
    data_end = ctx2.index(Token.DATA_END)
    print(f"DATA section: tokens {data_start}..{data_end}")
    print(f"Data bytes: {ctx2[data_start + 1 : data_end]}")

    print("\n" + "=" * 60)
    print("Demo complete!")
    print("Note: Model has zero/random weights. Correct output requires")
    print("weight setting (follow-up step).")
    print("=" * 60)


if __name__ == "__main__":
    demo()
